"use strict";

window.WONDERLAND_GRIMORIO = [
  {
    id: "bola-de-fogo",
    nome: "Bola de Fogo",
    categoria: "Magia",
    origemTipo: "Classe",
    origem: "Mago",
    nivel: 20,
    atributo: "INT",
    custo: "40 Mana",
    recarga: "2 turnos",
    alcance: "8 metros",
    area: "Raio de 2 metros",
    tags: ["Fogo", "Área", "Dano mágico"],
    descricao: "Conjura uma esfera flamejante que explode no ponto escolhido, causando dano mágico aos inimigos na área.",
    efeito: "Causa 150% de INT como dano mágico. Alvos atingidos recebem Queimadura por 2 turnos, sofrendo 20% de INT por turno.",
    observacoes: "A explosão não distingue aliados de inimigos quando usada em espaços apertados."
  },
  {
    id: "barreira-arcana",
    nome: "Barreira Arcana",
    categoria: "Proteção",
    origemTipo: "Classe",
    origem: "Mago",
    nivel: 10,
    atributo: "ARC",
    custo: "30 Mana",
    recarga: "3 turnos",
    alcance: "Próprio ou aliado a 5 metros",
    area: "Alvo único",
    tags: ["Escudo", "Proteção", "Arcano"],
    descricao: "Reveste o alvo com uma camada de energia mágica condensada.",
    efeito: "Concede um escudo equivalente a 120% de ARC por 2 turnos. Enquanto o escudo existir, o alvo recebe 15% menos dano mágico.",
    observacoes: "Não acumula com outra Barreira Arcana do mesmo conjurador."
  },
  {
    id: "passo-sombrio",
    nome: "Passo Sombrio",
    categoria: "Mobilidade",
    origemTipo: "Classe",
    origem: "Assassino",
    nivel: 20,
    atributo: "INI",
    custo: "25 Energia",
    recarga: "2 turnos",
    alcance: "6 metros",
    area: "Movimento próprio",
    tags: ["Mobilidade", "Sombra", "Reposicionamento"],
    descricao: "O usuário atravessa as sombras e reaparece em um ponto próximo.",
    efeito: "Move-se instantaneamente até 6 metros. O próximo ataque realizado no mesmo turno recebe 30% de INI como dano adicional.",
    observacoes: "Não atravessa paredes sólidas ou barreiras mágicas."
  },
  {
    id: "rugido-alfa",
    nome: "Rugido Alfa",
    categoria: "Controle",
    origemTipo: "Raça",
    origem: "Lobisomem",
    nivel: 1,
    atributo: "RES",
    custo: "Sem custo",
    recarga: "4 turnos",
    alcance: "Próprio",
    area: "Raio de 5 metros",
    tags: ["Medo", "Área", "Racial"],
    descricao: "Um rugido brutal que abala a coragem dos inimigos próximos.",
    efeito: "Inimigos na área fazem um teste de RES. Em caso de falha, recebem Medo por 1 turno e causam 20% menos dano durante o efeito.",
    observacoes: "Alvos imunes a efeitos mentais não podem receber Medo."
  },
  {
    id: "luz-serafica",
    nome: "Luz Seráfica",
    categoria: "Suporte",
    origemTipo: "Raça",
    origem: "Aengel",
    nivel: 20,
    atributo: "ARC",
    custo: "35 Mana",
    recarga: "3 turnos",
    alcance: "6 metros",
    area: "Alvo único",
    tags: ["Cura", "Luz", "Racial"],
    descricao: "Canaliza uma luz ancestral sobre um aliado ferido.",
    efeito: "Restaura 140% de ARC em HP e remove um efeito negativo comum.",
    observacoes: "Efeitos de execução, maldição ancestral ou transformação não podem ser removidos."
  },
  {
    id: "chamas-draconicas",
    nome: "Chamas Dracônicas",
    categoria: "Área",
    origemTipo: "Raça",
    origem: "Draconato",
    nivel: 1,
    atributo: "FOR",
    custo: "1 Acúmulo Dracônico",
    recarga: "2 turnos",
    alcance: "Cone de 5 metros",
    area: "Cone frontal",
    tags: ["Fogo", "Área", "Dracônico"],
    descricao: "Expele uma rajada elemental moldada pela linhagem do Draconato.",
    efeito: "Causa 130% de FOR como dano elemental em cone. O tipo de dano acompanha o elemento racial escolhido.",
    observacoes: "Pode aplicar efeitos adicionais conforme o elemento da linhagem."
  },
  {
    id: "invocacao-do-corvo-oco",
    nome: "Invocação do Corvo Oco",
    categoria: "Invocação",
    origemTipo: "Classe",
    origem: "Bruxo",
    nivel: 30,
    atributo: "ARC",
    custo: "45 Mana",
    recarga: "4 turnos",
    alcance: "4 metros",
    area: "Espaço livre",
    tags: ["Invocação", "Maldição", "Controle"],
    descricao: "Invoca uma criatura sombria que persegue o alvo marcado.",
    efeito: "O Corvo Oco permanece por 3 turnos, ataca com 80% de ARC e reduz em 10% a RES do alvo atingido.",
    observacoes: "Só pode existir um Corvo Oco por conjurador."
  },
  {
    id: "morte-sem-rosto",
    nome: "Morte sem Rosto",
    categoria: "Ultimate",
    origemTipo: "Caminho",
    origem: "Bruxo — Caminho da Morte",
    nivel: 100,
    atributo: "INT",
    custo: "100 Mana",
    recarga: "Uma vez por combate",
    alcance: "10 metros",
    area: "Alvo único",
    tags: ["Execução", "Maldição", "Ultimate"],
    descricao: "Manifesta a forma inevitável da morte sobre um inimigo condenado.",
    efeito: "Causa 300% de INT como dano mágico. Contra alvos abaixo de 20% de HP, executa imediatamente se não forem imunes a execução.",
    observacoes: "Chefes podem possuir resistência parcial ou imunidade à execução."
  }
];
