export const firstDungeon = {
  key: "ruinas-de-verdantia",
  name: "Ruínas de Verdantia",
  rank: "E",
  minimumPlayers: 4,
  recommendedLevel: "1–10",
  description:
    "Uma patrulha desapareceu sob as antigas muralhas cobertas de musgo. Reúna quatro aventureiros e interrompa a infestação antes que alcance as trilhas de Aokigahara.",
  encounters: [
    {
      key: "batedor-musgoso",
      name: "Batedor Musgoso",
      role: "Atacante",
      imageUrl: "/images/monsters/dungeon-e/batedor-musgoso.webp",
      weights: [6, 2, 3, 5, 1, 2],
      hpScale: 0.65,
      abilities: ["Emboscada de Esporos", "Passo entre Raízes"],
    },
    {
      key: "limo-runico",
      name: "Limo Rúnico",
      role: "Controle",
      imageUrl: "/images/monsters/dungeon-e/limo-runico.webp",
      weights: [2, 3, 5, 2, 5, 4],
      hpScale: 0.8,
      abilities: ["Prisão Rúnica", "Regeneração Viscosa"],
    },
    {
      key: "kobold-tunel",
      name: "Kobold do Túnel",
      role: "Defensor",
      imageUrl: "/images/monsters/dungeon-e/kobold-tunel.webp",
      weights: [4, 6, 5, 3, 1, 2],
      hpScale: 1,
      abilities: ["Muralha do Túnel", "Investida Calculada"],
    },
    {
      key: "rei-rato",
      name: "Rei Rato Coroado",
      role: "Chefe",
      imageUrl: "/images/monsters/dungeon-e/rei-rato-coroado.webp",
      weights: [6, 4, 5, 5, 3, 3],
      hpScale: 1.45,
      abilities: ["Decreto da Colônia", "Banquete do Rei", "Cauda Pestilenta"],
    },
  ],
} as const;
