import { classSkillSchema, racePayloadSchema, type AttributeKey } from "@/lib/game/schemas";
import type { RacePayload } from "@/lib/game/races";

export interface OfficialRaceDefinition {
  name: string;
  slug: string;
  payload: RacePayload;
}

type Operation =
  | "DAMAGE"
  | "HEAL"
  | "SHIELD"
  | "BUFF"
  | "DEBUFF"
  | "STUN"
  | "ROOT"
  | "FEAR"
  | "MOVE"
  | "TELEPORT"
  | "APPLY_STATUS"
  | "REMOVE_STATUS"
  | "TAUNT"
  | "REACTION";
type Kind = "damage" | "heal" | "shield" | "utility";

interface AbilitySeed {
  key: string;
  name: string;
  level: number;
  category: string;
  operation: Operation;
  kind: Kind;
  target: "self" | "ally" | "enemy" | "area";
  attribute?: AttributeKey;
  multiplier?: number;
  cost?: number;
  cooldown?: number;
  range?: number;
  area?: number;
  duration?: number;
  status?: string;
  damageType?: "physical" | "magic" | "true" | "none";
  description: string;
  type?: "Ativa" | "Passiva" | "Reação";
}

interface RaceSeed {
  name: string;
  slug: string;
  difficulty: number;
  specialization: string;
  description: string;
  tags: string[];
  hp: number;
  mana: number;
  bonuses: Record<AttributeKey, number>;
  resource: { name: string; maximum: number };
  passive: AbilitySeed;
  skills: AbilitySeed[];
}

function buildAbility(seed: AbilitySeed) {
  const scaling = seed.attribute
    ? [{ attribute: seed.attribute, multiplier: seed.multiplier ?? 1 }]
    : [];
  const passive = seed.type === "Passiva";
  return classSkillSchema.parse({
    key: seed.key,
    name: seed.name,
    level: seed.level,
    type: seed.type ?? "Ativa",
    category: seed.category,
    effect: seed.description,
    kind: seed.kind,
    damageType: seed.damageType ?? "none",
    target: seed.target,
    resource: passive ? "none" : "special",
    resourceKey: "race",
    cost: passive ? 0 : (seed.cost ?? 1),
    cooldown: seed.cooldown ?? 0,
    range: seed.range ?? 0,
    area: seed.area ?? 0,
    duration: seed.duration ?? 0,
    scaling,
    reachText: seed.area
      ? `${seed.range ?? 0} casas; área ${seed.area}`
      : `${seed.range ?? 0} casa(s)`,
    conditions: passive ? ["Resolve automaticamente quando o gatilho descrito ocorrer."] : [],
    systemRule: `Valide custo, alvo, alcance e recarga. Execute ${seed.operation}. Arredonde o resultado final para o inteiro mais próximo; empate .5 arredonda para cima.`,
    playerDescription: seed.description,
    chance: 100,
    maxStacks: 1,
    operations: [
      {
      operation: seed.operation,
      target: seed.target,
      base: 0,
      scaling,
      damageType: seed.damageType ?? "none",
      status: seed.status ?? "",
      duration: seed.duration ?? 0,
      chance: 100,
      stacks: seed.status ? 1 : 0,
      maxStacks: seed.status ? 1 : 0,
        distance: ["MOVE", "TELEPORT", "PUSH"].includes(seed.operation) ? (seed.range ?? 2) : 0,
      modifiers: [],
      },
    ],
  });
}

function buildRace(seed: RaceSeed): OfficialRaceDefinition {
  const passive = buildAbility(seed.passive);
  const abilities = seed.skills.map(buildAbility);
  const resource = {
    name: seed.resource.name,
    initial: 0,
    maximum: seed.resource.maximum,
    generationEvents: [{ trigger: "BASIC_ATTACK_HIT", amount: 1, limitPerAction: 1 }],
    consumptionRules: [
      `Habilidades raciais consomem ${seed.resource.name}; o valor nunca fica abaixo de 0.`,
    ],
    resetRules: [`No início e no fim do combate, ${seed.resource.name} retorna a 0.`],
  };
  return {
    name: seed.name,
    slug: seed.slug,
    payload: racePayloadSchema.parse({
      engineContractVersion: 1,
      specialization: seed.specialization,
      tags: seed.tags,
      description: seed.description,
      imageUrl: "",
      difficulty: seed.difficulty,
      baseHp: seed.hp,
      baseMana: 0,
      attributeBonuses: seed.bonuses,
      resource,
      mechanics: [
        {
          name: seed.resource.name,
          description: `Ganha 1 ponto ao acertar um ataque básico. Limite ${seed.resource.maximum}. Habilidades raciais consomem esse recurso.`,
        },
      ],
      traits: [{ name: seed.passive.name, description: seed.passive.description }],
      traitsV2: [passive],
      progression: abilities.map((ability) => ({
        level: ability.level,
        title: ability.name,
        description: ability.playerDescription,
      })),
      abilitiesV2: abilities,
    }),
  };
}

const seeds: RaceSeed[] = [
  {
    name: "Aengel",
    slug: "aengel",
    difficulty: 3,
    specialization: "Proteção celestial e suporte",
    tags: ["HUMANOIDE", "CELESTIAL", "AENGEL"],
    hp: 460,
    mana: 120,
    description:
      "Descendentes da Luz Primordial que protegem aliados com radiância, cura e escudos.",
    bonuses: { FOR: 1, DEF: 3, RES: 3, INI: 1, INT: 2, ARC: 5 },
    resource: { name: "Radiância", maximum: 5 },
    passive: {
      key: "luz-celestial",
      name: "Luz Celestial",
      level: 1,
      type: "Passiva",
      category: "Reação",
      operation: "REACTION",
      kind: "utility",
      target: "self",
      description: "Ao aplicar cura ou escudo, gera 1 Radiância, uma vez por ação.",
    },
    skills: [
      {
        key: "julgamento-da-alvorada",
        name: "Julgamento da Alvorada",
        level: 1,
        category: "Dano",
        operation: "DAMAGE",
        kind: "damage",
        target: "enemy",
        attribute: "ARC",
        multiplier: 1.1,
        cost: 1,
        cooldown: 1,
        range: 4,
        damageType: "magic",
        description: "Causa 1,1x ARC de dano mágico a um inimigo.",
      },
      {
        key: "halo-protetor",
        name: "Halo Protetor",
        level: 25,
        category: "Escudo",
        operation: "SHIELD",
        kind: "shield",
        target: "ally",
        attribute: "ARC",
        multiplier: 1.4,
        cost: 2,
        cooldown: 3,
        range: 4,
        duration: 2,
        description: "Concede escudo de 1,4x ARC por 2 rodadas.",
      },
      {
        key: "graca-purificadora",
        name: "Graça Purificadora",
        level: 50,
        category: "Purificação",
        operation: "REMOVE_STATUS",
        kind: "utility",
        target: "ally",
        cost: 2,
        cooldown: 4,
        range: 4,
        description: "Remove um status negativo comum de um aliado.",
      },
      {
        key: "ascensao-serafinica",
        name: "Ascensão Serafínica",
        level: 80,
        category: "Transformação",
        operation: "APPLY_STATUS",
        kind: "utility",
        target: "self",
        cost: 5,
        cooldown: 8,
        duration: 3,
        status: "forma-serafinica",
        description:
          "Entra na Forma Serafínica por 3 rodadas; o estado fortalece efeitos celestiais conforme as regras da Arena.",
      },
    ],
  },
  {
    name: "Draconato",
    slug: "draconato",
    difficulty: 4,
    specialization: "Dano elemental e resistência",
    tags: ["HUMANOIDE", "DRACONICO"],
    hp: 620,
    mana: 80,
    description:
      "Herdeiros de dragões primordiais que acumulam poder para liberar ataques elementais.",
    bonuses: { FOR: 5, DEF: 3, RES: 3, INI: 1, INT: 2, ARC: 1 },
    resource: { name: "Carga Dracônica", maximum: 5 },
    passive: {
      key: "escamas-ancestrais",
      name: "Escamas Ancestrais",
      level: 1,
      type: "Passiva",
      category: "Defesa",
      operation: "REACTION",
      kind: "utility",
      target: "self",
      description:
        "Ao receber dano igual ou superior a 10% do HP máximo, gera 1 Carga Dracônica, uma vez por ação.",
    },
    skills: [
      {
        key: "sopro-elemental",
        name: "Sopro Elemental",
        level: 1,
        category: "Dano em área",
        operation: "DAMAGE",
        kind: "damage",
        target: "area",
        attribute: "FOR",
        multiplier: 1.2,
        cost: 1,
        cooldown: 2,
        range: 3,
        area: 2,
        damageType: "magic",
        description: "Causa 1,2x FOR de dano mágico elemental em área 2.",
      },
      {
        key: "couraca-ancestral",
        name: "Couraça Ancestral",
        level: 25,
        category: "Escudo",
        operation: "SHIELD",
        kind: "shield",
        target: "self",
        attribute: "RES",
        multiplier: 1.3,
        cost: 2,
        cooldown: 3,
        duration: 2,
        description: "Recebe escudo de 1,3x RES por 2 rodadas.",
      },
      {
        key: "rugido-de-soberania",
        name: "Rugido de Soberania",
        level: 50,
        category: "Controle",
        operation: "FEAR",
        kind: "utility",
        target: "area",
        cost: 3,
        cooldown: 5,
        range: 3,
        area: 2,
        duration: 1,
        status: "amedrontado",
        description: "Aplica Medo por 1 rodada aos inimigos na área 2.",
      },
      {
        key: "despertar-draconico",
        name: "Despertar Dracônico",
        level: 80,
        category: "Transformação",
        operation: "APPLY_STATUS",
        kind: "utility",
        target: "self",
        cost: 5,
        cooldown: 8,
        duration: 3,
        status: "forma-draconica",
        description: "Assume a Forma Dracônica por 3 rodadas.",
      },
    ],
  },
  {
    name: "Lobisomem",
    slug: "lobisomem",
    difficulty: 3,
    specialization: "Caça, regeneração e investida",
    tags: ["HUMANOIDE", "BESTIAL", "LICANTROPO"],
    hp: 600,
    mana: 60,
    description:
      "Caçadores licantropos que crescem em ferocidade enquanto perseguem alvos feridos.",
    bonuses: { FOR: 5, DEF: 2, RES: 4, INI: 3, INT: 0, ARC: 1 },
    resource: { name: "Faro de Sangue", maximum: 5 },
    passive: {
      key: "predador-lunar",
      name: "Predador Lunar",
      level: 1,
      type: "Passiva",
      category: "Reação",
      operation: "REACTION",
      kind: "utility",
      target: "self",
      description:
        "Ao atingir um inimigo abaixo de 50% de HP, gera 1 Faro de Sangue adicional, uma vez por ação.",
    },
    skills: [
      {
        key: "garras-da-cacada",
        name: "Garras da Caçada",
        level: 1,
        category: "Dano",
        operation: "DAMAGE",
        kind: "damage",
        target: "enemy",
        attribute: "FOR",
        multiplier: 1.3,
        cost: 1,
        cooldown: 1,
        range: 1,
        damageType: "physical",
        description: "Causa 1,3x FOR de dano físico.",
      },
      {
        key: "regeneracao-lunar",
        name: "Regeneração Lunar",
        level: 25,
        category: "Cura",
        operation: "HEAL",
        kind: "heal",
        target: "self",
        attribute: "RES",
        multiplier: 1.1,
        cost: 2,
        cooldown: 3,
        description: "Recupera 1,1x RES de HP.",
      },
      {
        key: "salto-do-alfa",
        name: "Salto do Alfa",
        level: 50,
        category: "Mobilidade",
        operation: "MOVE",
        kind: "utility",
        target: "self",
        cost: 2,
        cooldown: 3,
        range: 2,
        description: "Move até 2 casas ignorando unidades intermediárias.",
      },
      {
        key: "forma-da-lua-cheia",
        name: "Forma da Lua Cheia",
        level: 80,
        category: "Transformação",
        operation: "APPLY_STATUS",
        kind: "utility",
        target: "self",
        cost: 5,
        cooldown: 8,
        duration: 3,
        status: "forma-lunar",
        description: "Entra na Forma Lunar por 3 rodadas.",
      },
    ],
  },
  {
    name: "Kitsune",
    slug: "kitsune",
    difficulty: 4,
    specialization: "Ilusão, magia e controle",
    tags: ["HUMANOIDE", "ESPIRITO", "VULPINO"],
    hp: 430,
    mana: 140,
    description: "Espíritos vulpinos que manipulam chamas, ilusões e a percepção dos inimigos.",
    bonuses: { FOR: 0, DEF: 1, RES: 2, INI: 4, INT: 5, ARC: 3 },
    resource: { name: "Caudas Místicas", maximum: 9 },
    passive: {
      key: "astucia-vulpina",
      name: "Astúcia Vulpina",
      level: 1,
      type: "Passiva",
      category: "Reação",
      operation: "REACTION",
      kind: "utility",
      target: "self",
      description: "Ao aplicar um status negativo, gera 1 Cauda Mística, uma vez por ação.",
    },
    skills: [
      {
        key: "chama-da-raposa",
        name: "Chama da Raposa",
        level: 1,
        category: "Dano",
        operation: "DAMAGE",
        kind: "damage",
        target: "enemy",
        attribute: "INT",
        multiplier: 1.2,
        cost: 1,
        cooldown: 1,
        range: 4,
        damageType: "magic",
        description: "Causa 1,2x INT de dano mágico.",
      },
      {
        key: "espelho-enganador",
        name: "Espelho Enganador",
        level: 25,
        category: "Escudo",
        operation: "SHIELD",
        kind: "shield",
        target: "self",
        attribute: "ARC",
        multiplier: 1.2,
        cost: 2,
        cooldown: 3,
        duration: 2,
        description: "Cria um escudo ilusório de 1,2x ARC por 2 rodadas.",
      },
      {
        key: "encanto-vulpino",
        name: "Encanto Vulpino",
        level: 50,
        category: "Controle",
        operation: "STUN",
        kind: "utility",
        target: "enemy",
        cost: 3,
        cooldown: 5,
        range: 4,
        duration: 1,
        status: "encantado",
        description: "Atordoa um inimigo por 1 rodada.",
      },
      {
        key: "manto-das-nove-caudas",
        name: "Manto das Nove Caudas",
        level: 80,
        category: "Transformação",
        operation: "APPLY_STATUS",
        kind: "utility",
        target: "self",
        cost: 9,
        cooldown: 8,
        duration: 3,
        status: "nove-caudas",
        description: "Ativa o Manto das Nove Caudas por 3 rodadas.",
      },
    ],
  },
  {
    name: "Leonis",
    slug: "leonis",
    difficulty: 2,
    specialization: "Liderança e combate físico",
    tags: ["HUMANOIDE", "BESTIAL", "LEONIS"],
    hp: 580,
    mana: 70,
    description: "Guerreiros leoninos cuja coragem protege aliados e pressiona inimigos.",
    bonuses: { FOR: 5, DEF: 3, RES: 3, INI: 2, INT: 0, ARC: 2 },
    resource: { name: "Bravura", maximum: 5 },
    passive: {
      key: "coracao-do-bando",
      name: "Coração do Bando",
      level: 1,
      type: "Passiva",
      category: "Reação",
      operation: "REACTION",
      kind: "utility",
      target: "self",
      description: "Ao proteger ou provocar um inimigo, gera 1 Bravura, uma vez por ação.",
    },
    skills: [
      {
        key: "garra-real",
        name: "Garra Real",
        level: 1,
        category: "Dano",
        operation: "DAMAGE",
        kind: "damage",
        target: "enemy",
        attribute: "FOR",
        multiplier: 1.25,
        cost: 1,
        cooldown: 1,
        range: 1,
        damageType: "physical",
        description: "Causa 1,25x FOR de dano físico.",
      },
      {
        key: "rugido-do-guardiao",
        name: "Rugido do Guardião",
        level: 25,
        category: "Provocação",
        operation: "TAUNT",
        kind: "utility",
        target: "area",
        cost: 2,
        cooldown: 4,
        range: 2,
        area: 2,
        duration: 1,
        status: "provocado",
        description: "Provoca inimigos na área 2 por 1 rodada.",
      },
      {
        key: "egide-do-bando",
        name: "Égide do Bando",
        level: 50,
        category: "Escudo",
        operation: "SHIELD",
        kind: "shield",
        target: "ally",
        attribute: "DEF",
        multiplier: 1.4,
        cost: 3,
        cooldown: 4,
        range: 3,
        duration: 2,
        description: "Concede 1,4x DEF de escudo a um aliado por 2 rodadas.",
      },
      {
        key: "soberano-da-savana",
        name: "Soberano da Savana",
        level: 80,
        category: "Buff",
        operation: "APPLY_STATUS",
        kind: "utility",
        target: "self",
        cost: 5,
        cooldown: 8,
        duration: 3,
        status: "soberania-leonis",
        description: "Ativa Soberania Leonis por 3 rodadas.",
      },
    ],
  },
  {
    name: "Tiefling",
    slug: "tiefling",
    difficulty: 4,
    specialization: "Magia infernal e debuffs",
    tags: ["HUMANOIDE", "INFERNAL"],
    hp: 470,
    mana: 130,
    description: "Portadores de herança infernal que convertem marcas e fogo sombrio em controle.",
    bonuses: { FOR: 1, DEF: 1, RES: 3, INI: 2, INT: 5, ARC: 3 },
    resource: { name: "Marca Infernal", maximum: 5 },
    passive: {
      key: "sangue-infernal",
      name: "Sangue Infernal",
      level: 1,
      type: "Passiva",
      category: "Reação",
      operation: "REACTION",
      kind: "utility",
      target: "self",
      description: "Ao causar dano mágico, gera 1 Marca Infernal, uma vez por ação.",
    },
    skills: [
      {
        key: "fogo-do-abismo",
        name: "Fogo do Abismo",
        level: 1,
        category: "Dano",
        operation: "DAMAGE",
        kind: "damage",
        target: "enemy",
        attribute: "INT",
        multiplier: 1.25,
        cost: 1,
        cooldown: 1,
        range: 4,
        damageType: "magic",
        description: "Causa 1,25x INT de dano mágico.",
      },
      {
        key: "pacto-de-cinzas",
        name: "Pacto de Cinzas",
        level: 25,
        category: "Escudo",
        operation: "SHIELD",
        kind: "shield",
        target: "self",
        attribute: "RES",
        multiplier: 1.3,
        cost: 2,
        cooldown: 3,
        duration: 2,
        description: "Recebe escudo de 1,3x RES por 2 rodadas.",
      },
      {
        key: "correntes-infernais",
        name: "Correntes Infernais",
        level: 50,
        category: "Controle",
        operation: "ROOT",
        kind: "utility",
        target: "enemy",
        cost: 3,
        cooldown: 4,
        range: 4,
        duration: 2,
        status: "enraizado",
        description: "Enraíza um inimigo por 2 rodadas.",
      },
      {
        key: "avatar-do-abismo",
        name: "Avatar do Abismo",
        level: 80,
        category: "Transformação",
        operation: "APPLY_STATUS",
        kind: "utility",
        target: "self",
        cost: 5,
        cooldown: 8,
        duration: 3,
        status: "avatar-infernal",
        description: "Assume o estado Avatar Infernal por 3 rodadas.",
      },
    ],
  },
  {
    name: "Vampiro",
    slug: "vampiro",
    difficulty: 4,
    specialization: "Dreno, mobilidade e controle",
    tags: ["HUMANOIDE", "VAMPIRO", "MORTO_VIVO"],
    hp: 500,
    mana: 100,
    description: "Predadores noturnos que sustentam o combate drenando vitalidade de seus alvos.",
    bonuses: { FOR: 3, DEF: 1, RES: 3, INI: 4, INT: 2, ARC: 2 },
    resource: { name: "Sangue", maximum: 5 },
    passive: {
      key: "sede-eterna",
      name: "Sede Eterna",
      level: 1,
      type: "Passiva",
      category: "Reação",
      operation: "REACTION",
      kind: "utility",
      target: "self",
      description: "Ao causar dano a um inimigo ferido, gera 1 Sangue adicional, uma vez por ação.",
    },
    skills: [
      {
        key: "mordida-sanguinea",
        name: "Mordida Sanguínea",
        level: 1,
        category: "Dano",
        operation: "DAMAGE",
        kind: "damage",
        target: "enemy",
        attribute: "FOR",
        multiplier: 1.2,
        cost: 1,
        cooldown: 1,
        range: 1,
        damageType: "physical",
        description: "Causa 1,2x FOR de dano físico.",
      },
      {
        key: "regeneracao-carmim",
        name: "Regeneração Carmim",
        level: 25,
        category: "Cura",
        operation: "HEAL",
        kind: "heal",
        target: "self",
        attribute: "ARC",
        multiplier: 1.1,
        cost: 2,
        cooldown: 3,
        description: "Recupera 1,1x ARC de HP.",
      },
      {
        key: "passo-de-nevoa",
        name: "Passo de Névoa",
        level: 50,
        category: "Mobilidade",
        operation: "TELEPORT",
        kind: "utility",
        target: "self",
        cost: 2,
        cooldown: 3,
        range: 3,
        description: "Teleporta para uma casa válida a até 3 casas.",
      },
      {
        key: "senhor-da-noite",
        name: "Senhor da Noite",
        level: 80,
        category: "Transformação",
        operation: "APPLY_STATUS",
        kind: "utility",
        target: "self",
        cost: 5,
        cooldown: 8,
        duration: 3,
        status: "senhor-da-noite",
        description: "Assume o estado Senhor da Noite por 3 rodadas.",
      },
    ],
  },
  {
    name: "Elfo",
    slug: "elfo",
    difficulty: 3,
    specialization: "Precisão e reposicionamento",
    tags: ["HUMANOIDE", "FEERICO", "ELFO"],
    hp: 440,
    mana: 120,
    description: "Combatentes longevos que combinam precisão, mobilidade e magia ancestral.",
    bonuses: { FOR: 1, DEF: 1, RES: 2, INI: 5, INT: 4, ARC: 2 },
    resource: { name: "Foco Ancestral", maximum: 5 },
    passive: {
      key: "sentidos-ancestrais",
      name: "Sentidos Ancestrais",
      level: 1,
      type: "Passiva",
      category: "Reação",
      operation: "REACTION",
      kind: "utility",
      target: "self",
      description:
        "Ao acertar um alvo a 3 ou mais casas, gera 1 Foco Ancestral adicional, uma vez por ação.",
    },
    skills: [
      {
        key: "disparo-preciso",
        name: "Disparo Preciso",
        level: 1,
        category: "Dano",
        operation: "DAMAGE",
        kind: "damage",
        target: "enemy",
        attribute: "INI",
        multiplier: 1.2,
        cost: 1,
        cooldown: 1,
        range: 5,
        damageType: "physical",
        description: "Causa 1,2x INI de dano físico a até 5 casas.",
      },
      {
        key: "passo-da-floresta",
        name: "Passo da Floresta",
        level: 25,
        category: "Mobilidade",
        operation: "MOVE",
        kind: "utility",
        target: "self",
        cost: 1,
        cooldown: 2,
        range: 2,
        description: "Move até 2 casas.",
      },
      {
        key: "barreira-ancestral",
        name: "Barreira Ancestral",
        level: 50,
        category: "Escudo",
        operation: "SHIELD",
        kind: "shield",
        target: "ally",
        attribute: "INT",
        multiplier: 1.2,
        cost: 3,
        cooldown: 4,
        range: 4,
        duration: 2,
        description: "Concede escudo de 1,2x INT por 2 rodadas.",
      },
      {
        key: "transe-ancestral",
        name: "Transe Ancestral",
        level: 80,
        category: "Buff",
        operation: "APPLY_STATUS",
        kind: "utility",
        target: "self",
        cost: 5,
        cooldown: 8,
        duration: 3,
        status: "transe-ancestral",
        description: "Entra em Transe Ancestral por 3 rodadas.",
      },
    ],
  },
  {
    name: "Fada",
    slug: "fada",
    difficulty: 3,
    specialization: "Cura, controle e mobilidade",
    tags: ["FEERICO", "FADA"],
    hp: 390,
    mana: 150,
    description: "Seres feéricos ágeis que manipulam pó mágico, glamour e cura.",
    bonuses: { FOR: 0, DEF: 1, RES: 2, INI: 4, INT: 3, ARC: 5 },
    resource: { name: "Pó Feérico", maximum: 5 },
    passive: {
      key: "asas-feericas",
      name: "Asas Feéricas",
      level: 1,
      type: "Passiva",
      category: "Reação",
      operation: "REACTION",
      kind: "utility",
      target: "self",
      description:
        "Ao curar, proteger ou controlar um alvo, gera 1 Pó Feérico adicional, uma vez por ação.",
    },
    skills: [
      {
        key: "centelha-feerica",
        name: "Centelha Feérica",
        level: 1,
        category: "Dano",
        operation: "DAMAGE",
        kind: "damage",
        target: "enemy",
        attribute: "ARC",
        multiplier: 1.1,
        cost: 1,
        cooldown: 1,
        range: 4,
        damageType: "magic",
        description: "Causa 1,1x ARC de dano mágico.",
      },
      {
        key: "po-restaurador",
        name: "Pó Restaurador",
        level: 25,
        category: "Cura",
        operation: "HEAL",
        kind: "heal",
        target: "ally",
        attribute: "ARC",
        multiplier: 1.3,
        cost: 2,
        cooldown: 3,
        range: 4,
        description: "Cura um aliado em 1,3x ARC.",
      },
      {
        key: "glamour-paralisante",
        name: "Glamour Paralisante",
        level: 50,
        category: "Controle",
        operation: "STUN",
        kind: "utility",
        target: "enemy",
        cost: 3,
        cooldown: 5,
        range: 4,
        duration: 1,
        status: "atordoado",
        description: "Atordoa um inimigo por 1 rodada.",
      },
      {
        key: "rainha-do-glamour",
        name: "Rainha do Glamour",
        level: 80,
        category: "Transformação",
        operation: "APPLY_STATUS",
        kind: "utility",
        target: "self",
        cost: 5,
        cooldown: 8,
        duration: 3,
        status: "glamour-supremo",
        description: "Ativa o Glamour Supremo por 3 rodadas.",
      },
    ],
  },
  {
    name: "Humano",
    slug: "humano",
    difficulty: 1,
    specialization: "Adaptação e versatilidade",
    tags: ["HUMANOIDE", "HUMANO"],
    hp: 500,
    mana: 100,
    description: "Aventureiros adaptáveis que respondem a diferentes situações com determinação.",
    bonuses: { FOR: 3, DEF: 2, RES: 2, INI: 3, INT: 3, ARC: 2 },
    resource: { name: "Determinação", maximum: 5 },
    passive: {
      key: "adaptabilidade",
      name: "Adaptabilidade",
      level: 1,
      type: "Passiva",
      category: "Reação",
      operation: "REACTION",
      kind: "utility",
      target: "self",
      description: "A primeira ação bem-sucedida de cada rodada gera 1 Determinação adicional.",
    },
    skills: [
      {
        key: "golpe-adaptavel",
        name: "Golpe Adaptável",
        level: 1,
        category: "Dano",
        operation: "DAMAGE",
        kind: "damage",
        target: "enemy",
        attribute: "FOR",
        multiplier: 1.15,
        cost: 1,
        cooldown: 1,
        range: 1,
        damageType: "physical",
        description: "Causa 1,15x FOR de dano físico.",
      },
      {
        key: "resolver",
        name: "Resolver",
        level: 25,
        category: "Escudo",
        operation: "SHIELD",
        kind: "shield",
        target: "self",
        attribute: "RES",
        multiplier: 1.2,
        cost: 2,
        cooldown: 3,
        duration: 2,
        description: "Recebe escudo de 1,2x RES por 2 rodadas.",
      },
      {
        key: "improvisacao",
        name: "Improvisação",
        level: 50,
        category: "Buff",
        operation: "BUFF",
        kind: "utility",
        target: "self",
        cost: 3,
        cooldown: 4,
        duration: 2,
        status: "improvisacao",
        description: "Aplica Improvisação por 2 rodadas.",
      },
      {
        key: "impeto-heroico",
        name: "Ímpeto Heroico",
        level: 80,
        category: "Purificação",
        operation: "REMOVE_STATUS",
        kind: "utility",
        target: "self",
        cost: 5,
        cooldown: 7,
        description: "Remove um status negativo comum de si.",
      },
    ],
  },
  {
    name: "Orc",
    slug: "orc",
    difficulty: 2,
    specialization: "Força, intimidação e resistência",
    tags: ["HUMANOIDE", "ORC"],
    hp: 650,
    mana: 50,
    description: "Combatentes robustos que transformam impacto e pressão em força de guerra.",
    bonuses: { FOR: 6, DEF: 3, RES: 4, INI: 1, INT: 0, ARC: 1 },
    resource: { name: "Ímpeto de Guerra", maximum: 5 },
    passive: {
      key: "tenacidade-orc",
      name: "Tenacidade Orc",
      level: 1,
      type: "Passiva",
      category: "Reação",
      operation: "REACTION",
      kind: "utility",
      target: "self",
      description: "Ao receber dano, gera 1 Ímpeto de Guerra adicional, uma vez por ação.",
    },
    skills: [
      {
        key: "esmagar",
        name: "Esmagar",
        level: 1,
        category: "Dano",
        operation: "DAMAGE",
        kind: "damage",
        target: "enemy",
        attribute: "FOR",
        multiplier: 1.35,
        cost: 1,
        cooldown: 1,
        range: 1,
        damageType: "physical",
        description: "Causa 1,35x FOR de dano físico.",
      },
      {
        key: "brado-intimidador",
        name: "Brado Intimidador",
        level: 25,
        category: "Controle",
        operation: "FEAR",
        kind: "utility",
        target: "area",
        cost: 2,
        cooldown: 4,
        range: 2,
        area: 2,
        duration: 1,
        status: "amedrontado",
        description: "Aplica Medo por 1 rodada aos inimigos na área 2.",
      },
      {
        key: "pele-de-guerra",
        name: "Pele de Guerra",
        level: 50,
        category: "Escudo",
        operation: "SHIELD",
        kind: "shield",
        target: "self",
        attribute: "RES",
        multiplier: 1.5,
        cost: 3,
        cooldown: 4,
        duration: 2,
        description: "Recebe escudo de 1,5x RES por 2 rodadas.",
      },
      {
        key: "frenesi-do-chefe",
        name: "Frenesi do Chefe",
        level: 80,
        category: "Buff",
        operation: "APPLY_STATUS",
        kind: "utility",
        target: "self",
        cost: 5,
        cooldown: 8,
        duration: 3,
        status: "frenesi-orc",
        description: "Entra em Frenesi Orc por 3 rodadas.",
      },
    ],
  },
  {
    name: "Alquimista",
    slug: "alquimista",
    difficulty: 5,
    specialization: "Transmutação, preparação e reações em cadeia",
    tags: ["HUMANOIDE", "ALQUIMICO"],
    hp: 470,
    mana: 0,
    description:
      "Linhagens alteradas por gerações de transmutação que combinam reagentes instáveis para adaptar seus corpos durante o combate.",
    bonuses: { FOR: 0, DEF: 2, RES: 4, INI: 3, INT: 4, ARC: 2 },
    resource: { name: "Reagentes", maximum: 6 },
    passive: {
      key: "lei-da-equivalencia",
      name: "Lei da Equivalência",
      level: 1,
      type: "Passiva",
      category: "Reação",
      operation: "REACTION",
      kind: "utility",
      target: "self",
      description:
        "A primeira operação diferente executada em cada rodada gera 1 Reagente; repetir a mesma categoria não gera recurso.",
    },
    skills: [
      {
        key: "frasco-catalitico",
        name: "Frasco Catalítico",
        level: 1,
        category: "Dano",
        operation: "DAMAGE",
        kind: "damage",
        target: "enemy",
        attribute: "INT",
        multiplier: 1.15,
        cost: 1,
        cooldown: 1,
        range: 4,
        damageType: "magic",
        description:
          "Causa 1,15x INT de dano mágico e prepara o alvo para a próxima reação alquímica.",
      },
      {
        key: "transmutacao-defensiva",
        name: "Transmutação Defensiva",
        level: 20,
        category: "Escudo",
        operation: "SHIELD",
        kind: "shield",
        target: "self",
        attribute: "RES",
        multiplier: 1.4,
        cost: 2,
        cooldown: 3,
        duration: 2,
        description: "Converte 2 Reagentes em escudo de 1,4x RES por 2 rodadas.",
      },
      {
        key: "solvente-universal",
        name: "Solvente Universal",
        level: 40,
        category: "Debuff",
        operation: "DEBUFF",
        kind: "utility",
        target: "enemy",
        cost: 3,
        cooldown: 4,
        range: 4,
        duration: 2,
        status: "armadura-dissolvida",
        description: "Reduz as proteções do alvo por 2 rodadas e consome a preparação existente.",
      },
      {
        key: "homunculo-de-combate",
        name: "Homúnculo de Combate",
        level: 60,
        category: "Invocação",
        operation: "APPLY_STATUS",
        kind: "utility",
        target: "self",
        cost: 4,
        cooldown: 6,
        duration: 3,
        status: "homunculo-ativo",
        description:
          "Invoca um homúnculo por 3 rodadas que replica a primeira operação alquímica de cada rodada com 50% do valor.",
      },
      {
        key: "grande-obra",
        name: "Grande Obra",
        level: 80,
        category: "Transformação",
        operation: "APPLY_STATUS",
        kind: "utility",
        target: "self",
        cost: 6,
        cooldown: 9,
        duration: 3,
        status: "pedra-filosofal",
        description:
          "Consome todos os Reagentes e ativa a Pedra Filosofal por 3 rodadas, alternando dano, cura e escudo conforme a última operação usada.",
      },
    ],
  },
  {
    name: "Ninja",
    slug: "ninja",
    difficulty: 5,
    specialization: "Selos, mobilidade e execução",
    tags: ["HUMANOIDE", "SHINOBI"],
    hp: 450,
    mana: 0,
    description:
      "Clãs moldados por técnicas corporais e selos secretos, capazes de encadear posições, marcas e substituições.",
    bonuses: { FOR: 2, DEF: 1, RES: 1, INI: 6, INT: 3, ARC: 2 },
    resource: { name: "Selos", maximum: 6 },
    passive: {
      key: "sequencia-de-selos",
      name: "Sequência de Selos",
      level: 1,
      type: "Passiva",
      category: "Reação",
      operation: "REACTION",
      kind: "utility",
      target: "self",
      description:
        "Mover antes de usar uma habilidade gera 1 Selo; acertar um alvo marcado gera outro, limitado a 2 por rodada.",
    },
    skills: [
      {
        key: "shuriken-marcada",
        name: "Shuriken Marcada",
        level: 1,
        category: "Dano",
        operation: "DAMAGE",
        kind: "damage",
        target: "enemy",
        attribute: "INI",
        multiplier: 1.1,
        cost: 1,
        cooldown: 1,
        range: 5,
        damageType: "physical",
        status: "marca-shinobi",
        description: "Causa 1,1x INI e aplica Marca Shinobi ao alvo.",
      },
      {
        key: "passo-sem-sombra",
        name: "Passo sem Sombra",
        level: 20,
        category: "Mobilidade",
        operation: "TELEPORT",
        kind: "utility",
        target: "self",
        cost: 2,
        cooldown: 2,
        range: 4,
        description: "Teleporta até 4 casas na direção do alvo e ignora unidades intermediárias.",
      },
      {
        key: "substituicao",
        name: "Técnica de Substituição",
        level: 40,
        type: "Reação",
        category: "Reação",
        operation: "REACTION",
        kind: "utility",
        target: "self",
        cost: 3,
        cooldown: 5,
        duration: 1,
        status: "substituicao",
        description:
          "Ao receber dano direto, anula o impacto e recua 3 casas; precisa ser preparada antes do ataque.",
      },
      {
        key: "prisao-de-sombras",
        name: "Prisão de Sombras",
        level: 60,
        category: "Controle",
        operation: "ROOT",
        kind: "utility",
        target: "enemy",
        cost: 4,
        cooldown: 5,
        range: 4,
        duration: 2,
        status: "preso-pela-sombra",
        description:
          "Enraíza por 2 rodadas; contra alvo marcado também o silencia na primeira rodada.",
      },
      {
        key: "execucao-dos-seis-selos",
        name: "Execução dos Seis Selos",
        level: 80,
        category: "Dano",
        operation: "DAMAGE",
        kind: "damage",
        target: "enemy",
        attribute: "INI",
        multiplier: 2.4,
        cost: 6,
        cooldown: 9,
        range: 1,
        damageType: "true",
        description:
          "Consome 6 Selos para causar 2,4x INI de dano verdadeiro a um alvo marcado adjacente.",
      },
    ],
  },
  {
    name: "Necromante",
    slug: "necromante",
    difficulty: 5,
    specialization: "Cadáveres, sacrifício e exército profano",
    tags: ["HUMANOIDE", "NECROTICO"],
    hp: 430,
    mana: 0,
    description:
      "Povos tocados pelo Véu que armazenam ecos dos mortos e os convertem em lacaios, maldições e sobrevivência.",
    bonuses: { FOR: 0, DEF: 2, RES: 4, INI: 1, INT: 5, ARC: 3 },
    resource: { name: "Almas", maximum: 8 },
    passive: {
      key: "colheita-do-veu",
      name: "Colheita do Véu",
      level: 1,
      type: "Passiva",
      category: "Reação",
      operation: "REACTION",
      kind: "utility",
      target: "self",
      description:
        "Gera 1 Alma quando uma unidade invocada expira ou quando qualquer combatente perde 20% do HP máximo em uma única ação.",
    },
    skills: [
      {
        key: "seta-necrotica",
        name: "Seta Necrótica",
        level: 1,
        category: "Dano",
        operation: "DAMAGE",
        kind: "damage",
        target: "enemy",
        attribute: "ARC",
        multiplier: 1.15,
        cost: 1,
        cooldown: 1,
        range: 5,
        damageType: "magic",
        status: "decomposicao",
        description: "Causa 1,15x ARC e aplica Decomposição por 2 rodadas.",
      },
      {
        key: "servo-descarnado",
        name: "Servo Descarnado",
        level: 20,
        category: "Invocação",
        operation: "APPLY_STATUS",
        kind: "utility",
        target: "self",
        cost: 2,
        cooldown: 3,
        duration: 3,
        status: "servo-descarnado",
        description:
          "Invoca um servo por 3 rodadas; ele intercepta o primeiro ataque recebido em cada rodada.",
      },
      {
        key: "pacto-funerario",
        name: "Pacto Funerário",
        level: 40,
        category: "Cura",
        operation: "HEAL",
        kind: "heal",
        target: "self",
        attribute: "RES",
        multiplier: 1.4,
        cost: 3,
        cooldown: 4,
        description:
          "Sacrifica a invocação mais antiga para recuperar 1,4x RES de HP e gerar 1 Alma.",
      },
      {
        key: "muralha-de-ossos",
        name: "Muralha de Ossos",
        level: 60,
        category: "Escudo",
        operation: "SHIELD",
        kind: "shield",
        target: "self",
        attribute: "ARC",
        multiplier: 1.6,
        cost: 4,
        cooldown: 5,
        duration: 2,
        description:
          "Concede escudo de 1,6x ARC; cada invocação ativa aumenta a duração em 1, até 4 rodadas.",
      },
      {
        key: "procissao-do-rei-morto",
        name: "Procissão do Rei Morto",
        level: 80,
        category: "Invocação",
        operation: "APPLY_STATUS",
        kind: "utility",
        target: "self",
        cost: 8,
        cooldown: 10,
        duration: 4,
        status: "procissao-profana",
        description:
          "Consome 8 Almas para convocar a Procissão por 4 rodadas; cada rodada alterna dano em área, medo e escudo.",
      },
    ],
  },
];

const classSlugs = new Set(["alquimista", "ninja", "necromante"]);

export const officialRaces = seeds.filter((seed) => !classSlugs.has(seed.slug)).map(buildRace);
