export type OfficialHistoryChapter = {
  id: string;
  title: string;
  paragraphs: string[];
};

export type OfficialHistoryEra = {
  id: string;
  number: string;
  title: string;
  subtitle: string;
  chapters: OfficialHistoryChapter[];
};

export const officialHistoryEras: OfficialHistoryEra[] = [
  {
    id: "origem",
    number: "I",
    title: "A Origem de Wonderland",
    subtitle: "O nascimento do mundo, da magia e dos primeiros grandes mistérios arcanos.",
    chapters: [
      {
        id: "origem-de-wonderland",
        title: "A Origem de Wonderland",
        paragraphs: [
          "Antes dos reinos, antes das cidades e antes mesmo de existir qualquer forma de vida conhecida, Wonderland era completamente diferente do mundo que conhecemos hoje.",
          "Os registros mais antigos, estudados durante séculos pelos Arcanólogos, descrevem o planeta como uma esfera silenciosa, árida e completamente sem vida. Não existiam florestas, oceanos, montanhas ou criaturas. A superfície era composta por uma única massa continental gigantesca, conhecida atualmente como Pangeia, cercada por um oceano igualmente inerte.",
          "Não havia magia.",
          "Não havia civilização.",
          "Não havia sequer evidências de que o planeta pudesse sustentar vida.",
          "Então aconteceu o impacto.",
        ],
      },
      {
        id: "impacto",
        title: "O Impacto",
        paragraphs: [
          "Há milhares de anos, um corpo celeste de proporções desconhecidas atravessou a atmosfera de Wonderland.",
          "Até hoje, os Arcanólogos não conseguiram determinar sua origem. Alguns registros sugerem que ele teria vindo de regiões extremamente distantes do espaço, enquanto outras teorias defendem que o objeto já vagava pelo sistema planetário havia milhões de anos.",
          "O que se sabe é que ele atingiu Wonderland.",
          "O impacto foi colossal.",
          "A colisão alterou a estrutura do planeta em uma escala nunca registrada novamente. A crosta terrestre se rompeu, montanhas surgiram, oceanos foram deslocados e enormes fissuras atravessaram a antiga Pangeia.",
          "Mas o impacto trouxe algo além de destruição.",
          "Trouxe magia.",
          "O asteroide carregava em seu interior uma substância desconhecida, posteriormente denominada pelos Arcanólogos como Essência Arcana.",
          "No momento da colisão, essa essência foi liberada pelo planeta.",
          "Ela se espalhou pelo solo, pelos oceanos e pela atmosfera, penetrando lentamente na estrutura de Wonderland.",
          "E o mundo começou a mudar.",
        ],
      },
      {
        id: "nascimento-da-vida",
        title: "O nascimento da vida",
        paragraphs: [
          "A Essência Arcana não apenas alterou o ambiente. Ela modificou a própria matéria.",
          "Regiões anteriormente estéreis começaram a desenvolver vegetação. Pequenos organismos surgiram nos oceanos. Rochas passaram a apresentar propriedades desconhecidas. Algumas áreas desenvolveram temperaturas e condições completamente diferentes das regiões vizinhas.",
          "A vida surgiu.",
          "E, conforme a magia se espalhava, Wonderland se tornava cada vez mais diverso.",
          "A antiga Pangeia começou a se fragmentar.",
          "Grandes massas de terra foram separadas por oceanos recém-formados. Algumas regiões foram empurradas para áreas extremamente frias. Outras foram cobertas por florestas densas, desertos ou ambientes completamente diferentes.",
          "Com o passar das eras, essas grandes massas territoriais deram origem aos atuais reinos.",
          "Wonderland não foi planejado.",
          "Ele simplesmente aconteceu.",
          "Foi moldado por uma colisão, pela natureza e pela magia que permaneceu no planeta.",
        ],
      },
      {
        id: "fragmentos",
        title: "Os Fragmentos",
        paragraphs: [
          "Embora grande parte da Essência Arcana tenha sido absorvida pelo próprio planeta, os Arcanólogos acreditam que o asteroide não se desintegrou completamente.",
          "A teoria mais aceita é que partes do corpo celeste podem ter se separado durante o impacto e permanecido espalhadas por Wonderland.",
          "Esses possíveis pedaços ficaram conhecidos como Fragmentos Arcanos.",
          "Sua importância é imensa.",
          "Mesmo um fragmento relativamente pequeno poderia conter uma quantidade extraordinária de energia. Os estudos realizados até hoje indicam que essa energia é capaz de alterar propriedades físicas ao seu redor e interagir diretamente com a magia presente no ambiente.",
          "Entretanto, existe uma diferença fundamental entre o que se acredita e o que foi realmente comprovado.",
          "Apenas um Fragmento Arcano foi encontrado.",
          "Um único.",
          "Ele está em Skypiece.",
        ],
      },
      {
        id: "fragmento-de-skypiece",
        title: "O Fragmento de Skypiece",
        paragraphs: [
          "O fragmento foi descoberto em tempos antigos, quando os habitantes da região ainda não compreendiam completamente sua natureza.",
          "O objeto apresentava uma concentração de Essência Arcana tão intensa que os primeiros pesquisadores sequer conseguiam determinar seus limites.",
          "Com o tempo, percebeu-se que a energia liberada pelo fragmento possuía uma propriedade extraordinária.",
          "Ela era capaz de contrariar a força que mantinha a própria terra presa ao solo.",
          "A descoberta mudou Skypiece para sempre.",
          "Utilizando o fragmento como fonte de energia, os habitantes conseguiram sustentar enormes massas de terra acima das nuvens.",
          "Assim nasceu o reino flutuante de Skypiece.",
          "O fragmento permanece protegido no coração do reino até os dias atuais, mantendo a região suspensa no céu.",
          "Nenhum outro objeto conhecido em Wonderland possui uma capacidade semelhante.",
          "E isso tornou o Fragmento de Skypiece uma das descobertas mais importantes de toda a história do planeta.",
          "Mais importante ainda, ele é a única prova concreta de que os Fragmentos Arcanos realmente existem.",
        ],
      },
      {
        id: "sol-de-lesedi",
        title: "O Sol de Lesedi",
        paragraphs: [
          "Existe, entretanto, uma teoria que há séculos desperta a curiosidade dos Arcanólogos.",
          "Em Lesedi existe uma gigantesca fonte de luz e calor conhecida simplesmente como o Sol de Lesedi.",
          "Durante muito tempo, acreditou-se que aquilo fosse apenas uma peculiaridade natural daquele território. Um fenômeno astronômico ou climático que ainda não havia sido compreendido.",
          "Porém, conforme os estudos sobre o Fragmento de Skypiece avançaram, algumas semelhanças começaram a chamar a atenção dos pesquisadores.",
          "A energia emitida pelo Sol de Lesedi apresenta determinadas características semelhantes às encontradas no Fragmento Arcano de Skypiece.",
          "Sua intensidade também parece incompatível com qualquer fenômeno natural conhecido em Wonderland.",
          "Foi então que surgiu uma hipótese.",
          "Uma hipótese considerada extremamente controversa.",
          "E se o Sol de Lesedi for um Fragmento Arcano?",
          "Não existe confirmação.",
          "Nenhum Arcanólogo conseguiu provar.",
          "E talvez nunca consiga.",
          "O problema é que ninguém consegue chegar perto o suficiente.",
          "As tentativas de aproximação foram abandonadas. Não é possível alcançá-lo por terra e, mesmo utilizando criaturas capazes de voar, a aproximação se torna impossível muito antes de qualquer pesquisador conseguir realizar uma análise adequada.",
          "A energia liberada pela região aumenta drasticamente conforme alguém se aproxima.",
          "Instrumentos falham.",
          "Materiais se deterioram.",
          "E qualquer tentativa de investigação direta precisa ser interrompida.",
          "Por isso, o Sol de Lesedi permanece apenas como uma hipótese nos registros acadêmicos.",
          "Não existe nenhum fragmento encontrado em Lesedi.",
          "O único Fragmento Arcano confirmado continua sendo o de Skypiece.",
          "Ainda assim, a possibilidade de que o Sol seja um fragmento colossal permanece uma das teorias mais fascinantes da Arcanologia.",
          "Caso esteja correta, isso significaria que uma parte gigantesca do asteroide original poderia ter sobrevivido ao impacto.",
          "Mas ninguém sabe.",
          "E, por enquanto, não existe maneira segura de descobrir.",
        ],
      },
      {
        id: "arcanologos",
        title: "Os Arcanólogos",
        paragraphs: [
          "Os responsáveis por estudar esses acontecimentos são conhecidos como Arcanólogos.",
          "A Arcanologia é uma área dedicada ao estudo da magia antiga, do Fragmento de Skypiece e das possíveis evidências relacionadas à colisão do asteroide.",
          "Arcanólogos investigam ruínas, analisam minerais, estudam registros antigos e procuram compreender como a Essência Arcana se espalhou pelo planeta.",
          "Alguns dedicam suas vidas à busca por possíveis fragmentos.",
          "Outros estudam exclusivamente a origem da magia.",
          "Há também pesquisadores especializados em fenômenos considerados anômalos, como o Sol de Lesedi.",
          "Apesar de séculos de pesquisa, uma das maiores perguntas da profissão permanece sem resposta:",
          "quantos fragmentos realmente existem?",
        ],
      },
      {
        id: "mercado-dos-fragmentos",
        title: "O mercado dos fragmentos",
        paragraphs: [
          "O mistério também despertou o interesse de pessoas que não possuem qualquer interesse científico.",
          "Afinal, se o pequeno fragmento encontrado em Skypiece é capaz de sustentar um reino inteiro no céu, quanto poderia valer um fragmento semelhante?",
          "Essa pergunta deu origem a um mercado clandestino.",
          "Ao longo dos séculos, surgiram ladrões, caçadores de relíquias, exploradores ilegais e até mesmo piratas interessados em encontrar os fragmentos antes dos Arcanólogos.",
          "Alguns procuram mapas antigos.",
          "Outros compram informações de exploradores.",
          "Existem histórias sobre expedições inteiras desaparecendo em busca de supostos fragmentos.",
          "Também existem rumores de objetos vendidos secretamente em portos e mercados clandestinos, apresentados como pedaços do asteroide original.",
          "A maioria é falsa.",
          "Pedras comuns.",
          "Minerais raros.",
          "Objetos mágicos sem qualquer relação com o impacto.",
          "Até hoje, nenhum desses supostos fragmentos foi comprovado como verdadeiro.",
          "Mesmo assim, existe quem pague fortunas pela possibilidade.",
          "E enquanto os Arcanólogos procuram evidências, outros procuram apenas uma oportunidade de transformar um pedaço da história de Wonderland em riqueza.",
        ],
      },
      {
        id: "misterio-do-primeiro-impacto",
        title: "O mistério do primeiro impacto",
        paragraphs: [
          "Apesar de todos os avanços, os Arcanólogos ainda não conseguiram responder à maior pergunta de todas.",
          "Por que aquele asteroide carregava magia?",
          "Não existem registros de outro corpo celeste semelhante.",
          "Não se sabe se a Essência Arcana surgiu naturalmente no espaço, se existe em outros lugares ou se o asteroide foi apenas um recipiente para algo ainda mais antigo.",
          "Também não se sabe quantos fragmentos realmente foram criados durante a colisão.",
          "Talvez o Fragmento de Skypiece seja o único que sobreviveu.",
          "Talvez existam outros escondidos em algum lugar de Wonderland.",
          "Talvez estejam enterrados sob montanhas, no fundo dos oceanos ou em regiões que nenhuma criatura jamais alcançou.",
          "E talvez alguns estejam diante dos olhos de todos, confundidos com fenômenos naturais que ninguém ainda compreendeu.",
          "O Sol de Lesedi continua sendo a maior dessas possibilidades.",
          "Mas, até que alguém consiga provar sua verdadeira natureza, ele continuará sendo apenas uma teoria.",
          "Por enquanto, tudo permanece enterrado entre fósseis, ruínas, mapas incompletos, documentos antigos e uma única prova concreta.",
          "Um fragmento.",
          "Um único pedaço do asteroide que mudou tudo.",
          "O que todos concordam, entretanto, é que Wonderland nasceu naquele dia.",
          "Não através de uma criação planejada.",
          "Mas através de uma colisão.",
          "Uma colisão que destruiu um mundo vazio e, ao mesmo tempo, deu origem a um novo.",
          "Um mundo onde a magia não existia até que algo vindo do espaço a trouxe consigo.",
          "Um mundo onde a antiga Pangeia se partiu, a vida surgiu e os primeiros reinos começaram a florescer.",
          "Um mundo que ainda guarda perguntas que ninguém conseguiu responder.",
          "E, talvez, em algum lugar além das terras conhecidas, ainda exista uma parte daquele asteroide esperando para ser encontrada.",
          "O mundo conhecido como Wonderland.",
        ],
      },
    ],
  },
];
