export const worldHistory = [
  { era: "Primórdios", title: "O nascimento de Wonderland", text: "Os primeiros territórios foram moldados por forças divinas, espíritos naturais e cristais de Mana. Skypiece surgiu como o primeiro reino dos Deuses Celestiais, enquanto as terras abaixo se dividiram entre florestas, gelo, savanas e oceanos." },
  { era: "121 t.d.M.", title: "A Era da Moeda", text: "Antes da moeda, os povos negociavam alimentos, serviços e pedras mágicas. Namida transformou o ouro em uma unidade de troca confiável, origem da economia que mais tarde adotaria o Wonderland Gold — WG." },
  { era: "A Guerra dos Dez Invernos", title: "Aokigahara contra Oymyakon", text: "Sem madeira suficiente para enfrentar o frio, Oymyakon avançou sobre a floresta. A guerra durou dez anos. Aokigahara venceu, mas sua mata ficou devastada e só voltou a prosperar depois do sacrifício do grande Druida ao Deus das Florestas." },
  { era: "A Queda Celestial", title: "O desaparecimento de Skypiece", text: "Uma criatura enviada por Amayi corrompeu o cristal azul que mantinha as cidades no céu. Aengels e Daemons entraram em conflito sobre o sacrifício necessário para salvá-lo. O reino colapsou, desapareceu e retornou muito tempo depois, quando um mês de chuvas e céus escuros terminou subitamente." },
  { era: "303 d.M.", title: "O Reino Perdido de Namida", text: "Durante a guerra, Namida protegeu povos marinhos e terrestres sob sua redoma. Séculos depois, uma guilda profanou o reino. Uisge reagiu destruindo a própria cidade, que passou a ser lembrada como o Reino Perdido de Namida." },
  { era: "Era Atual", title: "A nova geração de aventureiros", text: "Com os cinco reinos novamente ligados por comércio, guildas e Arena, novos personagens atravessam Wonderland. Seus Ranks registram não apenas poder, mas o impacto que deixam na história do mundo." },
] as const;

export const realmLore = [
  { key: "aokigahara", name: "Aokigahara", title: "Reino da Floresta Densa", climate: "Temperado e úmido", people: "Povos da floresta e druidas", color: "#36b874", position: [24,48], summary: "Uma floresta viva, protegida pelo sacrifício de um Druida e cobiçada pela resistência incomum de sua madeira.", history: "Aokigahara cresceu ao redor de uma mata criada para impedir o desmatamento. Depois de vencer a guerra de dez anos contra Oymyakon, o reino quase não conseguiu restaurar o que havia perdido. O sacrifício de seu grande Druida ao Deus das Florestas devolveu força às raízes e selou a proteção do território.", curiosities: ["As casas tradicionais são construídas em madeira local.","Algumas trilhas mudam de lugar durante a noite.","A retirada de madeira exige autorização dos guardiões da floresta."] },
  { key: "oymyakon", name: "Oymyakon", title: "Reino do Gelo", climate: "Frio extremo", people: "Povos da tundra", color: "#84d8ff", position: [35,19], summary: "Um reino isolado por uma tempestade perpétua, cercado por geleiras, tundras e ventos capazes de cortar a pele.", history: "A escassez de recursos para aquecer e reconstruir suas casas levou Oymyakon a atacar Aokigahara. A derrota encerrou a guerra, mas o reino se fechou ainda mais. A tempestade permanente tornou suas fronteiras quase impenetráveis e interrompeu a comunicação com o restante de Wonderland.", curiosities: ["As construções usam madeira reforçada e isolamento de peles.","Entrar ou sair durante a grande tempestade é considerado impossível.","As auroras são usadas para marcar as estações."] },
  { key: "lesedi", name: "Lesedi", title: "Reino de Areia", climate: "Tropical árido", people: "Povos das savanas e dunas", color: "#e5b85c", position: [69,61], summary: "Savanas quentes, dunas, planaltos e montanhas rochosas formam o maior corredor terrestre de comércio.", history: "Lesedi prosperou dominando rotas que atravessam regiões onde água e sombra valem tanto quanto ouro. Suas cidades utilizam pedra, argila, fibras e outros materiais locais para resistir ao calor. Mercadores de diferentes reinos transformaram seus mercados em pontos centrais da economia de WG.", curiosities: ["As caravanas viajam principalmente ao amanhecer e ao entardecer.","Reservatórios subterrâneos abastecem as maiores cidades.","Planaltos funcionam como fortalezas naturais."] },
  { key: "namida", name: "Namida", title: "Reino Submerso", climate: "Oceânico protegido", people: "Raças marinhas e terrestres", color: "#3aaee8", position: [45,77], summary: "Uma cidade sob o oceano, protegida pela redoma de Uisge e Sihir — hoje lembrada como um reino perdido.", history: "Namida acolheu refugiados durante a guerra entre Aokigahara e Oymyakon e foi essencial para a origem da moeda. Em 303 d.M., uma guilda profanou o reino. A fúria de Uisge destruiu a cidade e transformou sua redoma em uma ruína cercada por mistérios.", curiosities: ["Foi um dos primeiros centros de cunhagem de ouro.","Sua redoma permitia a convivência de povos terrestres e aquáticos.","Exploradores ainda procuram entradas para as ruínas."] },
  { key: "skypiece", name: "Skypiece", title: "Reino Celestial", climate: "Céus frios e luminosos", people: "Aengels e Daemons", color: "#bda6ff", position: [71,25], summary: "Cidades flutuantes sustentadas por um cristal azul de Mana e marcadas pelo conflito que derrubou o primeiro reino.", history: "Criado pelos Deuses Celestiais, Skypiece dependia de um cristal de Mana azul. Quando uma criatura de Amayi o corrompeu, os Aengels defenderam um sacrifício para restaurá-lo e os Daemons se opuseram. O reino caiu e desapareceu, retornando somente depois de um longo período de chuvas e escuridão.", curiosities: ["Fragmentos do cristal ainda alimentam mecanismos antigos.","As cidades não permanecem sempre sobre o mesmo ponto.","Seu retorno foi anunciado pelo clarear repentino dos céus."] },
] as const;
