import Link from "next/link";
import { PlayerNav } from "@/components/player-nav";
import { requireMissionManager } from "@/lib/auth/account";
import { kingdomMissionNames,parseManagedMissions } from "@/lib/game/missions";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { resolveMissionAction } from "./actions";

export const metadata={title:"Gerenciar missões"};export const dynamic="force-dynamic";
export default async function MissionManagementPage({searchParams}:{searchParams:Promise<{status?:string;mensagem?:string}>}){
  await requireMissionManager();const query=await searchParams;const client=await createServerSupabaseClient();const result=client?await client.rpc("v2_get_managed_missions"):{data:null,error:null};const assignments=parseManagedMissions(result.data);
  return <main className="mission-page"><PlayerNav/><div className="page-container mission-management"><header><div><span className="eyebrow">Livro de controle da Guilda</span><h1>Contratos em campo</h1><p>Avalie o retorno dos aventureiros. A conclusão entrega recompensas; a falha aplica bloqueio de 24 horas.</p></div><Link className="button button--glass" href="/missoes">← Voltar ao mural</Link></header>{query.status?<div className={`mission-notice ${query.status==="completed"?"is-success":"is-warning"}`}>{query.status==="completed"?"Missão concluída e recompensas entregues.":query.status==="failed"?"Missão marcada como falha. O personagem ficará bloqueado por 24 horas.":query.mensagem??"Ação não concluída."}</div>:null}<section className="mission-ledger"><header><span>Personagem</span><span>Rank / Nível</span><span>Missão</span><span>Recompensa</span><span>Decisão</span></header>{assignments.map(item=><article key={item.assignmentId}><div><strong>{item.characterName}</strong><small>{kingdomMissionNames[item.kingdom]??item.kingdom}</small></div><div><b>Rank {item.characterRank}</b><small>Nível {item.characterLevel}</small></div><div><strong>{item.missionName}</strong><small>Missão {item.missionRank}{item.isRankTrial?" · Prova de ascensão":""}</small></div><div><b>{item.rewardXp.toLocaleString("pt-BR")} XP</b><small>{item.rewardGold.toLocaleString("pt-BR")} WG</small></div><form action={resolveMissionAction}><input name="assignmentId" type="hidden" value={item.assignmentId}/><button className="is-complete" name="result" value="completed">Concluída</button><button className="is-failed" name="result" value="failed">Não concluída</button></form></article>)}{!assignments.length?<div className="mission-ledger__empty"><span>✓</span><h2>Nenhum contrato aguarda avaliação</h2><p>Quando um jogador aceitar uma missão, ela aparecerá neste livro.</p></div>:null}</section></div></main>;
}
