"use strict";

(async function(){
  const account=window.WONDERLAND_ACCOUNT;
  const client=window.WONDERLAND_SUPABASE;
  const greeting=document.getElementById("adminGreeting");
  const logout=document.getElementById("adminLogout");
  const moduleTitle=document.getElementById("adminModuleTitle");
  const moduleContent=document.getElementById("adminModuleContent");

  if(!account||!client){window.location.replace("conta.html");return}

  let user;
  try{user=await account.current()}catch(error){console.error(error)}
  if(!user){window.location.replace("conta.html");return}
  if(!account.isAdmin(user)){window.location.replace("personagens.html");return}

  greeting.textContent=`Bem-vindo, ${user.name}. Gerencie o conteúdo e o balanceamento do Wonderland.`;

  const classSource=window.WONDERLAND_CLASSES||{};
  const raceSource=Array.isArray(window.WONDERLAND_RACES)?window.WONDERLAND_RACES:[];
  const progression=window.WONDERLAND_PROGRESSION;
  const rankOptions=["E","D","C","B","A","S","EX"];

  const modules={
    races:{title:"Raças",table:"races",id:"id",fields:["id","name","description","tagline","archetype","difficulty","base_hp","base_mana","icon","artwork_url","is_active","sort_order"]},
    classes:{title:"Classes",table:"classes",id:"id",fields:["id","name","description","role","specialization","difficulty","primary_attribute","secondary_attribute","strengths","weaknesses","resource_name","resource_description","icon","artwork_url","is_active","sort_order"]},
    skills:{title:"Habilidades",table:"skills",id:"id",fields:["id","name","description","category","source_type","class_id","class_path_id","race_id","unlock_level","mana_cost","cooldown_turns","range_cells","area_cells","duration_turns","uses_per_combat","is_passive","is_ultimate","is_active","sort_order"]},
    items:{title:"Itens",table:"items",id:"id",fields:["id","name","description","item_type","rarity","max_stack","required_level","base_value","icon_url","artwork_url","is_tradeable","is_active","sort_order"]},
    users:{title:"Usuários",table:"profiles",id:"id",fields:["id","username","display_name","role","is_banned","avatar_url"]},
    settings:{title:"Balanceamento",table:"game_settings",id:"key",fields:["key","category","label","description","value","default_value","value_type","is_public","is_editable"]}
  };

  const labels={id:"ID",key:"Chave",name:"Nome",description:"Descrição",tagline:"Frase",archetype:"Arquétipo",difficulty:"Dificuldade",base_hp:"HP Base",base_mana:"Mana Base",icon:"Ícone",artwork_url:"Imagem",is_active:"Ativo",sort_order:"Ordem",role:"Função",specialization:"Especialização",primary_attribute:"Atributo principal",secondary_attribute:"Atributo secundário",strengths:"Pontos fortes",weaknesses:"Pontos fracos",resource_name:"Recurso",resource_description:"Descrição do recurso",category:"Categoria",source_type:"Origem",class_id:"Classe",class_path_id:"Caminho",race_id:"Raça",unlock_level:"Nível",mana_cost:"Mana",cooldown_turns:"Recarga",range_cells:"Alcance",area_cells:"Área",duration_turns:"Duração",uses_per_combat:"Usos por combate",is_passive:"Passiva",is_ultimate:"Ultimate",item_type:"Tipo",rarity:"Raridade",max_stack:"Pilha máxima",required_level:"Nível mínimo",base_value:"Valor",icon_url:"Ícone",is_tradeable:"Negociável",username:"Usuário",display_name:"Nome exibido",is_banned:"Banido",avatar_url:"Avatar",value:"Valor",default_value:"Valor padrão",value_type:"Tipo",is_public:"Público",is_editable:"Editável"};

  const booleans=new Set(["is_active","is_passive","is_ultimate","is_tradeable","is_banned","is_public","is_editable"]);
  const numbers=new Set(["difficulty","base_hp","base_mana","sort_order","unlock_level","mana_cost","cooldown_turns","range_cells","area_cells","duration_turns","uses_per_combat","max_stack","required_level","base_value"]);
  const longText=new Set(["description","tagline","strengths","weaknesses","resource_description"]);
  const readonly=new Set(["id","key"]);

  const esc=value=>String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
  const levelNumber=value=>Number(String(value??1).replace(/\D+/g,""))||1;
  const starsToNumber=value=>Math.max(1,Math.min(5,(String(value||"").match(/★/g)||[]).length||1));
  const classAttrs=cls=>{const source=String(cls?.estilo?.atributos||"").toUpperCase();const attrs=["FOR","DEF","RES","INI","INT","ARC"].filter(attr=>source.includes(attr));return{primary:attrs[0]||null,secondary:attrs[1]||null}};

  const localClasses=()=>Object.values(classSource).map((cls,index)=>{const attrs=classAttrs(cls);return{id:cls.id,name:cls.nome,description:cls.descricao||"",role:cls.cargo||"",specialization:cls.especializacao?.titulo||cls.cargo||"",difficulty:starsToNumber(cls.dificuldade),primary_attribute:attrs.primary,secondary_attribute:attrs.secondary,strengths:cls.estilo?.fortes||"",weaknesses:cls.estilo?.fracos||"",resource_name:"Mana",resource_description:cls.recurso?.descricao||"",icon:cls.icone||"",artwork_url:cls.imagem||"",is_active:true,sort_order:index,_source:"local"}});
  const localRaces=()=>raceSource.map((race,index)=>({id:race.id,name:race.name,description:race.description||race.descricao||"",tagline:race.tagline||"",archetype:race.archetype||"",difficulty:starsToNumber(race.difficulty||race.dificuldade),base_hp:Number(race.stats?.hp||race.hp||0),base_mana:Number(race.stats?.mana||race.mana||0),icon:race.icon||"",artwork_url:race.artwork||race.image||"",is_active:true,sort_order:index,_source:"local"}));
  const localSkills=()=>[];

  async function refreshStats(){const statMap={statUsers:"profiles",statCharacters:"characters",statRaces:"races",statClasses:"classes",statSkills:"skills",statItems:"items"};await Promise.all(Object.entries(statMap).map(async([elementId,table])=>{const element=document.getElementById(elementId);try{const {count,error}=await client.from(table).select("*",{count:"exact",head:true});if(error)throw error;let value=count??0;if(value===0&&table==="races")value=localRaces().length;if(value===0&&table==="classes")value=localClasses().length;element.textContent=String(value)}catch(error){console.error(error);element.textContent="—"}}))}

  function inputFor(field,value){const label=esc(labels[field]||field);if(booleans.has(field))return `<label class="admin-field admin-field-check"><span>${label}</span><input type="checkbox" name="${field}" ${value?"checked":""}></label>`;if(longText.has(field))return `<label class="admin-field admin-field-wide"><span>${label}</span><textarea name="${field}" rows="4">${esc(value??"")}</textarea></label>`;const type=numbers.has(field)?"number":"text";return `<label class="admin-field"><span>${label}</span><input type="${type}" name="${field}" value="${esc(value??"")}" ${readonly.has(field)?"readonly":""}></label>`}
  function normalizeValue(field,input){if(booleans.has(field))return input.checked;if(numbers.has(field))return input.value===""?null:Number(input.value);if(field==="value"||field==="default_value"){const raw=input.value.trim();if(raw==="")return null;try{return JSON.parse(raw)}catch{return raw}}return input.value===""?null:input.value}
  function formatNumber(value){return progression?.formatNumber?progression.formatNumber(value):new Intl.NumberFormat("pt-BR").format(Number(value)||0)}

  async function loadRows(moduleKey,module){const {data,error}=await client.from(module.table).select(module.fields.join(",")).order(module.id,{ascending:true}).limit(500);if(error)throw error;if(data?.length)return data;if(moduleKey==="classes")return localClasses();if(moduleKey==="races")return localRaces();if(moduleKey==="skills")return localSkills();return[]}
  async function loadRelated(moduleKey,row){if(moduleKey==="users"){const {data,error}=await client.from("characters").select("id,name,race_id,class_id,guild_rank,level,experience,wg,created_at,image_url").eq("user_id",row.id).order("created_at",{ascending:true});if(error)throw error;return data||[]}return[]}

  function renderRecordList(module,rows){if(!rows.length)return '<div class="admin-empty">Nenhum registro encontrado neste módulo.</div>';return `<aside class="admin-record-list">${rows.map((row,index)=>`<button type="button" class="admin-record-button" data-record-index="${index}"><small>${esc(row[module.id])}</small><strong>${esc(row.name||row.label||row.username||row.display_name||row[module.id])}</strong><span>${esc(row.role||row.category||row.source_type||row.item_type||"")}</span></button>`).join("")}</aside>`}

  function characterEditorHtml(character){const currentRank=rankOptions.includes(String(character.guild_rank||"E").toUpperCase())?String(character.guild_rank||"E").toUpperCase():"E";return `<section class="admin-character-editor"><header class="admin-character-editor-header"><div><span>Personagem selecionado</span><h3>${esc(character.name)}</h3><p>Edite identidade, progressão, economia, raça, classe e Rank.</p></div><span class="admin-character-level">Nível ${esc(character.level||1)}</span></header><form class="admin-character-form"><div class="admin-character-grid"><label class="admin-field"><span>Nome</span><input name="name" value="${esc(character.name||"")}"></label><label class="admin-field"><span>Nível</span><input name="level" type="number" min="1" max="100" value="${esc(character.level||1)}"></label><label class="admin-field"><span>Experiência</span><input name="experience" type="number" min="0" value="${esc(character.experience||0)}"></label><label class="admin-field"><span>Wonderland Gold (WG)</span><input name="wg" type="number" min="0" step="1" value="${esc(character.wg||0)}"></label><label class="admin-field"><span>Rank</span><select name="guild_rank">${rankOptions.map(rank=>`<option value="${rank}" ${rank===currentRank?"selected":""}>${rank}</option>`).join("")}</select></label><label class="admin-field"><span>Raça</span><select name="race_id">${raceSource.map(race=>`<option value="${esc(race.id)}" ${race.id===character.race_id?"selected":""}>${esc(race.name)}</option>`).join("")}</select></label><label class="admin-field"><span>Classe</span><select name="class_id">${Object.values(classSource).map(cls=>`<option value="${esc(cls.id)}" ${cls.id===character.class_id?"selected":""}>${esc(cls.nome)}</option>`).join("")}</select></label><label class="admin-field admin-field-wide"><span>Imagem</span><input name="image_url" type="url" value="${esc(character.image_url||"")}" placeholder="https://..."></label></div><div class="admin-character-preview"><div><span>Resumo</span><strong>${esc(character.name)}</strong><small>${esc(character.race_id)} • ${esc(character.class_id)} • ${esc(character.wg||0)} WG</small></div><div class="admin-character-rank-preview">${esc(currentRank)}</div></div><div class="admin-form-actions"><button type="submit" class="wl-button wl-button-green">Salvar personagem</button></div><p class="admin-form-message"></p></form></section>`}

  function renderEditor(module,row,index,related,moduleKey){const relatedTitle=moduleKey==="users"?"Personagens da conta":"";const relatedHtml=relatedTitle?`<section class="admin-related admin-user-characters"><header><span>Conteúdo vinculado</span><h3>${relatedTitle}</h3></header>${related.length?related.map((item,relatedIndex)=>`<article class="admin-related-card admin-character-card"><div><small>Nível ${esc(item.level||1)}</small><h4>${esc(item.name)}</h4><p>${esc(item.race_id||"Raça")} • ${esc(item.class_id||"Classe")} • Rank ${esc(item.guild_rank||"E")}</p></div><div class="admin-related-meta"><span>XP ${esc(item.experience||0)}</span><span>${esc(item.wg||0)} WG</span></div><button type="button" class="wl-button wl-button-gold" data-character-edit-index="${relatedIndex}">Editar personagem</button></article>`).join(""):"<div class='admin-empty'>Nenhum personagem vinculado.</div>"}<div id="adminCharacterEditorHost"></div></section>`:"";return `<section class="admin-editor admin-editor-detail"><header><div><span>Editor</span><h3>${esc(row.name||row.display_name||row.username||row[module.id])}</h3></div></header><form id="adminEditForm" class="admin-edit-form">${module.fields.map(field=>inputFor(field,row?.[field])).join("")}<div class="admin-form-actions"><button type="submit" class="wl-button wl-button-green">Salvar alterações</button></div><p id="adminFormMessage" class="admin-form-message"></p></form>${relatedHtml}</section>`}

  function renderXpModule(){
    if(!progression){moduleContent.innerHTML='<div class="admin-error">O sistema de progressão não foi carregado.</div>';return}
    const missionRows=rankOptions.map(rank=>{const reward=progression.MISSION_REWARDS?.[rank];return reward?`<tr><td><strong>Rank ${rank}</strong></td><td>${formatNumber(reward.xp)} XP</td><td>${formatNumber(reward.wg)} WG</td></tr>`:""}).join("");
    const dungeonRows=["E","D","C","B","A","S"].map(rank=>{const reward=progression.DUNGEON_REWARDS?.[rank];return reward?`<tr><td><strong>Rank ${rank}</strong></td><td>${esc(reward.level)}</td><td>${formatNumber(reward.xp)} XP</td><td>${formatNumber(reward.wg)} WG</td></tr>`:""}).join("");
    const xpRows=Object.entries(progression.XP_TOTAL_BY_LEVEL||{}).map(([level,xp])=>`<tr><td>Nível ${esc(level)}</td><td>${formatNumber(xp)} XP total</td></tr>`).join("");
    moduleContent.innerHTML=`<section class="admin-xp-overview"><div class="admin-xp-intro"><span>Economia oficial</span><h3>XP e Wonderland Gold</h3><p>WG é a moeda oficial do Wonderland. Estes valores são usados como referência para missões, dungeons e progressão de nível.</p></div><div class="admin-xp-grid"><article class="admin-xp-card"><header><span>Missões</span><h3>Recompensas por Rank</h3></header><div class="admin-table-wrap"><table class="admin-reward-table"><thead><tr><th>Rank</th><th>Experiência</th><th>Wonderland Gold</th></tr></thead><tbody>${missionRows}</tbody></table></div></article><article class="admin-xp-card"><header><span>Dungeons</span><h3>Recompensas e nível recomendado</h3></header><div class="admin-table-wrap"><table class="admin-reward-table"><thead><tr><th>Rank</th><th>Nível</th><th>Experiência</th><th>Wonderland Gold</th></tr></thead><tbody>${dungeonRows}</tbody></table></div></article></div><article class="admin-xp-card admin-xp-levels"><header><span>Progressão</span><h3>Tabela oficial de XP total</h3></header><div class="admin-table-wrap admin-xp-level-table"><table class="admin-reward-table"><thead><tr><th>Nível</th><th>XP total necessário</th></tr></thead><tbody>${xpRows}</tbody></table></div></article></section>`;
  }

  async function openModule(key){
    document.querySelectorAll("[data-admin-module]").forEach(button=>button.classList.toggle("active",button.dataset.adminModule===key));
    if(key==="xp"){moduleTitle.textContent="XP & WG";renderXpModule();return}
    const module=modules[key];if(!module)return;
    moduleTitle.textContent=module.title;moduleContent.innerHTML='<div class="admin-loading">Consultando o Supabase...</div>';
    try{const rows=await loadRows(key,module);moduleContent.innerHTML=`<div class="admin-browser">${renderRecordList(module,rows)}<div id="adminDetailPane" class="admin-detail-pane"><div class="admin-empty">Selecione um registro à esquerda.</div></div></div>`;const detailPane=document.getElementById("adminDetailPane");moduleContent.querySelectorAll("[data-record-index]").forEach(button=>button.addEventListener("click",async()=>{moduleContent.querySelectorAll("[data-record-index]").forEach(item=>item.classList.toggle("active",item===button));const index=Number(button.dataset.recordIndex),row=rows[index];detailPane.innerHTML='<div class="admin-loading">Carregando detalhes...</div>';try{const related=await loadRelated(key,row);detailPane.innerHTML=renderEditor(module,row,index,related,key);bindEditor(module,rows,index,detailPane,key,related)}catch(error){detailPane.innerHTML=`<div class="admin-error">${esc(error.message||"Falha ao carregar detalhes.")}</div>`}}));if(rows.length)moduleContent.querySelector("[data-record-index='0']")?.click()}catch(error){console.error(error);moduleContent.innerHTML=`<div class="admin-error">${esc(error.message||"Não foi possível carregar este módulo.")}</div>`}}
  }

  function bindEditor(module,rows,index,host,moduleKey,related){const form=host.querySelector("#adminEditForm");form?.addEventListener("submit",async event=>{event.preventDefault();const message=form.querySelector("#adminFormMessage");const row=rows[index],payload={};module.fields.forEach(field=>{if(readonly.has(field))return;const input=form.elements.namedItem(field);if(input)payload[field]=normalizeValue(field,input)});message.textContent="Salvando...";try{const query=row._source==="local"?client.from(module.table).upsert({...payload,[module.id]:row[module.id]}):client.from(module.table).update(payload).eq(module.id,row[module.id]);const {error}=await query;if(error)throw error;delete row._source;Object.assign(row,payload);message.textContent="Alterações salvas com sucesso no Supabase.";await refreshStats()}catch(error){message.textContent=error.message||"Não foi possível salvar."}});

    if(moduleKey==="users"){
      const hostEditor=host.querySelector("#adminCharacterEditorHost");
      host.querySelectorAll("[data-character-edit-index]").forEach(button=>button.addEventListener("click",()=>{
        const character=related[Number(button.dataset.characterEditIndex)];hostEditor.innerHTML=characterEditorHtml(character);
        const characterForm=hostEditor.querySelector(".admin-character-form");const rankSelect=characterForm.elements.guild_rank;const rankPreview=hostEditor.querySelector(".admin-character-rank-preview");rankPreview.textContent=rankSelect.value;rankSelect.addEventListener("change",()=>rankPreview.textContent=rankSelect.value);
        characterForm.addEventListener("submit",async event=>{event.preventDefault();const message=characterForm.querySelector(".admin-form-message");const submit=characterForm.querySelector('button[type="submit"]');message.textContent="Salvando personagem...";submit.disabled=true;const payload={name:characterForm.elements.name.value.trim(),level:Number(characterForm.elements.level.value||1),experience:Number(characterForm.elements.experience.value||0),wg:Math.max(0,Math.trunc(Number(characterForm.elements.wg.value||0))),guild_rank:rankSelect.value,race_id:characterForm.elements.race_id.value,class_id:characterForm.elements.class_id.value,image_url:characterForm.elements.image_url.value.trim()||null};try{const {data,error}=await client.from("characters").update(payload).eq("id",character.id).select("id,name,race_id,class_id,guild_rank,level,experience,wg,image_url").single();if(error)throw error;Object.assign(character,data);message.textContent=`Personagem salvo com sucesso. Saldo atual: ${data.wg} WG.`;rankPreview.textContent=data.guild_rank;const cardButton=host.querySelector(`[data-character-edit-index="${related.indexOf(character)}"]`);const card=cardButton?.closest(".admin-character-card");if(card){card.querySelector("small").textContent=`Nível ${data.level}`;card.querySelector("h4").textContent=data.name;card.querySelector("p").textContent=`${data.race_id} • ${data.class_id} • Rank ${data.guild_rank}`;const meta=card.querySelectorAll(".admin-related-meta span");if(meta[0])meta[0].textContent=`XP ${data.experience}`;if(meta[1])meta[1].textContent=`${data.wg} WG`}}catch(error){console.error(error);message.textContent=error.message||"Não foi possível salvar o personagem."}finally{submit.disabled=false}});
      }));
    }
  }

  document.querySelectorAll("[data-admin-module]").forEach(button=>button.addEventListener("click",()=>openModule(button.dataset.adminModule)));
  logout?.addEventListener("click",async()=>{await account.logout();window.location.assign("conta.html")});
  await refreshStats();
})();
