"use strict";

(async function(){
  const account=window.WONDERLAND_ACCOUNT;
  const defense=window.WONDERLAND_DEFENSE_SYSTEM;
  const manaSystem=window.WONDERLAND_MANA_SYSTEM;
  const attrs=["FOR","DEF","RES","INI","INT","ARC"];
  const GRID_W=100,GRID_H=100;
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
  const els={setup:$("arenaSetup"),battle:$("arenaBattle"),character:$("arenaCharacter"),monster:$("arenaMonster"),start:$("arenaStart"),message:$("arenaMessage"),grid:$("arenaGrid"),skillCards:$("arenaSkillCards"),log:$("arenaCombatLog"),timer:$("arenaTimer"),turnLabel:$("arenaTurnLabel"),movementInfo:$("arenaMovementInfo"),defend:$("arenaDefend"),endTurn:$("arenaEndTurn"),reset:$("arenaReset")};
  const state={characters:[],sheet:null,character:null,race:null,cls:null,attrs:null,skills:[],dummy:null,started:false,turn:"player",round:1,timer:60,timerId:null,selectedAction:null,player:null,enemy:null,moveLeft:0,actions:{basic:false,race:false,class:false},defendCooldown:0,cooldowns:{},log:[],actedThisTurn:false};
  if(!account){els.message.textContent="Sistema de contas indisponível.";return}

  function baseAttributes(row){return Object.fromEntries(attrs.map(attr=>{const k=attr.toLowerCase();return[attr,Number(row?.[`base_${k}`]||20)+Number(row?.[`allocated_${k}`]||0)+Number(row?.[`racial_${k}`]||0)]}))}
  function equipmentBonus(equipment){const out=Object.fromEntries(attrs.map(a=>[a,0]));const seen=new Set();(equipment||[]).forEach(item=>{if(item?.metadata?.linked_two_hand)return;const key=`${item.item_key}:${item.slot}`;if(seen.has(key))return;seen.add(key);Object.entries(item?.metadata?.stats||{}).forEach(([a,v])=>{a=String(a).toUpperCase();if(attrs.includes(a))out[a]+=Number(v)||0})});return out}
  function textValue(value){if(value==null)return"";if(typeof value==="string"||typeof value==="number")return String(value).replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();if(Array.isArray(value))return value.map(textValue).filter(Boolean).join(" • ");if(typeof value==="object")return textValue(value.description||value.descricao||value.text||value.nome||value.name||"");return""}
  function parseLevel(value){const m=String(value||"").match(/(\d+)/);return Number(m?.[1]||1)}
  function parseScale(text){const m=String(text||"").match(/(\d+(?:[.,]\d+)?)%\s+(?:do|de|da)\s+(?:seu\s+)?(FOR|DEF|RES|INI|INT|ARC)/i);return m?{percent:Number(m[1].replace(",",".")),attr:m[2].toUpperCase()}:null}
  function parseMana(text){const m=String(text||"").match(/(\d+)\s*Mana/i);return Number(m?.[1]||0)}
  function parseCooldown(text){const m=String(text||"").match(/(?:recarga|cooldown)\D*(\d+)/i);return Math.max(0,Number(m?.[1]||0))}
  function officialSkills(cls,level,pathId){const list=[];(cls?.progressao||[]).forEach(s=>{const unlock=parseLevel(s.nivel);if(unlock<=level)list.push({...s,source:"class",unlock})});if(level>=50&&pathId){const selected=(cls?.caminhos||[]).find(p=>String(p.id||p.nome||"").toLowerCase()===String(pathId).toLowerCase());(selected?.habilidades||[]).forEach((s,i)=>{const unlock=[60,70,80,90,100][i]||100;if(unlock<=level)list.push({...s,source:"class",unlock})})}return list}
  function roleWeights(cls){const t=`${cls?.nome||""} ${cls?.especializacao||""} ${cls?.descricao||""}`.toLowerCase();if(/mago|feiticeiro|bruxo|necromante|alquimista/.test(t))return{INT:1.45,ARC:1.25,INI:1.08,RES:.95,DEF:.8,FOR:.65};if(/bardo|druida|suporte|cura|invoca/.test(t))return{ARC:1.45,INT:1.2,RES:1.12,INI:1.05,DEF:.9,FOR:.75};if(/assassino|ninja|arqueiro/.test(t))return{INI:1.45,FOR:1.25,DEF:.95,RES:.9,INT:.8,ARC:.75};if(/guerreiro|bárbaro|barbaro|espadachim|tanque/.test(t))return{FOR:1.35,DEF:1.28,RES:1.18,INI:.95,INT:.7,ARC:.75};return Object.fromEntries(attrs.map(a=>[a,1]))}
  function buildDummy(playerAttrs,cls,race){const w=roleWeights(cls);const total=attrs.reduce((s,a)=>s+Number(playerAttrs[a]||0),0);const sw=attrs.reduce((s,a)=>s+w[a],0);const distributed={};attrs.forEach(a=>distributed[a]=Math.max(1,Math.round(total*w[a]/sw)));const hpBase=Number(race?.stats?.hp||500);const hpMax=hpBase+Math.floor(distributed.RES/5)*10;const manaMax=manaSystem?.breakdown({intValue:distributed.INT,race})?.total||100+Math.floor(distributed.INT/5)*10;return{name:"Boneco de Teste",attrs:distributed,hpMax,manaMax,race:race?.name||"Raça adaptativa",className:cls?.nome||"Classe adaptativa"}}
  function movementFromIni(ini){return Math.max(1,Math.min(12,Math.floor(Number(ini||0)/25)))}
  function manhattan(a,b){return Math.abs(a.x-b.x)+Math.abs(a.y-b.y)}
  function log(text){state.log.unshift(text);state.log=state.log.slice(0,40);els.log.innerHTML=state.log.map(line=>`<p>${line}</p>`).join("")}
  function hpMaxFor(attrsObj,race){return Number(race?.stats?.hp||500)+Math.floor(Number(attrsObj.RES||0)/5)*10}
  function manaMaxFor(attrsObj,race){return manaSystem?.breakdown({intValue:Number(attrsObj.INT||0),race})?.total||100+Math.floor(Number(attrsObj.INT||0)/5)*10}
  function basicWeaponInfo(){const names=(state.sheet?.equipment||[]).map(e=>String(e.metadata?.name||"")).join(" ");if(/cajado|orbe|grimório|grimorio|tomo|cetro|foco arcano|varinha/i.test(names))return{type:"magical",attr:"INT",range:7,label:"Ataque mágico à distância"};if(/lança|lanca|alabarda/i.test(names))return{type:"physical",attr:"FOR",range:3,label:"Ataque de alcance com lança"};return{type:"physical",attr:"FOR",range:1,label:"Ataque físico corpo a corpo"}}
  function renderSetup(){if(!state.sheet)return;$("setupPlayerImage").src=state.character.image_url||state.race?.artwork||state.race?.image||"assets/images/logo.png";$("setupPlayerName").textContent=state.character.name;$("setupPlayerSummary").textContent=`${state.race?.name||state.character.race_id} • ${state.cls?.nome||state.character.class_id}`;$("setupPlayerStats").innerHTML=attrs.map(a=>`<span>${a}<strong>${esc(state.attrs[a])}</strong></span>`).join("");$("setupEnemySummary").textContent=`${state.dummy.race} • ${state.dummy.className}`;$("setupEnemyStats").innerHTML=attrs.map(a=>`<span>${a}<strong>${esc(state.dummy.attrs[a])}</strong></span>`).join("")}
  function actionData(){const basic=basicWeaponInfo();const out=[{id:"basic",name:"Ataque básico",source:"basic",cost:0,range:basic.range,scale:100,attr:basic.attr,type:basic.type,cooldown:0,description:`100% de ${basic.attr}. ${basic.label}.`}];state.skills.slice(0,12).forEach((s,i)=>{const desc=textValue(s.descricao);const parsed=parseScale(desc);out.push({id:`skill-${i}`,name:textValue(s.nome)||`Habilidade ${i+1}`,source:s.source||"class",cost:parseMana(desc),range:/distância|distancia|alcance|projétil|projetil|área|area/i.test(desc)?Math.max(3,Number((desc.match(/(\d+)\s*(?:casa|alcance)/i)||[])[1]||0)):1,scale:parsed?.percent||100,attr:parsed?.attr||"FOR",type:parsed?.attr==="INT"?"magical":"physical",cooldown:parseCooldown(desc),description:desc})});return out}
  function renderBattleHeader(){const p=state.player,e=state.enemy;$("battlePlayerImage").src=p.image;$("battlePlayerName").textContent=p.name;$("battleEnemyName").textContent=e.name;$("battlePlayerHpText").textContent=`${p.hp} / ${p.hpMax}`;$("battleEnemyHpText").textContent=`${e.hp} / ${e.hpMax}`;$("battlePlayerManaText").textContent=`${p.mana} / ${p.manaMax}`;$("battleEnemyManaText").textContent=`${e.mana} / ${e.manaMax}`;$("battlePlayerHpBar").style.width=`${Math.max(0,p.hp/p.hpMax*100)}%`;$("battleEnemyHpBar").style.width=`${Math.max(0,e.hp/e.hpMax*100)}%`;$("battlePlayerManaBar").style.width=`${Math.max(0,p.mana/p.manaMax*100)}%`;$("battleEnemyManaBar").style.width=`${Math.max(0,e.mana/e.manaMax*100)}%`;els.turnLabel.textContent=state.turn==="player"?p.name:e.name;els.movementInfo.textContent=`Movimentos: ${state.turn==="player"?state.moveLeft:0}`;$("battlePlayerTurn").textContent=state.turn==="player"?"Seu turno":"Aguardando";$("battleEnemyTurn").textContent=state.turn==="enemy"?"IA calculando":"IA instantânea";$("actionBasicState").textContent=state.actions.basic?"Usado":"Disponível";$("actionRaceState").textContent=state.actions.race?"Usada":"Disponível";$("actionClassState").textContent=state.actions.class?"Usada":"Disponível";els.defend.disabled=state.turn!=="player"||state.defendCooldown>0||state.actedThisTurn;els.defend.textContent=state.defendCooldown>0?`Defender — recarga ${state.defendCooldown}`:state.actedThisTurn?"Defender — apenas como primeira ação":"Defender próximo dano"}
  function renderSkills(){els.skillCards.innerHTML=actionData().map(a=>{const category=a.source==="basic"?"basic":a.source==="race"?"race":"class";const used=state.actions[category];const cd=Number(state.cooldowns[a.id]||0);return `<button type="button" class="arena-skill-card ${state.selectedAction?.id===a.id?"selected":""}" data-action-id="${esc(a.id)}" ${used||cd>0||state.turn!=="player"?"disabled":""}><small>${a.source==="basic"?"Ataque básico":a.source==="race"?"Raça":"Classe"}</small><strong>${esc(a.name)}</strong><span>${a.cost} Mana • ${a.range} casa(s)</span><p>${esc(a.description)}</p><em>${a.scale}% de ${a.attr} • dano ${a.type==="magical"?"mágico":"físico"}</em>${cd>0?`<b class="arena-cooldown">Recarga: ${cd} turno(s)</b>`:""}</button>`}).join("")}
  function reachableCells(origin,steps){const cells=[];for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++){const d=manhattan(origin,{x,y});if(d>0&&d<=steps&&!(x===state.enemy.x&&y===state.enemy.y))cells.push(`${x},${y}`)}return new Set(cells)}
  function rangeCells(origin,range){const cells=[];for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++){const d=manhattan(origin,{x,y});if(d>0&&d<=range)cells.push(`${x},${y}`)}return new Set(cells)}
  function unitHp(unit){return `<span class="unit-hp"><i style="width:${Math.max(0,unit.hp/unit.hpMax*100)}%"></i></span>`}
  function renderGrid(){const moveSet=state.turn==="player"&&!state.selectedAction?reachableCells(state.player,state.moveLeft):new Set();const rangeSet=state.turn==="player"&&state.selectedAction?rangeCells(state.player,state.selectedAction.range):new Set();let html="";for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++){const key=`${x},${y}`;const isP=x===state.player.x&&y===state.player.y;const isE=x===state.enemy.x&&y===state.enemy.y;const cls=["arena-cell"];if(moveSet.has(key))cls.push("can-move");if(rangeSet.has(key))cls.push("in-range");if(isE&&rangeSet.has(key))cls.push("targetable");html+=`<button type="button" class="${cls.join(" ")}" data-x="${x}" data-y="${y}" role="gridcell">${isP?`${unitHp(state.player)}<img src="${esc(state.player.image)}" alt="${esc(state.player.name)}"><span class="unit player-unit">${esc(state.player.name)}</span>`:isE?`${unitHp(state.enemy)}<span class="dummy-unit">✦</span><span class="unit enemy-unit">${esc(state.enemy.name)}</span>`:""}</button>`}els.grid.innerHTML=html}
  function startTimer(){clearInterval(state.timerId);state.timer=60;els.timer.textContent=state.timer;state.timerId=setInterval(()=>{if(!state.started||state.turn!=="player")return;state.timer--;els.timer.textContent=state.timer;if(state.timer<=0){clearInterval(state.timerId);state.player.hp=0;renderAll();finish("O tempo chegou a zero. O jogador perdeu o combate.")}},1000)}
  function calculateDamage(attacker,target,action){const raw=Math.max(0,Math.round(Number(attacker.attrs[action.attr]||0)*(action.scale/100)));const info=defense?.breakdown({def:target.attrs.DEF,res:target.attrs.RES})||{};const reduction=action.type==="magical"?(info.magicalReduction??Math.min(75,Math.floor(target.attrs.RES/5))):(info.physicalReduction??Math.min(75,Math.floor(target.attrs.DEF/5)));return{raw,reduction,final:Math.max(0,Math.round(raw*(1-reduction/100)))}}
  function useAction(action,target){if(state.turn!=="player"||target!==state.enemy)return;const category=action.source==="basic"?"basic":action.source==="race"?"race":"class";if(state.actions[category]||Number(state.cooldowns[action.id]||0)>0)return;if(manhattan(state.player,state.enemy)>action.range){log(`<strong>${esc(action.name)}</strong> está fora de alcance.`);return}if(state.player.mana<action.cost){log(`Mana insuficiente para <strong>${esc(action.name)}</strong>.`);return}const dmg=calculateDamage(state.player,state.enemy,action);state.player.mana-=action.cost;if(state.enemy.defending){log(`${state.enemy.name} bloqueou 100% do dano.`);state.enemy.defending=false}else state.enemy.hp=Math.max(0,state.enemy.hp-dmg.final);state.actions[category]=true;state.actedThisTurn=true;if(action.cooldown>0)state.cooldowns[action.id]=action.cooldown;state.selectedAction=null;log(`${state.player.name} usa <strong>${esc(action.name)}</strong>: ${dmg.raw} bruto, ${dmg.reduction}% reduzido, <strong>${dmg.final} de dano</strong>.`);renderAll();if(state.enemy.hp<=0)finish(`${state.enemy.name} foi derrotado.`)}
  function moveUnit(unit,x,y){const dist=manhattan(unit,{x,y});if(dist<1||dist>state.moveLeft)return;unit.x=x;unit.y=y;state.moveLeft-=dist;state.actedThisTurn=true;log(`${unit.name} moveu ${dist} casa(s).`);renderAll()}
  function decrementCooldowns(){Object.keys(state.cooldowns).forEach(key=>{state.cooldowns[key]=Math.max(0,Number(state.cooldowns[key]||0)-1);if(state.cooldowns[key]===0)delete state.cooldowns[key]});if(state.defendCooldown>0)state.defendCooldown--}
  function enemyTurn(){if(!state.started)return;state.turn="enemy";clearInterval(state.timerId);renderAll();setTimeout(()=>{if(!state.started)return;const basic={id:"enemy-basic",name:"Ataque básico",source:"basic",cost:0,range:1,scale:100,attr:Number(state.enemy.attrs.INT)>Number(state.enemy.attrs.FOR)?"INT":"FOR",type:Number(state.enemy.attrs.INT)>Number(state.enemy.attrs.FOR)?"magical":"physical"};let dist=manhattan(state.enemy,state.player);const move=movementFromIni(state.enemy.attrs.INI);if(dist>basic.range){let steps=Math.min(move,Math.max(0,dist-basic.range));while(steps-->0){if(state.enemy.x<state.player.x)state.enemy.x++;else if(state.enemy.x>state.player.x)state.enemy.x--;else if(state.enemy.y<state.player.y)state.enemy.y++;else if(state.enemy.y>state.player.y)state.enemy.y--}log(`${state.enemy.name} se aproximou do alvo.`)}dist=manhattan(state.enemy,state.player);const shouldDefend=state.enemy.hp/state.enemy.hpMax<.3&&Math.random()<.35;if(shouldDefend){state.enemy.defending=true;log(`${state.enemy.name} decidiu defender e bloqueará o próximo dano.`)}else if(dist<=basic.range){const dmg=calculateDamage(state.enemy,state.player,basic);if(state.player.defending){log(`${state.player.name} bloqueou 100% do dano.`);state.player.defending=false}else state.player.hp=Math.max(0,state.player.hp-dmg.final);log(`${state.enemy.name} usa <strong>Ataque básico</strong> e causa <strong>${dmg.final}</strong> de dano.`)}else log(`${state.enemy.name} não encontrou um ataque válido neste turno.`);renderAll();if(state.player.hp<=0){finish(`${state.player.name} foi derrotado.`);return}beginPlayerTurn()},450)}
  function beginPlayerTurn(){state.turn="player";state.round++;state.actions={basic:false,race:false,class:false};state.selectedAction=null;state.moveLeft=movementFromIni(state.player.attrs.INI);state.actedThisTurn=false;decrementCooldowns();renderAll();startTimer();log(`Turno ${state.round}: ${state.player.name} pode agir.`)}
  function renderAll(){renderBattleHeader();renderSkills();renderGrid()}
  function finish(text){state.started=false;clearInterval(state.timerId);els.endTurn.disabled=true;els.defend.disabled=true;log(`<strong>${esc(text)}</strong>`);renderAll()}
  async function loadCharacters(){const current=await account.current().catch(()=>null);if(!current){window.location.replace("conta.html");return}let characters=[];try{characters=await (account.getCharacters?account.getCharacters():account.listCharacters?.())}catch(error){console.error(error);els.message.textContent=error.message||"Não foi possível carregar os personagens."}state.characters=Array.isArray(characters)?characters:[];els.character.innerHTML=state.characters.length?state.characters.map(char=>`<option value="${esc(char.id)}">${esc(char.name)} • Nível ${esc(char.level||1)}</option>`).join(""):'<option value="">Nenhum personagem disponível</option>';els.character.disabled=!state.characters.length;els.start.disabled=!state.characters.length;if(state.characters.length)await loadCharacter(state.characters[0].id);else els.message.textContent="Nenhum personagem foi encontrado nesta conta."}
  async function loadCharacter(id){if(!id)return;els.message.textContent="Carregando combatente...";try{const sheet=await account.getCharacterSheet(id);state.sheet=sheet;state.character=sheet.character;const base=baseAttributes(sheet.attributes);const bonus=equipmentBonus(sheet.equipment);state.attrs=Object.fromEntries(attrs.map(attr=>[attr,(base[attr]||0)+(bonus[attr]||0)]));state.race=(window.WONDERLAND_RACES||[]).find(item=>item.id===sheet.character.race_id);state.cls=(window.WONDERLAND_CLASSES||{})[sheet.character.class_id];state.skills=officialSkills(state.cls,Number(sheet.character.level||1),sheet.character.path_id);state.dummy=buildDummy(state.attrs,state.cls,state.race);renderSetup();els.message.textContent="Combatentes prontos."}catch(error){console.error(error);els.message.textContent=error.message||"Não foi possível carregar o personagem."}}
  function startBattle(){if(!state.sheet||!state.dummy)return;state.started=true;state.round=1;state.turn="player";state.actions={basic:false,race:false,class:false};state.cooldowns={};state.defendCooldown=0;state.actedThisTurn=false;state.player={name:state.character.name,image:state.character.image_url||state.race?.artwork||state.race?.image||"assets/images/logo.png",attrs:{...state.attrs},hpMax:hpMaxFor(state.attrs,state.race),manaMax:manaMaxFor(state.attrs,state.race),hp:0,mana:0,x:46,y:50,defending:false};state.player.hp=state.player.hpMax;state.player.mana=state.player.manaMax;state.enemy={name:state.dummy.name,attrs:{...state.dummy.attrs},hpMax:state.dummy.hpMax,manaMax:state.dummy.manaMax,hp:state.dummy.hpMax,mana:state.dummy.manaMax,x:54,y:50,defending:false};state.moveLeft=movementFromIni(state.player.attrs.INI);state.log=[];els.setup.hidden=true;els.battle.hidden=false;els.endTurn.disabled=false;renderAll();startTimer();log(`${state.player.name} entrou na Arena contra ${state.enemy.name}.`)}
  els.character.addEventListener("change",()=>loadCharacter(els.character.value));
  els.start.addEventListener("click",startBattle);
  els.skillCards.addEventListener("click",event=>{const button=event.target.closest("[data-action-id]");if(!button||button.disabled)return;const action=actionData().find(a=>a.id===button.dataset.actionId);if(!action)return;state.selectedAction=state.selectedAction?.id===action.id?null:action;renderAll()});
  els.grid.addEventListener("click",event=>{const cell=event.target.closest("[data-x]");if(!cell||!state.started||state.turn!=="player")return;const x=Number(cell.dataset.x),y=Number(cell.dataset.y);if(x===state.enemy.x&&y===state.enemy.y&&state.selectedAction){useAction(state.selectedAction,state.enemy);return}if(!state.selectedAction)moveUnit(state.player,x,y)});
  els.endTurn.addEventListener("click",()=>{if(state.turn==="player"&&state.started)enemyTurn()});
  els.defend.addEventListener("click",()=>{if(state.turn!=="player"||state.defendCooldown>0||state.actedThisTurn)return;state.player.defending=true;state.defendCooldown=5;state.actions={basic:true,race:true,class:true};state.moveLeft=0;state.actedThisTurn=true;log(`${state.player.name} abriu mão de todas as ações e entrou em defesa.`);renderAll();enemyTurn()});
  els.reset.addEventListener("click",()=>{state.started=false;clearInterval(state.timerId);els.battle.hidden=true;els.setup.hidden=false;els.message.textContent="Teste encerrado sem alterar a ficha real."});
  await loadCharacters();
})();