"use strict";
(async function(){
  const account=window.WONDERLAND_ACCOUNT, defense=window.WONDERLAND_DEFENSE_SYSTEM, manaSystem=window.WONDERLAND_MANA_SYSTEM, skillCosts=window.WONDERLAND_SKILL_COSTS;
  const attrs=["FOR","DEF","RES","INI","INT","ARC"], GRID_W=20, GRID_H=14, $=id=>document.getElementById(id);
  const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
  const els={setup:$("arenaSetup"),battle:$("arenaBattle"),character:$("arenaCharacter"),start:$("arenaStart"),message:$("arenaMessage"),grid:$("arenaGrid"),skillCards:$("arenaSkillCards"),log:$("arenaCombatLog"),timer:$("arenaTimer"),turnLabel:$("arenaTurnLabel"),movementInfo:$("arenaMovementInfo"),defend:$("arenaDefend"),endTurn:$("arenaEndTurn"),reset:$("arenaReset"),outcome:$("arenaOutcome"),outcomeTitle:$("arenaOutcomeTitle"),outcomeText:$("arenaOutcomeText"),outcomeEyebrow:$("arenaOutcomeEyebrow"),outcomeAgain:$("arenaOutcomeAgain")};
  const state={characters:[],sheet:null,character:null,race:null,cls:null,attrs:null,skills:[],raceSkills:[],dummy:null,started:false,turn:"player",round:1,timer:60,timerId:null,selectedAction:null,player:null,enemy:null,moveLeft:0,actions:{basic:false,race:false,class:false},defendCooldown:0,cooldowns:{},log:[],actedThisTurn:false,roundMiss:{player:false,enemy:false},damageFx:{player:null,enemy:null},passives:{player:[],enemy:[]}};
  if(!account){els.message.textContent="Sistema de contas indisponível.";return}
  const txt=v=>String(v??"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();
  function baseAttributes(row){return Object.fromEntries(attrs.map(a=>{const k=a.toLowerCase();return[a,Number(row?.[`base_${k}`]||20)+Number(row?.[`allocated_${k}`]||0)+Number(row?.[`racial_${k}`]||0)]}))}
  function equipmentBonus(equipment){const out=Object.fromEntries(attrs.map(a=>[a,0])),seen=new Set();(equipment||[]).forEach(item=>{if(item?.metadata?.linked_two_hand)return;const key=`${item.item_key}:${item.slot}`;if(seen.has(key))return;seen.add(key);Object.entries(item?.metadata?.stats||{}).forEach(([a,v])=>{a=String(a).toUpperCase();if(attrs.includes(a))out[a]+=Number(v)||0})});return out}
  function collectPassives(cls,race){const list=[];(cls?.passivas||[]).forEach(p=>list.push({source:"class",name:p.nome||p.name||"Passiva de classe",text:txt(p.descricao||p.description)}));(race?.traits||[]).forEach(p=>list.push({source:"race",name:p.title||p.nome||p.name||"Passiva racial",text:txt(p.content||p.descricao||p.description)}));return list}
  function applyStartPassives(unit,passives){unit.mod={damageOut:1,damageIn:1,heal:1,shield:0};passives.forEach(p=>{const t=p.text.toLowerCase();const add=(re,key)=>{const m=t.match(re);if(m)unit.mod[key]*=1+Number(m[1])/100};const reduce=(re,key)=>{const m=t.match(re);if(m)unit.mod[key]*=1-Number(m[1])/100};add(/(\d+)%\s+(?:de\s+)?(?:dano|dano físico|dano magico|dano mágico)/,"damageOut");reduce(/recebe\s+(\d+)%\s+menos\s+dano/,"damageIn");const shield=t.match(/escudo(?: equivalente a| de)?\s*(\d+)%\s+(?:da|de)\s+(for|def|res|ini|int|arc)/);if(shield)unit.mod.shield+=Math.round((Number(unit.attrs[shield[2].toUpperCase()]||0)*Number(shield[1]))/100);const heal=t.match(/recupera\s+(\d+)%\s+do hp máximo/);if(heal)unit.mod.heal=Math.max(unit.mod.heal,1+Number(heal[1])/100)});
  }
  function randomEntry(list){return list[Math.floor(Math.random()*list.length)]||null}
  function roleWeights(cls){const t=`${cls?.nome||""} ${cls?.descricao||""}`.toLowerCase();if(/mago|feiticeiro|bruxo|necromante|alquimista/.test(t))return{INT:1.5,ARC:1.25,INI:1.05,RES:.95,DEF:.8,FOR:.65};if(/bardo|druida|suporte|cura|invoca/.test(t))return{ARC:1.5,INT:1.2,RES:1.1,INI:1.05,DEF:.9,FOR:.75};if(/assassino|ninja|arqueiro/.test(t))return{INI:1.5,FOR:1.25,DEF:.95,RES:.9,INT:.8,ARC:.75};if(/guerreiro|bárbaro|barbaro|espadachim|tanque/.test(t))return{FOR:1.4,DEF:1.3,RES:1.2,INI:.95,INT:.7,ARC:.75};return Object.fromEntries(attrs.map(a=>[a,1]))}
  function buildDummy(playerAttrs,cls,race){const w=roleWeights(cls),total=attrs.reduce((s,a)=>s+Number(playerAttrs[a]||0),0),sw=attrs.reduce((s,a)=>s+w[a],0),distributed={};attrs.forEach(a=>distributed[a]=Math.max(1,Math.round(total*w[a]/sw)));const hpBase=Number(race?.stats?.hp||500),hpMax=hpBase+Math.floor(distributed.RES/5)*10,manaMax=manaSystem?.breakdown({intValue:distributed.INT,race})?.total||100+Math.floor(distributed.INT/5)*10;return{name:"Boneco de Teste",attrs:distributed,hpMax,manaMax,race:race?.name||"Raça aleatória",className:cls?.nome||"Classe aleatória",raceData:race,classData:cls}}
  function randomizeDummy(){const race=randomEntry(window.WONDERLAND_RACES||[]),cls=randomEntry(Object.values(window.WONDERLAND_CLASSES||{}));state.dummy=buildDummy(state.attrs,cls,race);return state.dummy}
  function movementFromIni(ini){return Math.max(1,Math.min(8,Math.floor(Number(ini||0)/25)))}
  function manhattan(a,b){return Math.abs(a.x-b.x)+Math.abs(a.y-b.y)}
  function hpMaxFor(a,r){return Number(r?.stats?.hp||500)+Math.floor(Number(a.RES||0)/5)*10}
  function manaMaxFor(a,r){return manaSystem?.breakdown({intValue:Number(a.INT||0),race:r})?.total||100+Math.floor(Number(a.INT||0)/5)*10}
  function calculateDamage(attacker,target,action){const raw=Math.max(0,Math.round(Number(attacker.attrs[action.attr]||0)*(action.scale/100)*(attacker.mod?.damageOut||1)));const info=defense?.breakdown({def:target.attrs.DEF,res:target.attrs.RES})||{};const reduction=action.type==="magical"?(info.magicalReduction??Math.min(75,Math.floor(target.attrs.RES/5))):(info.physicalReduction??Math.min(75,Math.floor(target.attrs.DEF/5)));let final=Math.max(0,Math.round(raw*(1-reduction/100)*(target.mod?.damageIn||1)));if(target.mod?.shield>0){const blocked=Math.min(final,target.mod.shield);target.mod.shield-=blocked;final-=blocked}return{raw,reduction,final}}
  async function loadCharacter(id){const sheet=await account.getCharacterSheet(id);state.sheet=sheet;state.character=sheet.character;const base=baseAttributes(sheet.attributes),bonus=equipmentBonus(sheet.equipment);state.attrs=Object.fromEntries(attrs.map(a=>[a,(base[a]||0)+(bonus[a]||0)]));state.race=(window.WONDERLAND_RACES||[]).find(r=>r.id===sheet.character.race_id);state.cls=(window.WONDERLAND_CLASSES||{})[sheet.character.class_id];state.passives.player=collectPassives(state.cls,state.race);$("setupPlayerImage").src=state.character.image_url||state.race?.artwork||state.race?.image||"assets/images/logo.png";$("setupPlayerName").textContent=state.character.name;$("setupPlayerSummary").textContent=`${state.race?.name||state.character.race_id} • ${state.cls?.nome||state.character.class_id}`;$("setupPlayerStats").innerHTML=attrs.map(a=>`<span>${a}<strong>${esc(state.attrs[a])}</strong></span>`).join("");$("setupEnemySummary").textContent="Raça e classe sorteadas ao começar";$("setupEnemyStats").innerHTML=attrs.map(a=>`<span>${a}<strong>?</strong></span>`).join("");els.message.textContent=`${state.passives.player.length} passiva(s) serão ativadas no combate.`}
  async function loadCharacters(){const current=await account.current().catch(()=>null);if(!current){location.replace("conta.html");return}const chars=await account.getCharacters();state.characters=Array.isArray(chars)?chars:[];els.character.innerHTML=state.characters.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} • Nível ${esc(c.level||1)}</option>`).join("");els.start.disabled=!state.characters.length;if(state.characters[0])await loadCharacter(state.characters[0].id)}
  function renderPassiveSummary(){let box=$("arenaPassiveSummary");if(!box){box=document.createElement("section");box.id="arenaPassiveSummary";box.className="arena-passive-summary";els.battle.insertBefore(box,els.battle.firstChild)}box.innerHTML=`<article><span>Passivas do jogador</span>${state.passives.player.map(p=>`<div><strong>${esc(p.name)}</strong><small>${esc(p.text)}</small></div>`).join("")||"<em>Nenhuma.</em>"}</article><article><span>Passivas do Boneco</span>${state.passives.enemy.map(p=>`<div><strong>${esc(p.name)}</strong><small>${esc(p.text)}</small></div>`).join("")||"<em>Nenhuma.</em>"}</article>`}
  function startBattle(){if(!state.character)return;randomizeDummy();const pHp=hpMaxFor(state.attrs,state.race),pMana=manaMaxFor(state.attrs,state.race);state.player={name:state.character.name,attrs:{...state.attrs},hp:pHp,hpMax:pHp,mana:pMana,manaMax:pMana,x:2,y:7};state.enemy={name:"Boneco de Teste",attrs:{...state.dummy.attrs},hp:state.dummy.hpMax,hpMax:state.dummy.hpMax,mana:state.dummy.manaMax,manaMax:state.dummy.manaMax,x:17,y:7};state.passives.enemy=collectPassives(state.dummy.classData,state.dummy.raceData);applyStartPassives(state.player,state.passives.player);applyStartPassives(state.enemy,state.passives.enemy);state.started=true;els.setup.hidden=true;els.battle.hidden=false;renderPassiveSummary();els.message.textContent="Passivas raciais e de classe ativadas."}
  els.character.addEventListener("change",()=>loadCharacter(els.character.value));els.start.addEventListener("click",startBattle);els.reset.addEventListener("click",()=>location.reload());await loadCharacters();
})();