"use strict";
(async function(){
  const account=window.WONDERLAND_ACCOUNT, defense=window.WONDERLAND_DEFENSE_SYSTEM, manaSystem=window.WONDERLAND_MANA_SYSTEM, skillCosts=window.WONDERLAND_SKILL_COSTS;
  const attrs=["FOR","DEF","RES","INI","INT","ARC"], GRID_W=20, GRID_H=14, $=id=>document.getElementById(id);
  const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
  const strip=v=>String(v??"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();
  const slug=v=>strip(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
  const els={setup:$("arenaSetup"),battle:$("arenaBattle"),character:$("arenaCharacter"),start:$("arenaStart"),message:$("arenaMessage"),grid:$("arenaGrid"),skillCards:$("arenaSkillCards"),log:$("arenaCombatLog"),timer:$("arenaTimer"),turnLabel:$("arenaTurnLabel"),movementInfo:$("arenaMovementInfo"),defend:$("arenaDefend"),endTurn:$("arenaEndTurn"),reset:$("arenaReset"),outcome:$("arenaOutcome"),outcomeTitle:$("arenaOutcomeTitle"),outcomeText:$("arenaOutcomeText"),outcomeEyebrow:$("arenaOutcomeEyebrow"),outcomeAgain:$("arenaOutcomeAgain")};
  const state={characters:[],sheet:null,character:null,race:null,cls:null,path:null,attrs:null,skills:[],raceSkills:[],dummy:null,started:false,turn:"player",round:1,timer:60,timerId:null,selectedAction:null,player:null,enemy:null,moveLeft:0,actions:{basic:false,race:false,class:false},defendCooldown:0,cooldowns:{},enemyCooldowns:{},log:[],actedThisTurn:false,roundMiss:{player:false,enemy:false},damageFx:{player:null,enemy:null},passives:{player:[],enemy:[]}};
  if(!account){els.message.textContent="Sistema de contas indisponível.";return}
  function textValue(v){if(v==null)return"";if(typeof v==="string"||typeof v==="number")return strip(v);if(Array.isArray(v))return v.map(textValue).filter(Boolean).join(" • ");if(typeof v==="object")return textValue(v.description||v.descricao||v.content||v.text||v.nome||v.name||"");return""}
  function parseLevel(v){return Number(String(v||"").match(/(\d+)/)?.[1]||1)}
  function parseScale(t){const m=String(t||"").match(/(\d+(?:[.,]\d+)?)%\s+(?:do|de|da)\s+(?:seu\s+)?(FOR|DEF|RES|INI|INT|ARC)/i);return m?{percent:Number(m[1].replace(",",".")),attr:m[2].toUpperCase()}:null}
  function parseMana(t){return Number((String(t||"").match(/(?:custa|consome|gasta|custo\s*:?)\s*(\d+)\s*mana/i)||String(t||"").match(/(\d+)\s*mana/i))?.[1]||0)}
  function parseCooldown(t){return Math.max(0,Number(String(t||"").match(/(?:recarga|cooldown)\D*(\d+)/i)?.[1]||0))}
  function baseAttributes(row){return Object.fromEntries(attrs.map(a=>{const k=a.toLowerCase();return[a,Number(row?.[`base_${k}`]||20)+Number(row?.[`allocated_${k}`]||0)+Number(row?.[`racial_${k}`]||0)]}))}
  function equipmentBonus(equipment){const out=Object.fromEntries(attrs.map(a=>[a,0])),seen=new Set();(equipment||[]).forEach(item=>{if(item?.metadata?.linked_two_hand)return;const key=`${item.item_key}:${item.slot}`;if(seen.has(key))return;seen.add(key);Object.entries(item?.metadata?.stats||{}).forEach(([a,v])=>{a=String(a).toUpperCase();if(attrs.includes(a))out[a]+=Number(v)||0})});return out}
  function resolvePath(cls,character){const raw=character?.path_id||character?.class_path_id||character?.caminho_id||character?.class_path||character?.path||"";if(!raw)return null;const wanted=slug(raw);return (cls?.caminhos||[]).find(p=>slug(p.id)===wanted||slug(p.nome)===wanted)||null}
  function officialSkills(cls,level,path){const list=[];(cls?.progressao||[]).forEach(s=>{const unlock=parseLevel(s.nivel);if(unlock<=level)list.push({...s,source:"class",unlock})});if(level>=50&&path)(path.habilidades||[]).forEach((s,i)=>{const unlock=Number(s.nivel||[60,70,80,90,100][i]||100);if(unlock<=level)list.push({...s,source:"class",unlock,pathName:path.nome})});return list}
  function officialRaceSkills(race,level){return(race?.progression||[]).filter(s=>Number(s.level||0)<=level).map(s=>({...s,source:"race",unlock:Number(s.level||1),nome:s.name||s.nome,descricao:s.content||s.descricao,meta:s.meta||[]}))}
  function collectPassives(cls,race,path){const list=[];(cls?.passivas||[]).forEach(p=>list.push({source:"class",name:p.nome||p.name||"Passiva de classe",text:textValue(p.descricao||p.description)}));(race?.traits||[]).forEach(p=>list.push({source:"race",name:p.title||p.nome||p.name||"Passiva racial",text:textValue(p.content||p.descricao||p.description)}));if(path?.passiva)list.push({source:"path",name:path.passiva.nome||path.nome||"Passiva do Caminho",text:textValue(path.passiva.descricao||path.passiva.description)});return list}
  function compilePassives(unit,list){unit.passives=list;unit.mod={damageOut:1,damageIn:1,physicalOut:1,magicalOut:1,healOut:1,shield:0,execute:0};list.forEach(p=>{const t=p.text.toLowerCase();let m;if((m=t.match(/(?:causa|recebe)\s+(\d+)%\s+(?:a mais|mais)\s+dano/)))unit.mod.damageOut*=1+Number(m[1])/100;if((m=t.match(/(?:dano físico|dano fisico).*?(\d+)%|(?:\d+)%.*?dano físico/)))unit.mod.physicalOut*=1+Number(m[1]||m[2]||0)/100;if((m=t.match(/(?:dano mágico|dano magico).*?(\d+)%|(?:\d+)%.*?dano mágico/)))unit.mod.magicalOut*=1+Number(m[1]||m[2]||0)/100;if((m=t.match(/recebe\s+(\d+)%\s+menos\s+dano/)))unit.mod.damageIn*=1-Number(m[1])/100;if((m=t.match(/escudo(?: equivalente a| de)?\s*(\d+)%\s+(?:da|de)\s+(for|def|res|ini|int|arc)/)))unit.mod.shield+=Math.round(Number(unit.attrs[m[2].toUpperCase()]||0)*Number(m[1])/100);if((m=t.match(/contra alvos abaixo de\s*(\d+)%.*?causa\s*(\d+)%\s+a mais/)))unit.mod.execute=Math.max(unit.mod.execute,Number(m[2])/100)});return unit.mod}
  function passiveSummary(unit){return (unit.passives||[]).map(p=>p.name).join(" • ")||"Nenhuma passiva"}
  function randomEntry(list){return list[Math.floor(Math.random()*list.length)]||null}
  function roleWeights(cls){const t=`${cls?.nome||""} ${cls?.especializacao?.titulo||cls?.especializacao||""} ${cls?.descricao||""}`.toLowerCase();if(/mago|feiticeiro|bruxo|necromante|alquimista/.test(t))return{INT:1.5,ARC:1.25,INI:1.05,RES:.95,DEF:.8,FOR:.65};if(/bardo|druida|suporte|cura|invoca/.test(t))return{ARC:1.5,INT:1.2,RES:1.1,INI:1.05,DEF:.9,FOR:.75};if(/assassino|ninja|arqueiro/.test(t))return{INI:1.5,FOR:1.25,DEF:.95,RES:.9,INT:.8,ARC:.75};if(/guerreiro|bárbaro|barbaro|espadachim|tanque/.test(t))return{FOR:1.4,DEF:1.3,RES:1.2,INI:.95,INT:.7,ARC:.75};return Object.fromEntries(attrs.map(a=>[a,1]))}
  function buildDummy(playerAttrs,cls,race,path,level){const w=roleWeights(cls),total=attrs.reduce((s,a)=>s+Number(playerAttrs[a]||0),0),sw=attrs.reduce((s,a)=>s+w[a],0),distributed={};attrs.forEach(a=>distributed[a]=Math.max(1,Math.round(total*w[a]/sw)));const hpBase=Number(race?.stats?.hp||500),hpMax=hpBase+Math.floor(distributed.RES/5)*10,manaMax=manaSystem?.breakdown({intValue:distributed.INT,race})?.total||100+Math.floor(distributed.INT/5)*10;return{name:"Boneco de Teste",attrs:distributed,hpMax,manaMax,race:race?.name||"Raça aleatória",className:cls?.nome||"Classe aleatória",raceData:race,classData:cls,pathData:path,pathName:path?.nome||"Sem Caminho",level,skills:officialSkills(cls,level,path),raceSkills:officialRaceSkills(race,level)}}
  function randomizeDummy(){const race=randomEntry(window.WONDERLAND_RACES||[]),cls=randomEntry(Object.values(window.WONDERLAND_CLASSES||{})),level=Number(state.character?.level||1),path=level>=50?randomEntry(cls?.caminhos||[]):null;state.dummy=buildDummy(state.attrs,cls,race,path,level);return state.dummy}
  function movementFromIni(ini){return Math.max(1,Math.min(8,Math.floor(Number(ini||0)/25)))}
  function manhattan(a,b){return Math.abs(a.x-b.x)+Math.abs(a.y-b.y)}
  function hpMaxFor(a,r){return Number(r?.stats?.hp||500)+Math.floor(Number(a.RES||0)/5)*10}
  function manaMaxFor(a,r){return manaSystem?.breakdown({intValue:Number(a.INT||0),race:r})?.total||100+Math.floor(Number(a.INT||0)/5)*10}
  function log(t){state.log.unshift(t);state.log=state.log.slice(0,50);els.log.innerHTML=state.log.map(x=>`<p>${x}</p>`).join("")}
  function basicWeaponInfo(){const names=(state.sheet?.equipment||[]).map(e=>String(e.metadata?.name||"")).join(" ");if(/cajado|orbe|grimório|grimorio|tomo|cetro|foco arcano|varinha/i.test(names))return{type:"magical",attr:"INT",range:7,label:"Ataque mágico à distância"};if(/lança|lanca|alabarda/i.test(names))return{type:"physical",attr:"FOR",range:3,label:"Ataque de alcance com lança"};return{type:"physical",attr:"FOR",range:1,label:"Ataque físico corpo a corpo"}}
  function isSelfSkill(desc,skill){const t=`${desc} ${skill?.categoria||skill?.category||skill?.tipo||""}`.toLowerCase();return /transforma|transformação|transformacao|postura|forma |assume|fortalecimento|aprimoramento|recupera|regenera|cura a si|escudo para si|recebe .*% de (for|def|res|ini|int|arc)|durante os próximos|durante os proximos/.test(t)&&!/causa|atinge|alvo inimigo|inimigo recebe/.test(t)}
  function inferCost(skill,desc,level,source,cls){const full=`${desc} ${(skill.meta||[]).join(" ")}`;const explicit=parseMana(full);if(explicit>0)return explicit;if(/sem custo/i.test(full))return 0;if(skillCosts?.infer)return Math.max(5,Number(skillCosts.infer(cls||state.cls,skill,level,{path:source==="class"&&level>=60,ultimate:/ultimate|máxima|maxima/i.test(String(skill.tipo||skill.category||skill.categoria||""))}).value||0));return Math.max(10,Math.min(120,Math.round((12+level*.7)/5)*5))}
  function toAction(skill,index,source,cls){const desc=textValue(skill.descricao||skill.content),parsed=parseScale(desc),level=Number(skill.unlock||skill.level||1),meta=Array.isArray(skill.meta)?skill.meta:[],target=isSelfSkill(desc,skill)?"self":"enemy",healing=/cura|recupera .*hp|restaura .*hp|regenera/i.test(desc),shield=/escudo/i.test(desc);return{id:`${source}-${slug(skill.nome||skill.name||index)}-${index}`,name:textValue(skill.nome||skill.name)||`Habilidade ${index+1}`,source,cost:inferCost({...skill,meta},desc,level,source,cls),range:target==="self"?0:(/distância|distancia|alcance|projétil|projetil|área|area/i.test(desc)?Math.max(3,Number((desc.match(/(\d+)\s*(?:casa|alcance)/i)||[])[1]||0)):1),scale:parsed?.percent||100,attr:parsed?.attr||(/mágic|magico|cura|escudo/i.test(desc)?(/cura|escudo/i.test(desc)?"ARC":"INT"):"FOR"),type:parsed?.attr==="INT"||/mágic|magico/i.test(desc)?"magical":"physical",cooldown:parseCooldown(`${desc} ${meta.join(" ")}`),description:desc,target,healing,shield}}
  function playerActionData(){const b=basicWeaponInfo();return{basic:[{id:"basic",name:"Ataque básico",source:"basic",cost:0,range:b.range,scale:100,attr:b.attr,type:b.type,cooldown:0,description:`100% de ${b.attr}. ${b.label}.`,target:"enemy"}],class:state.skills.map((s,i)=>toAction(s,i,"class",state.cls)),race:state.raceSkills.map((s,i)=>toAction(s,i,"race",state.cls))}}
  function enemyActionData(){const d=state.dummy||{};return{basic:[{id:"enemy-basic",name:"Ataque básico",source:"basic",cost:0,range:d.attrs?.INT>d.attrs?.FOR?7:1,scale:100,attr:d.attrs?.INT>d.attrs?.FOR?"INT":"FOR",type:d.attrs?.INT>d.attrs?.FOR?"magical":"physical",cooldown:0,description:"Ataque básico adaptativo.",target:"enemy"}],class:(d.skills||[]).map((s,i)=>toAction(s,i,"class",d.classData)),race:(d.raceSkills||[]).map((s,i)=>toAction(s,i,"race",d.classData))}}
  function allPlayerActions(){const g=playerActionData();return[...g.basic,...g.class,...g.race]}
  function actionButton(a){const used=state.actions[a.source],cd=Number(state.cooldowns[a.id]||0),cost=a.cost===0?"Sem custo":`${a.cost} Mana`;return`<button type="button" class="arena-action-button ${state.selectedAction?.id===a.id?"selected":""}" data-action-id="${esc(a.id)}" ${used||cd>0||state.turn!=="player"?"disabled":""}><span class="arena-action-name">${esc(a.name)}</span><span class="arena-action-meta">${esc(cost)}</span>${cd>0?`<span class="arena-action-cd">${cd}</span>`:""}<div class="arena-skill-tooltip"><small>${a.source==="basic"?"Ataque básico":a.source==="race"?"Raça":"Classe"}</small><strong>${esc(a.name)}</strong><p>${esc(a.description)}</p><dl><div><dt>Alvo</dt><dd>${a.target==="self"?"Próprio usuário":"Inimigo"}</dd></div><div><dt>Dano/Efeito</dt><dd>${a.healing?"Cura":a.shield?"Escudo":a.target==="self"?"Efeito próprio":`${a.scale}% de ${a.attr}`}</dd></div><div><dt>Mana</dt><dd>${esc(cost)}</dd></div><div><dt>Alcance</dt><dd>${a.target==="self"?"Próprio":a.range}</dd></div><div><dt>Recarga</dt><dd>${a.cooldown||0}</dd></div></dl></div></button>`}
  function renderSkills(){const g=playerActionData();els.skillCards.innerHTML=[["basic","Ataque básico"],["class","Classe"],["race","Raça"]].map(([k,l])=>`<section class="arena-action-group"><header><span>${l}</span><strong>${state.actions[k]?"Usado":"Disponível"}</strong></header><div>${g[k].length?g[k].map(actionButton).join(""):'<p class="arena-no-actions">Nenhuma habilidade disponível.</p>'}</div></section>`).join("")}
  function ensurePassivePanel(){let panel=$("arenaPassivePanel");if(!panel){panel=document.createElement("section");panel.id="arenaPassivePanel";panel.className="arena-passive-panel";els.battle.insertBefore(panel,els.battle.querySelector(".arena-battle-layout"))}panel.innerHTML=`<article><span>Passivas ativas — ${esc(state.player.name)}</span><p>${esc(passiveSummary(state.player))}</p></article><article><span>Passivas ativas — Boneco</span><p>${esc(passiveSummary(state.enemy))}</p></article>`}
  function renderSetup(){if(!state.sheet)return;$("setupPlayerImage").src=state.character.image_url||state.race?.artwork||state.race?.image||"assets/images/logo.png";$("setupPlayerName").textContent=state.character.name;$("setupPlayerSummary").textContent=`${state.race?.name||state.character.race_id} • ${state.cls?.nome||state.character.class_id}${state.path?` • ${state.path.nome}`:""}`;$("setupPlayerStats").innerHTML=attrs.map(a=>`<span>${a}<strong>${esc(state.attrs[a])}</strong></span>`).join("");$("setupEnemySummary").textContent="Raça, classe e Caminho sorteados ao começar";$("setupEnemyStats").innerHTML=attrs.map(a=>`<span>${a}<strong>?</strong></span>`).join("")}
  function renderHeader(){const p=state.player,e=state.enemy;$("battlePlayerImage").src=p.image;$("battlePlayerName").textContent=p.name;$("battleEnemyName").textContent=`${e.name} • ${e.raceName} / ${e.className}${e.pathName&&e.pathName!=="Sem Caminho"?` / ${e.pathName}`:""}`;$("battlePlayerHpText").textContent=`${p.hp} / ${p.hpMax}`;$("battleEnemyHpText").textContent=`${e.hp} / ${e.hpMax}`;$("battlePlayerManaText").textContent=`${p.mana} / ${p.manaMax}`;$("battleEnemyManaText").textContent=`${e.mana} / ${e.manaMax}`;$("battlePlayerHpBar").style.width=`${Math.max(0,p.hp/p.hpMax*100)}%`;$("battleEnemyHpBar").style.width=`${Math.max(0,e.hp/e.hpMax*100)}%`;$("battlePlayerManaBar").style.width=`${Math.max(0,p.mana/p.manaMax*100)}%`;$("battleEnemyManaBar").style.width=`${Math.max(0,e.mana/e.manaMax*100)}%`;els.turnLabel.textContent=state.turn==="player"?p.name:e.name;els.movementInfo.textContent=`Movimentos: ${state.turn==="player"?state.moveLeft:0}`;$("battlePlayerTurn").textContent=state.turn==="player"?"Seu turno":"Aguardando";$("battleEnemyTurn").textContent=state.turn==="enemy"?"IA usando ações":"IA instantânea";$("actionBasicState").textContent=state.actions.basic?"Usado":"Disponível";$("actionRaceState").textContent=state.actions.race?"Usada":"Disponível";$("actionClassState").textContent=state.actions.class?"Usada":"Disponível";els.defend.disabled=state.turn!=="player"||state.defendCooldown>0||state.actedThisTurn;els.defend.textContent=state.defendCooldown>0?`Defender — recarga ${state.defendCooldown}`:state.actedThisTurn?"Defender — apenas como primeira ação":"Defender próximo dano"}
  function reachable(origin,steps){const s=new Set();for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++){const d=manhattan(origin,{x,y});if(d>0&&d<=steps&&!(x===state.enemy.x&&y===state.enemy.y))s.add(`${x},${y}`)}return s}
  function inRange(origin,range){const s=new Set();for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++){const d=manhattan(origin,{x,y});if(d>0&&d<=range)s.add(`${x},${y}`)}return s}
  function unitHp(unit){return`<span class="unit-hp"><i style="width:${Math.max(0,unit.hp/unit.hpMax*100)}%"></i></span>`}
  function unitFx(side){const fx=state.damageFx[side];return fx?`<span class="arena-damage-number">-${esc(fx)}</span>`:""}
  function renderGrid(){const moveSet=state.turn==="player"&&!state.selectedAction?reachable(state.player,state.moveLeft):new Set(),rangeSet=state.turn==="player"&&state.selectedAction&&state.selectedAction.target!=="self"?inRange(state.player,state.selectedAction.range):new Set();let html="";for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++){const key=`${x},${y}`,isP=x===state.player.x&&y===state.player.y,isE=x===state.enemy.x&&y===state.enemy.y,cls=["arena-cell"];if(moveSet.has(key))cls.push("can-move");if(rangeSet.has(key))cls.push("in-range");if(isE&&rangeSet.has(key))cls.push("targetable");if(isP&&state.damageFx.player)cls.push("arena-unit-hit");if(isE&&state.damageFx.enemy)cls.push("arena-unit-hit");html+=`<button type="button" class="${cls.join(" ")}" data-x="${x}" data-y="${y}">${isP?`${unitFx("player")}${unitHp(state.player)}<img src="${esc(state.player.image)}" alt="${esc(state.player.name)}"><span class="unit">${esc(state.player.name)}</span>`:isE?`${unitFx("enemy")}${unitHp(state.enemy)}<span class="dummy-unit">✦</span><span class="unit">${esc(state.enemy.name)}</span>`:""}</button>`}els.grid.innerHTML=html}
  function flashDamage(side,amount){state.damageFx[side]=Math.max(0,Math.round(Number(amount)||0));renderGrid();setTimeout(()=>{state.damageFx[side]=null;if(state.started)renderGrid()},750)}
  function renderAll(){if(!state.started)return;renderHeader();renderGrid();renderSkills();ensurePassivePanel()}
  function calculateDamage(attacker,target,action){let mult=(attacker.mod?.damageOut||1)*(action.type==="magical"?(attacker.mod?.magicalOut||1):(attacker.mod?.physicalOut||1));if(attacker.mod?.execute&&target.hp/target.hpMax<.3)mult*=1+attacker.mod.execute;const raw=Math.max(0,Math.round(Number(attacker.attrs[action.attr]||0)*(action.scale/100)*mult)),info=defense?.breakdown({def:target.attrs.DEF,res:target.attrs.RES})||{},reduction=action.type==="magical"?(info.magicalReduction??Math.min(75,Math.floor(target.attrs.RES/5))):(info.physicalReduction??Math.min(75,Math.floor(target.attrs.DEF/5)));let final=Math.max(0,Math.round(raw*(1-reduction/100)*(target.mod?.damageIn||1)));if(target.mod?.shield>0){const blocked=Math.min(final,target.mod.shield);target.mod.shield-=blocked;final-=blocked;if(blocked)log(`${target.name} absorveu <strong>${blocked}</strong> com um escudo passivo.`)}return{raw,reduction,final}}
  function applySelfAction(unit,action,cooldowns,side){unit.mana-=action.cost;if(action.healing){const amount=Math.max(1,Math.round(Number(unit.attrs[action.attr]||0)*action.scale/100*(unit.mod?.healOut||1)));unit.hp=Math.min(unit.hpMax,unit.hp+amount);log(`${unit.name} usa <strong>${esc(action.name)}</strong> e recupera <strong>${amount} HP</strong>.`)}else if(action.shield){const amount=Math.max(1,Math.round(Number(unit.attrs[action.attr]||0)*action.scale/100));unit.mod.shield=(unit.mod.shield||0)+amount;log(`${unit.name} usa <strong>${esc(action.name)}</strong> e recebe <strong>${amount}</strong> de escudo.`)}else log(`${unit.name} ativa <strong>${esc(action.name)}</strong>.`);if(action.cooldown>0)cooldowns[action.id]=action.cooldown;if(side==="player"){state.actions[action.source]=true;state.actedThisTurn=true;state.selectedAction=null}}
  function usePlayerAction(action){if(state.turn!=="player"||state.actions[action.source]||Number(state.cooldowns[action.id]||0)>0)return;if(state.player.mana<action.cost){log(`Mana insuficiente para <strong>${esc(action.name)}</strong>.`);return}if(action.target==="self"){applySelfAction(state.player,action,state.cooldowns,"player");renderAll();return}if(manhattan(state.player,state.enemy)>action.range){log(`<strong>${esc(action.name)}</strong> está fora de alcance.`);return}const dmg=calculateDamage(state.player,state.enemy,action);state.player.mana-=action.cost;if(state.enemy.defending){log(`${state.enemy.name} bloqueou 100% do dano.`);state.enemy.defending=false}else{state.enemy.hp=Math.max(0,state.enemy.hp-dmg.final);flashDamage("enemy",dmg.final)}state.actions[action.source]=true;state.actedThisTurn=true;if(action.cooldown>0)state.cooldowns[action.id]=action.cooldown;state.selectedAction=null;log(`${state.player.name} usa <strong>${esc(action.name)}</strong> e causa <strong>${dmg.final}</strong> de dano.`);renderAll();if(state.enemy.hp<=0)finish("victory",`${state.enemy.name} foi derrotado.`)}
  function movePlayer(x,y){const d=manhattan(state.player,{x,y});if(d<1||d>state.moveLeft)return;state.player.x=x;state.player.y=y;state.moveLeft-=d;state.actedThisTurn=true;log(`${state.player.name} moveu ${d} casa(s).`);renderAll()}
  function moveToward(unit,target,steps,desiredRange=1){while(steps-->0&&manhattan(unit,target)>desiredRange){if(unit.x<target.x)unit.x++;else if(unit.x>target.x)unit.x--;else if(unit.y<target.y)unit.y++;else if(unit.y>target.y)unit.y--}}
  function chooseEnemyAction(actions,source){const dist=manhattan(state.enemy,state.player),ready=actions.filter(a=>a.source===source&&!state.enemyCooldowns[a.id]&&state.enemy.mana>=a.cost&&(a.target==="self"||dist<=a.range));if(!ready.length)return null;return ready.sort((a,b)=>{const score=x=>(x.healing?(state.enemy.hp/state.enemy.hpMax<.55?500:10):0)+(x.shield?180:0)+(x.target==="self"?80:0)+x.scale*3-x.cost;return score(b)-score(a)})[0]}
  function enemyUse(action){if(!action)return false;if(action.target==="self"){applySelfAction(state.enemy,action,state.enemyCooldowns,"enemy");return true}const dmg=calculateDamage(state.enemy,state.player,action);state.enemy.mana-=action.cost;if(state.player.defending){log(`${state.player.name} bloqueou 100% do dano.`);state.player.defending=false}else{state.player.hp=Math.max(0,state.player.hp-dmg.final);flashDamage("player",dmg.final)}if(action.cooldown>0)state.enemyCooldowns[action.id]=action.cooldown;log(`${state.enemy.name} usa <strong>${esc(action.name)}</strong> e causa <strong>${dmg.final}</strong> de dano.`);return true}
  function startTimer(){clearInterval(state.timerId);state.timer=60;els.timer.textContent=60;state.timerId=setInterval(()=>{if(!state.started||state.turn!=="player")return;state.timer--;els.timer.textContent=state.timer;if(state.timer<=0){clearInterval(state.timerId);state.roundMiss.player=true;enemyTurn(true)}},1000)}
  function enemyTurn(playerMiss=false){if(!state.started)return;state.turn="enemy";clearInterval(state.timerId);renderAll();setTimeout(()=>{if(!state.started)return;const groups=enemyActionData(),all=[...groups.class,...groups.race,...groups.basic],maxRange=Math.max(1,...all.filter(a=>a.target!=="self"&&state.enemy.mana>=a.cost&&!state.enemyCooldowns[a.id]).map(a=>a.range));moveToward(state.enemy,state.player,movementFromIni(state.enemy.attrs.INI),maxRange);let acted=false;const classAction=chooseEnemyAction(groups.class,"class"),raceAction=chooseEnemyAction(groups.race,"race"),basicAction=chooseEnemyAction(groups.basic,"basic");if(state.enemy.hp/state.enemy.hpMax<.35){if(classAction&&(classAction.healing||classAction.shield))acted=enemyUse(classAction)||acted;if(raceAction&&(raceAction.healing||raceAction.shield))acted=enemyUse(raceAction)||acted}if(state.started&&state.player.hp>0&&classAction&&!classAction.healing&&!classAction.shield)acted=enemyUse(classAction)||acted;if(state.started&&state.player.hp>0&&raceAction&&!raceAction.healing&&!raceAction.shield)acted=enemyUse(raceAction)||acted;if(state.started&&state.player.hp>0&&basicAction)acted=enemyUse(basicAction)||acted;if(!acted&&state.enemy.hp/state.enemy.hpMax<.3){state.enemy.defending=true;acted=true;log(`${state.enemy.name} assume postura defensiva.`)}state.roundMiss.enemy=!acted;renderAll();if(state.player.hp<=0){finish("defeat",`${state.player.name} foi derrotado.`);return}if(playerMiss&&!acted){finish("draw","Os dois combatentes perderam suas ações na mesma rodada.");return}beginPlayerTurn()},420)}
  function reduceCooldownMap(map){Object.keys(map).forEach(k=>{map[k]=Math.max(0,map[k]-1);if(!map[k])delete map[k]})}
  function beginPlayerTurn(){state.turn="player";state.round++;state.actions={basic:false,race:false,class:false};state.selectedAction=null;state.moveLeft=movementFromIni(state.player.attrs.INI);state.actedThisTurn=false;state.roundMiss={player:false,enemy:false};if(state.defendCooldown>0)state.defendCooldown--;reduceCooldownMap(state.cooldowns);reduceCooldownMap(state.enemyCooldowns);renderAll();startTimer()}
  function finish(type,text){state.started=false;clearInterval(state.timerId);renderHeader();renderGrid();renderSkills();els.outcome.hidden=false;els.outcome.className=`arena-outcome ${type}`;els.outcomeEyebrow.textContent="Resultado do combate";els.outcomeTitle.textContent=type==="victory"?"Vitória":type==="defeat"?"Derrota":"Empate";els.outcomeText.textContent=text}
  async function loadCharacters(){const current=await account.current().catch(()=>null);if(!current){window.location.replace("conta.html");return}const chars=await account.getCharacters().catch(()=>[]);state.characters=Array.isArray(chars)?chars:[];els.character.innerHTML=state.characters.length?state.characters.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} • Nível ${esc(c.level||1)}</option>`).join(""):'<option value="">Nenhum personagem disponível</option>';els.start.disabled=!state.characters.length;if(state.characters.length)await loadCharacter(state.characters[0].id)}
  async function loadCharacter(id){if(!id)return;els.message.textContent="Carregando personagem...";const sheet=await account.getCharacterSheet(id);state.sheet=sheet;state.character=sheet.character;const base=baseAttributes(sheet.attributes),bonus=equipmentBonus(sheet.equipment);state.attrs=Object.fromEntries(attrs.map(a=>[a,(base[a]||0)+(bonus[a]||0)]));state.race=(window.WONDERLAND_RACES||[]).find(r=>r.id===sheet.character.race_id);state.cls=(window.WONDERLAND_CLASSES||{})[sheet.character.class_id];state.path=resolvePath(state.cls,sheet.character);state.skills=officialSkills(state.cls,Number(sheet.character.level||1),state.path);state.raceSkills=officialRaceSkills(state.race,Number(sheet.character.level||1));state.passives.player=collectPassives(state.cls,state.race,state.path);renderSetup();els.message.textContent=`Pronto: ${state.skills.length} habilidade(s) de classe, ${state.raceSkills.length} racial(is) e ${state.passives.player.length} passiva(s).`}
  function startBattle(){if(!state.sheet)return;const dummy=randomizeDummy(),pHp=hpMaxFor(state.attrs,state.race),pMana=manaMaxFor(state.attrs,state.race);state.player={name:state.character.name,image:state.character.image_url||state.race?.artwork||state.race?.image||"assets/images/logo.png",attrs:{...state.attrs},hp:pHp,hpMax:pHp,mana:pMana,manaMax:pMana,x:2,y:Math.floor(GRID_H/2),defending:false};state.enemy={name:"Boneco de Teste",attrs:{...dummy.attrs},hp:dummy.hpMax,hpMax:dummy.hpMax,mana:dummy.manaMax,manaMax:dummy.manaMax,x:GRID_W-3,y:Math.floor(GRID_H/2),defending:false,raceName:dummy.race,className:dummy.className,pathName:dummy.pathName};state.passives.enemy=collectPassives(dummy.classData,dummy.raceData,dummy.pathData);compilePassives(state.player,state.passives.player);compilePassives(state.enemy,state.passives.enemy);state.started=true;state.turn="player";state.round=1;state.actions={basic:false,race:false,class:false};state.selectedAction=null;state.moveLeft=movementFromIni(state.player.attrs.INI);state.defendCooldown=0;state.cooldowns={};state.enemyCooldowns={};state.actedThisTurn=false;state.roundMiss={player:false,enemy:false};state.log=[];state.damageFx={player:null,enemy:null};els.outcome.hidden=true;els.setup.hidden=true;els.battle.hidden=false;log(`Combate iniciado contra ${state.enemy.raceName} / ${state.enemy.className}${state.enemy.pathName!=="Sem Caminho"?` / ${state.enemy.pathName}`:""}.`);log(`Passivas do jogador: <strong>${esc(passiveSummary(state.player))}</strong>.`);log(`Passivas do Boneco: <strong>${esc(passiveSummary(state.enemy))}</strong>.`);renderAll();startTimer()}
  els.character.addEventListener("change",()=>loadCharacter(els.character.value).catch(e=>{console.error(e);els.message.textContent=e.message||"Falha ao carregar personagem."}));els.start.addEventListener("click",startBattle);els.grid.addEventListener("click",e=>{if(!state.started||state.turn!=="player")return;const cell=e.target.closest("[data-x]");if(!cell)return;const x=Number(cell.dataset.x),y=Number(cell.dataset.y);if(x===state.enemy.x&&y===state.enemy.y&&state.selectedAction){usePlayerAction(state.selectedAction);return}if(!state.selectedAction)movePlayer(x,y)});els.skillCards.addEventListener("click",e=>{const b=e.target.closest("[data-action-id]");if(!b||b.disabled)return;const a=allPlayerActions().find(x=>x.id===b.dataset.actionId);if(!a)return;if(a.target==="self"){usePlayerAction(a);return}state.selectedAction=state.selectedAction?.id===a.id?null:a;renderAll()});els.endTurn.addEventListener("click",()=>{if(state.started&&state.turn==="player")enemyTurn(false)});els.defend.addEventListener("click",()=>{if(state.turn!=="player"||state.defendCooldown>0||state.actedThisTurn)return;state.player.defending=true;state.defendCooldown=5;state.actions={basic:true,race:true,class:true};state.moveLeft=0;state.actedThisTurn=true;log(`${state.player.name} entrou em defesa.`);renderAll();enemyTurn(false)});els.reset.addEventListener("click",()=>{state.started=false;clearInterval(state.timerId);els.battle.hidden=true;els.setup.hidden=false;els.message.textContent="Teste encerrado."});els.outcomeAgain.addEventListener("click",()=>{els.outcome.hidden=true;els.battle.hidden=true;els.setup.hidden=false;renderSetup()});
  await loadCharacters();
})();