"use strict";

const classesList = document.getElementById("classesList");
const classContent = document.getElementById("classContent");
let classes = {};
let currentClass = null;
let activeTab = "overview";

const CLASS_ORDER = ["barbaro","alquimista","arqueiro","assassino","bardo","bruxo","druida","espadachim","feiticeiro","mago","ninja","necromante","guerreiro"];
const ATTRIBUTES = ["FOR","DEF","RES","INI","INT","ARC"];
const PATH_LEVELS = [60,70,80,90,100];
const ATTRIBUTE_THEMES = {
 FOR:{accent:"#e56a3d",rgb:"229,106,61",secondary:"#d8a04d",secondaryRgb:"216,160,77"},
 DEF:{accent:"#4f8fd8",rgb:"79,143,216",secondary:"#7bb4e8",secondaryRgb:"123,180,232"},
 RES:{accent:"#43b77a",rgb:"67,183,122",secondary:"#82cf9f",secondaryRgb:"130,207,159"},
 INI:{accent:"#d5aa38",rgb:"213,170,56",secondary:"#f0cf67",secondaryRgb:"240,207,103"},
 INT:{accent:"#865dd4",rgb:"134,93,212",secondary:"#b08bea",secondaryRgb:"176,139,234"},
 ARC:{accent:"#35b7bd",rgb:"53,183,189",secondary:"#70d7d2",secondaryRgb:"112,215,210"}
};
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");

function getPrimaryAttribute(c){const a=String(c?.estilo?.atributos||"").toUpperCase(),r=String(c?.cargo||"").toLowerCase();if(r.includes("suporte")||r.includes("invocador"))return"ARC";if(r.includes("mágico")||r.includes("magico"))return"INT";if(r.includes("assassino"))return"INI";if(r.includes("tanque")&&!r.includes("dps"))return"DEF";return ATTRIBUTES.find(x=>a.startsWith(x)||a.includes(`${x} PRINCIPAL`))||"FOR"}
function getClassTheme(c){return ATTRIBUTE_THEMES[getPrimaryAttribute(c)]||ATTRIBUTE_THEMES.FOR}
function applyClassTheme(c){const t=getClassTheme(c),s=document.documentElement.style;s.setProperty("--classes-red",t.accent);s.setProperty("--classes-red-rgb",t.rgb);s.setProperty("--classes-gold",t.secondary);s.setProperty("--classes-gold-rgb",t.secondaryRgb);document.body.dataset.classTheme=getPrimaryAttribute(c).toLowerCase()}
function stars(value){const filled=(String(value||"").match(/★/g)||[]).length;return `<span class="rating-stars-inline" aria-label="${filled} de 5 estrelas">${Array.from({length:5},(_,i)=>`<span class="rating-star-inline ${i<filled?"filled":"empty"}">★</span>`).join("")}</span>`}
function getSkillCost(skill,level,options={}){return window.WONDERLAND_SKILL_COSTS?.infer(currentClass,skill,level,options)||{label:"Sem custo"}}

function createSidebar(){classesList.innerHTML="";const ordered=CLASS_ORDER.map(id=>classes[id]).filter(Boolean);ordered.forEach(c=>{const t=getClassTheme(c),b=document.createElement("button");b.type="button";b.className="class-button";b.dataset.id=c.id;b.style.setProperty("--item-accent",t.accent);b.style.setProperty("--item-accent-rgb",t.rgb);b.innerHTML=`<span class="class-icon class-icon-symbol" aria-hidden="true" style="color:${t.accent};border-color:rgba(${t.rgb},.42);background:radial-gradient(circle,rgba(${t.rgb},.20),rgba(5,11,13,.94))">${esc(c.icone||"✦")}</span><div class="class-info"><span class="class-name">${esc(c.nome)}</span><span class="class-role">${esc(c.cargo)}</span></div>`;classesList.appendChild(b)});const p=document.querySelector(".classes-index-heading p");if(p)p.textContent=`${ordered.length} classes oficiais. Escolha uma para consultar seu estilo de combate e progressão.`}

function loadClass(id){const next=classes[id];if(!next)return;currentClass=next;activeTab="overview";applyClassTheme(next);document.querySelectorAll(".class-button").forEach(b=>b.classList.toggle("active",b.dataset.id===id));renderClass()}
function renderClass(){const c=currentClass,p=getPrimaryAttribute(c);classContent.innerHTML=`<div class="class-header"><div class="class-image"><img loading="lazy" decoding="async" src="${esc(c.imagem)}" alt="${esc(c.nome)}"></div><div><span class="class-kicker">${esc(c.cargo)}</span><h1 class="class-title">${esc(c.nome)}</h1><div class="class-stars"><span class="rating-label">Dificuldade</span>${stars(c.dificuldade)}</div><p class="class-description">${esc(c.descricao)}</p><div class="class-path-meta"><strong>${esc(p)} principal</strong><small>${esc(c.recurso?.nome||"Mecânica própria")}</small></div></div></div>${renderAffinityPanel()}<nav class="class-tabs" aria-label="Informações da classe"><button class="class-tab ${activeTab==="overview"?"active":""}" data-tab="overview" type="button">✦ Visão Geral</button><button class="class-tab ${activeTab==="skills"?"active":""}" data-tab="skills" type="button">⚔ Habilidades</button><button class="class-tab ${activeTab==="paths"?"active":""}" data-tab="paths" type="button">▲ Caminhos</button></nav><section class="class-tab-content">${renderActiveTab()}</section>`;const img=classContent.querySelector(".class-image img");if(img)img.addEventListener("error",()=>{img.src="assets/images/logo.png";img.classList.add("fallback")},{once:true})}
function renderAffinityPanel(){const a=currentClass.afinidades||{},p=getPrimaryAttribute(currentClass);return `<section class="class-affinity-panel"><div class="class-affinity-grid">${ATTRIBUTES.map(x=>`<article class="class-affinity-card ${x===p?"primary":""}"><span>${x}</span>${stars(a[x]||"☆☆☆☆☆")}</article>`).join("")}</div></section>`}
function renderActiveTab(){if(activeTab==="skills")return renderProgressao();if(activeTab==="paths")return renderCaminhos();return renderOverviewTab()}
function row(l,v){return `<div class="playstyle-row"><span>${esc(l)}</span><strong>${esc(v||"—")}</strong></div>`}
function renderOverviewTab(){const c=currentClass;return `<div class="overview-grid"><article class="class-highlight-card"><span>Especialização</span><h2>${esc(c.especializacao?.titulo||c.cargo)}</h2><p>${esc(c.especializacao?.descricao||c.descricao)}</p></article><aside class="class-playstyle-card">${row("Função principal",c.estilo?.principal)}${row("Mecânica exclusiva",c.recurso?.nome)}${row("Pontos fortes",c.estilo?.fortes)}${row("Pontos fracos",c.estilo?.fracos)}${row("Atributos centrais",c.estilo?.atributos)}</aside></div>${c.recurso?`<section class="class-resource-card"><span>Mecânica da Classe</span><h2>${esc(c.recurso.nome)}</h2><p>${esc(c.recurso.descricao)}</p></section>`:""}${c.passivas?.length?`<section class="class-section-block"><header class="class-section-heading"><span>Característica permanente</span><h2>Passiva da Classe</h2></header><div class="class-passive-grid">${c.passivas.map(p=>`<article class="passive-card"><h3>${esc(p.nome)}</h3><p>${esc(p.descricao)}</p><span class="class-skill-cost">Custo: Sem custo</span></article>`).join("")}</div></section>`:""}`}
function renderProgressao(){const skills=currentClass.progressao||[];return `<section class="class-progression-section"><header class="class-section-heading"><span>Arsenal da Classe</span><h2>Habilidades — níveis 1 a 50</h2></header><div class="class-skill-list">${skills.map((s,i)=>skillCard(s,String(s.nivel).replace(/\D/g,"")||i+1,i===0)).join("")}</div></section>`}
function skillCard(s,level,open=false,ultimate=false,path=false){const cost=getSkillCost(s,Number(level)||1,{ultimate,path});return `<details class="class-skill-card ${ultimate?"ultimate":""}" ${open?"open":""}><summary class="class-skill-summary"><span class="class-skill-level">Nível<br><strong>${esc(level)}</strong></span><span class="class-skill-title-wrap"><small>${esc(ultimate?"Poder Supremo":s.categoria||"Habilidade")}</small><strong>${esc(s.nome)}</strong><em class="class-skill-cost">Custo: ${esc(cost.label)}</em></span><span class="class-skill-toggle" aria-hidden="true">＋</span></summary><div class="class-skill-body"><p>${esc(s.descricao)}</p><div class="class-skill-cost-detail"><strong>Custo</strong><span>${esc(cost.label)}</span></div></div></details>`}
function renderCaminhos(){const paths=currentClass.caminhos||[];if(!paths.length)return `<div class="class-empty-state"><strong>Nenhum Caminho registrado.</strong></div>`;return `<section class="class-paths-section"><header class="class-section-heading"><span>Especializações de nível 50</span><h2>Caminhos de ${esc(currentClass.nome)}</h2></header><div class="class-path-selector">${paths.map((p,i)=>`<button class="class-path-selector-button ${i===0?"active":""}" type="button" data-path-index="${i}"><span>Caminho ${i+1}</span><strong>${esc(p.nome)}</strong></button>`).join("")}</div><div id="classPathView">${renderSinglePath(paths[0],0)}</div></section>`}
function renderSinglePath(path,index){return `<article class="class-path-card"><header class="class-path-header"><span>Caminho ${index+1}</span><h3>${esc(path.nome)}</h3><div class="class-path-meta"><strong>${esc(path.especializacao)}</strong><small>Complexidade: ${esc(path.complexidade)}</small></div><p>${esc(path.descricao)}</p></header><section class="class-path-passive"><span>Nível 50 • Nova Passiva</span><h4>${esc(path.passiva?.nome)}</h4><div>${esc(path.passiva?.descricao)}</div><small class="class-skill-cost">Custo: Sem custo</small></section><div class="class-skill-list class-path-progression">${(path.habilidades||[]).map((h,i)=>skillCard(h,PATH_LEVELS[i]||100,i===0,String(h.tipo).toLowerCase()==="ultimate",true)).join("")}</div></article>`}

classContent.addEventListener("click",event=>{const tab=event.target.closest(".class-tab");if(tab){activeTab=tab.dataset.tab||"overview";renderClass();return}const pathButton=event.target.closest(".class-path-selector-button");if(pathButton){const i=Number(pathButton.dataset.pathIndex),view=document.getElementById("classPathView");if(!Number.isNaN(i)&&view&&currentClass.caminhos?.[i]){classContent.querySelectorAll(".class-path-selector-button").forEach(b=>b.classList.toggle("active",b===pathButton));view.innerHTML=renderSinglePath(currentClass.caminhos[i],i)}}});
classesList.addEventListener("click",event=>{const button=event.target.closest(".class-button");if(button)loadClass(button.dataset.id)});

function initializeClasses(){classes=window.WONDERLAND_CLASSES||{};const first=CLASS_ORDER.find(id=>classes[id]);if(!first){classContent.innerHTML='<div class="class-empty-state"><strong>Não foi possível carregar as classes.</strong></div>';return}createSidebar();loadClass(first)}
initializeClasses();
