"use strict";
(async function(){
  const account=window.WONDERLAND_ACCOUNT;
  const client=window.WONDERLAND_SUPABASE;
  const localItems=Array.isArray(window.WONDERLAND_SHOP_ITEMS)?window.WONDERLAND_SHOP_ITEMS:[];
  const slots=window.WONDERLAND_ITEM_SLOTS||{};
  const grid=document.getElementById("shopGrid"),status=document.getElementById("shopStatus"),count=document.getElementById("shopCount"),search=document.getElementById("shopSearch"),slotFilter=document.getElementById("shopSlot"),rarityFilter=document.getElementById("shopRarity"),dialog=document.getElementById("shopDialog"),form=document.getElementById("shopPurchaseForm"),characterSelect=document.getElementById("shopCharacter"),balance=document.getElementById("shopCharacterBalance"),title=document.getElementById("shopDialogTitle"),description=document.getElementById("shopDialogDescription"),message=document.getElementById("shopDialogMessage"),cancel=document.getElementById("shopCancel"),confirm=document.getElementById("shopConfirm");
  let characters=[],items=[],selectedItem=null;
  const esc=value=>String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
  const format=value=>new Intl.NumberFormat("pt-BR").format(Number(value)||0);
  const normalize=value=>String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();
  const rarityColors={Comum:"#b9b3a8",Incomum:"#66c783",Raro:"#4ca7ff",Épico:"#a86cff",Lendário:"#f0b84d",Mítico:"#ff596f"};
  const dbToItem=row=>({
    id:row.item_key||row.id,name:row.name,slot:row.slot,rarity:row.rarity||"Comum",price:Number(row.price_wg||0),
    stats:{FOR:Number(row.for_bonus||0),DEF:Number(row.def_bonus||0),RES:Number(row.res_bonus||0),INI:Number(row.ini_bonus||0),INT:Number(row.int_bonus||0),ARC:Number(row.arc_bonus||0)},
    image:row.image_url||null,icon:row.icon_url||"◆",description:row.description||"",twoHanded:Boolean(row.two_handed),occupiesBoth:Boolean(row.occupy_two_slots),active:row.active_shop!==false,required_level:Number(row.required_level||1),_dbId:row.id
  });
  const statsText=item=>Object.entries(item.stats||{}).filter(([,value])=>Number(value)).map(([key,value])=>`${key} +${value}`);
  function mergeItems(dbRows){
    const db=(dbRows||[]).map(dbToItem),used=new Set(),merged=db.map(item=>{const i=localItems.findIndex((local,index)=>!used.has(index)&&(local.id===item.id||normalize(local.name)===normalize(item.name)));if(i>=0)used.add(i);return item});
    localItems.forEach((item,index)=>{if(!used.has(index))merged.push({...item})});
    return merged.sort((a,b)=>String(a.name).localeCompare(String(b.name),"pt-BR"));
  }
  if(!account||!client){window.location.replace("conta.html");return}
  const user=await account.current().catch(()=>null);if(!user){window.location.replace("conta.html");return}
  try{characters=await account.getCharacters()}catch(error){console.error(error)}
  try{const {data,error}=await client.from("items").select("*").eq("active_shop",true).order("name",{ascending:true});if(error)throw error;items=mergeItems(data||[])}catch(error){console.error(error);items=[...localItems];status.textContent="Catálogo local carregado. As alterações do painel exigem a migração SQL mais recente."}
  [...new Set(items.map(item=>item.slot).filter(Boolean))].forEach(slot=>slotFilter.insertAdjacentHTML("beforeend",`<option value="${esc(slot)}">${esc(slots[slot]||slot)}</option>`));
  [...new Set(items.map(item=>item.rarity).filter(Boolean))].forEach(rarity=>rarityFilter.insertAdjacentHTML("beforeend",`<option value="${esc(rarity)}">${esc(rarity)}</option>`));
  function render(){
    const term=normalize(search.value),slot=slotFilter.value,rarity=rarityFilter.value;
    const filtered=items.filter(item=>item.active!==false).filter(item=>slot==="all"||item.slot===slot).filter(item=>rarity==="all"||item.rarity===rarity).filter(item=>!term||normalize(`${item.name} ${item.slot} ${item.rarity} ${statsText(item).join(" ")}`).includes(term));
    count.textContent=String(filtered.length);status.textContent=`${filtered.length} item(ns) disponíveis. Alterações salvas no painel são aplicadas aqui pelo Supabase.`;
    grid.innerHTML=filtered.length?filtered.map(item=>{const color=rarityColors[item.rarity]||rarityColors.Comum,handText=item.twoHanded?"Arma de duas mãos — ocupa os dois slots":item.occupiesBoth?"Conjunto duplo — ocupa os dois slots de arma":"";return `<article class="shop-item-card${item.testItem?" shop-item-card-test":""}" style="--rarity:${color}"><div class="shop-item-visual">${item.image?`<img src="${esc(item.image)}" alt="${esc(item.name)}">`:`<span class="shop-item-icon">${esc(item.icon||"◆")}</span>`}<span class="shop-rarity-orbit"></span></div><div class="shop-item-body"><div class="shop-item-kicker"><span>${esc(item.rarity)}</span><span>${esc(slots[item.slot]||item.slot)}</span></div><h2>${esc(item.name)}</h2><p class="shop-item-slot">${esc(item.description||`Equipamento ${String(item.rarity||"comum").toLowerCase()} do mercado de Wonderland.`)}</p><div class="shop-item-stats">${statsText(item).map(stat=>`<span>${esc(stat)}</span>`).join("")||"<span>Sem bônus</span>"}</div><div class="shop-item-warning">${esc(handText)}</div><div class="shop-item-footer"><div class="shop-item-price"><small>Preço</small><strong>${format(item.price)} WG</strong></div><button type="button" class="wl-button wl-button-gold" data-buy-item="${esc(item.id)}">Comprar</button></div></div></article>`}).join(""):'<div class="shop-empty">Nenhum item encontrado com estes filtros.</div>';
    grid.querySelectorAll("[data-buy-item]").forEach(button=>button.addEventListener("click",()=>openPurchase(button.dataset.buyItem)));
  }
  function refreshCharacterOptions(){characterSelect.innerHTML=characters.length?characters.map(character=>`<option value="${esc(character.id)}">${esc(character.name)} — ${format(character.wg)} WG</option>`).join(""):'<option value="">Nenhum personagem disponível</option>';characterSelect.disabled=!characters.length;confirm.disabled=!characters.length;updateBalance()}
  function updateBalance(){const character=characters.find(item=>item.id===characterSelect.value);if(!character||!selectedItem){balance.textContent="Selecione um personagem.";return}const enough=Number(character.wg)>=Number(selectedItem.price);balance.innerHTML=`Saldo de <strong>${esc(character.name)}</strong>: <strong>${format(character.wg)} WG</strong><br>Após a compra: <strong>${enough?format(character.wg-selectedItem.price):"saldo insuficiente"}</strong>${enough?" WG":""}`;confirm.disabled=!enough}
  function openPurchase(itemId){selectedItem=items.find(item=>String(item.id)===String(itemId));if(!selectedItem)return;title.textContent=selectedItem.name;description.textContent=`${selectedItem.rarity} • ${slots[selectedItem.slot]||selectedItem.slot} • ${format(selectedItem.price)} WG`;message.textContent="";message.classList.remove("error");refreshCharacterOptions();dialog.showModal()}
  characterSelect.addEventListener("change",updateBalance);cancel.addEventListener("click",()=>dialog.close());
  form.addEventListener("submit",async event=>{event.preventDefault();if(!selectedItem)return;const character=characters.find(item=>item.id===characterSelect.value);if(!character)return;confirm.disabled=true;message.textContent="Processando compra...";message.classList.remove("error");try{const {data,error}=await client.rpc("purchase_shop_item",{p_character_id:character.id,p_item_key:selectedItem.id,p_name:selectedItem.name,p_slot:selectedItem.slot,p_rarity:selectedItem.rarity,p_price_wg:selectedItem.price,p_stats:selectedItem.stats||{},p_icon:selectedItem.icon||null,p_image_url:selectedItem.image||null,p_two_handed:Boolean(selectedItem.twoHanded),p_occupies_both_hands:Boolean(selectedItem.occupiesBoth)});if(error)throw error;character.wg=Number(data?.new_balance??character.wg-selectedItem.price);message.textContent=`Compra concluída. ${selectedItem.name} foi enviado ao inventário de ${character.name}.`;refreshCharacterOptions();setTimeout(()=>dialog.close(),1100)}catch(error){console.error(error);message.textContent=error.message||"Não foi possível concluir a compra.";message.classList.add("error");updateBalance()}});
  [search,slotFilter,rarityFilter].forEach(control=>control.addEventListener(control===search?"input":"change",render));refreshCharacterOptions();render();
})();