create or replace function public._v2_rework_skill_list(
  p_specs jsonb,
  p_levels integer[],
  p_attr_one text,
  p_attr_two text,
  p_damage_type text,
  p_resource_max integer
) returns jsonb
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_result jsonb := '[]'::jsonb;
  v_spec jsonb;
  v_index integer := 0;
begin
  for v_spec in select value from jsonb_array_elements(p_specs)
  loop
    v_index := v_index + 1;
    v_result := v_result || jsonb_build_array(
      public._v2_rework_skill(
        v_spec->>0,
        p_levels[v_index],
        v_spec->>1,
        v_spec->>2,
        p_attr_one,
        p_attr_two,
        p_damage_type,
        p_resource_max
      )
    );
  end loop;
  return v_result;
end;
$$;

revoke all on function public._v2_rework_skill_list(jsonb,integer[],text,text,text,integer) from public, anon, authenticated;

do $$
declare
  v_catalog jsonb := $catalog$
[
  {"name":"Alquimista","attrs":["INT","ARC"],"dtype":"magic","description":"Especialista em reagentes, transmutação e suporte adaptativo. Alterna explosões, enfraquecimentos e fórmulas de emergência conforme a situação.","mechanic":{"name":"Catalisadores","description":"Variar entre dano, suporte e controle alimenta Catalisadores para técnicas avançadas."},"passive":{"name":"Reação em Cadeia","description":"Alternar a categoria das técnicas recompensa o Alquimista com um fluxo de combate mais eficiente."},"base":[["Frasco Volátil","D","Arremessa um composto instável que causa dano mágico concentrado."],["Reagente Corrosivo","DX","Causa dano e corrói as defesas do inimigo por 2 turnos."],["Névoa Catalítica","A3","Espalha uma nuvem alquímica que atinge até 3 inimigos."],["Elixir de Emergência","H","Escolha um aliado e restaure sua vida com um reagente de ação imediata."],["Tônico de Combate","B","Escolha um aliado e aumente seu poder e iniciativa por 2 turnos."],["Destilação Instável","DC","Causa dano e rompe a concentração do alvo."],["Grande Reação","A4","Combina reagentes em uma reação devastadora contra até 4 inimigos."]],"paths":[{"key":"cirurgiao-quimico","skills":[["Sutura Alquímica","H","Escolha um aliado e feche seus ferimentos com uma mistura regenerativa."],["Pele Mutagênica","S","Escolha um aliado e cubra-o com uma película que absorve dano."],["Antídoto Universal","P","Escolha um aliado, remova um efeito negativo e recupere sua vida."],["Transfusão Catalítica","HS","Escolha um aliado para receber cura e proteção alquímica."],["Panaceia Suprema","HA4","Libera a fórmula máxima e cura até 4 aliados."]]},{"key":"mestre-transmutador","skills":[["Mercúrio Bélico","DX","Transmuta matéria em metal líquido, causando dano e enfraquecendo o alvo."],["Ouro Falso","X","Altera a estrutura do inimigo e reduz suas defesas."],["Prisma de Transmutação","A3","Fratura matéria e energia para atingir até 3 inimigos."],["Conversão Violenta","T","Converte estabilidade em colapso e causa dano verdadeiro."],["Magnum Opus","A4","Executa a obra-prima da transmutação contra até 4 inimigos."]]}]},
  {"name":"Arqueiro","attrs":["FOR","INI"],"dtype":"physical","description":"Combatente de precisão que marca alvos, administra ritmo e alterna execução individual com pressão em área.","mechanic":{"name":"Precisão","description":"Ações ofensivas constroem Precisão para disparos técnicos e execuções."},"passive":{"name":"Olho de Caçador","description":"Manter pressão sobre alvos vulneráveis favorece sequências precisas e letais."},"base":[["Flecha Precisa","D","Dispara contra um ponto vital e causa dano físico confiável."],["Disparo Perfurante","DX","Atravessa a guarda, causando dano e reduzindo defesa."],["Rajada Tripla","A3","Dispara em rápida sucessão contra até 3 inimigos."],["Marca do Predador","X","Marca um inimigo e expõe suas defesas."],["Passo do Vento","Bself","Assume uma postura móvel e aumenta força e iniciativa."],["Chuva de Flechas","A4","Cobre a formação inimiga e atinge até 4 alvos."],["Tiro do Horizonte","T","Alinha um disparo absoluto que causa dano verdadeiro."]],"paths":[{"key":"atirador","skills":[["Mira Imóvel","Bself","Estabiliza a postura e eleva força e iniciativa."],["Tiro de Ruptura","DX","Disparo técnico que causa dano e abre a defesa inimiga."],["Flecha Silenciadora","DC","Atinge a concentração do alvo, causando dano e silêncio."],["Olho da Agulha","T","Concentra toda a precisão em dano verdadeiro."],["Disparo Impossível","D","Executa um tiro de extrema dificuldade e grande dano físico."]]},{"key":"cacador","skills":[["Armadilha Serrilhada","DX","Fere e desestabiliza um inimigo."],["Sinal da Caçada","X","Marca um inimigo e expõe suas fraquezas ao grupo."],["Flechas de Contenção","A2","Dispara em ângulos cruzados contra até 2 inimigos."],["Matilha de Setas","A3","Coordena uma sequência de tiros contra até 3 inimigos."],["Caçada Selvagem","A4","Transforma o campo em território de caça e atinge até 4 inimigos."]]}]},
  {"name":"Assassino","attrs":["FOR","INI"],"dtype":"physical","description":"Especialista em explosão, execução e janelas de vulnerabilidade. Escolhe alvos prioritários e pune qualquer abertura.","mechanic":{"name":"Ímpeto Sombrio","description":"Dano e estados negativos geram Ímpeto para técnicas de execução."},"passive":{"name":"Golpe Oportunista","description":"Alvos debilitados se tornam oportunidades para sequências mais letais."},"base":[["Corte Oculto","D","Surge no ponto cego e desfere um corte físico rápido."],["Lâmina Envenenada","DX","Fere e reduz as defesas do alvo."],["Dança das Facas","A3","Arremessa lâminas e atinge até 3 inimigos."],["Fumaça Negra","X","Reduz iniciativa e defesa do alvo."],["Passo Fantasma","Bself","Eleva força e iniciativa por 2 turnos."],["Golpe de Misericórdia","T","Explora uma abertura fatal e causa dano verdadeiro."],["Noite das Lâminas","A4","Cruza o campo em cortes contra até 4 inimigos."]],"paths":[{"key":"executor","skills":[["Sentença","X","Marca um inimigo para execução e reduz suas defesas."],["Corte da Garganta","DC","Causa dano e silencia o alvo brevemente."],["Colheita Rubra","DH","Causa dano e recupera vitalidade."],["Execução Fria","T","Converte a abertura criada em dano verdadeiro."],["Último Suspiro","D","Desfere um ataque final de altíssimo dano físico."]]},{"key":"sombra","skills":[["Véu da Sombra","Bself","Oculta a presença e aumenta força e iniciativa."],["Passos Entre Sombras","D","Ataca antes que o inimigo consiga reagir."],["Eco Sombrio","A2","Imagens residuais atacam até 2 inimigos."],["Silêncio da Noite","DC","Causa dano e rompe a concentração do alvo."],["Eclipse Assassino","A3","Transforma sombras em lâminas contra até 3 inimigos."]]}]},
  {"name":"Bárbaro","attrs":["FOR","RES"],"dtype":"physical","description":"Brutamontes ofensivo que converte a violência da batalha em Fúria e cresce conforme o confronto se intensifica.","mechanic":{"name":"Fúria","description":"Causar e receber dano alimenta Fúria, consumida por técnicas de alto impacto."},"passive":{"name":"Sangue Quente","description":"Pressão constante favorece golpes pesados, sustentação e ataques em área."},"base":[["Machadada Brutal","D","Desfere um golpe pesado de grande dano físico."],["Quebra-Ossos","DX","Esmaga a postura do alvo e reduz suas defesas."],["Varredura Selvagem","A2","Gira a arma e atinge até 2 inimigos."],["Rugido de Guerra","Bself","Aumenta força e resistência por 2 turnos."],["Sede de Sangue","DH","Fere o inimigo e recupera parte da própria vida."],["Terremoto de Aço","A3","Golpeia com força suficiente para atingir até 3 inimigos."],["Fúria Primal","A4","Libera uma ofensiva brutal contra até 4 inimigos."]],"paths":[{"key":"berserker","skills":[["Frenesi","Bself","Abandona cautela e aumenta força e iniciativa."],["Rasgo Carmesim","DX","Causa dano e deixa o alvo vulnerável."],["Carnificina","A3","Encadeia golpes brutais contra até 3 inimigos."],["Sem Misericórdia","T","Canaliza Fúria em dano verdadeiro."],["Fim da Linha","D","Concentra toda a força em uma execução física devastadora."]]},{"key":"guardiao-totemico","skills":[["Pele de Urso","Bself","Invoca resistência ancestral e fortalece defesa e resistência."],["Totem Protetor","S","Escolha um aliado e envolva-o em proteção espiritual."],["Urro Ancestral","Xtaunt","Provoca um inimigo e prende sua atenção."],["Investida do Bisão","DX","Causa dano e desestabiliza a defesa do alvo."],["Espírito da Montanha","BA3","Fortalece até 3 aliados com resistência totêmica."]]}]},
  {"name":"Bardo","attrs":["ARC","INT"],"dtype":"magic","description":"Suporte versátil que usa música para fortalecer aliados, perturbar inimigos e controlar o ritmo da batalha.","mechanic":{"name":"Inspiração","description":"Suporte, cura e estados geram Inspiração para refrões e ápices de apresentação."},"passive":{"name":"Ritmo de Combate","description":"Alternar suporte, controle e dano mantém a apresentação eficiente."},"base":[["Acorde Cortante","D","Projeta uma nota comprimida e causa dano mágico."],["Verso Dissonante","DX","Causa dano e reduz as resistências do alvo."],["Refrão Inspirador","B","Escolha um aliado e aumente seu poder e iniciativa."],["Canção Restauradora","H","Escolha um aliado e restaure sua vida."],["Crescendo","A3","Amplifica uma progressão sonora contra até 3 inimigos."],["Nota Hipnótica","C","Prende a atenção do inimigo e interrompe sua ação."],["Apoteose Musical","BA4","Conduz um grande refrão e fortalece até 4 aliados."]],"paths":[{"key":"colegio-da-guerra","skills":[["Marcha de Batalha","BA3","Fortalece até 3 aliados para uma ofensiva coordenada."],["Rufar dos Tambores","A2","Libera impacto sonoro contra até 2 inimigos."],["Hino da Coragem","B","Escolha um aliado e fortaleça sua força e resistência."],["Cadência Implacável","A3","Ataca até 3 inimigos com impactos sonoros."],["Sinfonia da Vitória","BA4","Eleva até 4 aliados ao ápice do ritmo de combate."]]},{"key":"colegio-do-glamour","skills":[["Sussurro Encantador","C","Captura a atenção e quebra a concentração do inimigo."],["Espelho de Glamour","X","Confunde o alvo e reduz suas defesas."],["Valsa Restauradora","HA2","Cura até 2 aliados com uma melodia suave."],["Coro das Máscaras","A3","Projeta ilusões sonoras contra até 3 inimigos."],["Aplauso Eterno","HA4","Encerra a apresentação com cura para até 4 aliados."]]}]},
  {"name":"Bruxo","attrs":["INT","ARC"],"dtype":"magic","description":"Conjurador de pacto que transforma maldições e risco em pressão mágica, controle e dano contínuo.","mechanic":{"name":"Pacto","description":"Amaldiçoar e controlar inimigos alimenta o Pacto para manifestações proibidas."},"passive":{"name":"Preço do Poder","description":"Inimigos sob estados negativos criam as melhores janelas ofensivas do Bruxo."},"base":[["Rajada Profana","D","Dispara energia de pacto e causa dano mágico."],["Marca Maldita","DX","Causa dano e reduz as resistências do alvo."],["Chamas do Pacto","A3","Incendeia energia profana contra até 3 inimigos."],["Selo de Fraqueza","X","Amaldiçoa um inimigo e reduz suas defesas."],["Terror Sussurrante","C","Invade a mente do alvo e provoca medo."],["Dreno Impuro","DH","Rouba essência do inimigo e recupera vida."],["Portal do Abismo","A4","Abre uma fenda profana contra até 4 inimigos."]],"paths":[{"key":"pacto-abissal","skills":[["Tentáculo Abissal","DX","Causa dano e reduz as defesas do alvo."],["Olhar do Vazio","C","Expõe o inimigo ao vazio e rompe sua ação."],["Maré Negra","A3","Uma onda de escuridão atinge até 3 inimigos."],["Avatar do Abismo","U","Invoca uma manifestação que fortalece o Bruxo."],["Horizonte Sem Luz","A4","O vazio avança sobre até 4 inimigos."]]},{"key":"pacto-infernal","skills":[["Brasa Contratual","DX","Marca o inimigo com fogo infernal e reduz suas resistências."],["Correntes de Enxofre","DC","Causa dano e silencia o alvo."],["Explosão Infernal","A3","Detona fogo de pacto em até 3 inimigos."],["Preço em Sangue","DH","Causa dano e converte essência roubada em cura."],["Condenação Ígnea","A4","Invoca fogo infernal sobre até 4 inimigos."]]}]},
  {"name":"Cavaleiro","attrs":["DEF","FOR"],"dtype":"physical","description":"Linha de frente resistente que combina pressão física, provocação e proteção seletiva sem abrir mão de ofensiva.","mechanic":{"name":"Guarda","description":"Sofrer dano, controlar e proteger gera Guarda para técnicas defensivas e retaliações."},"passive":{"name":"Linha Inquebrável","description":"O Cavaleiro sustenta a frente e cria janelas seguras para o grupo."},"base":[["Golpe de Escudo","DX","Causa dano e quebra a postura defensiva do alvo."],["Corte de Vanguarda","D","Ataca com precisão mantendo a linha de frente."],["Desafio do Cavaleiro","Xtaunt","Provoca um inimigo e prende sua atenção."],["Postura de Ferro","Bself","Aumenta defesa e resistência por 2 turnos."],["Arco de Aço","A2","Varre a linha inimiga e atinge até 2 alvos."],["Investida Real","DC","Causa dano e interrompe a concentração do alvo."],["Muralha em Movimento","A3","Avança golpeando e atinge até 3 inimigos."]],"paths":[{"key":"bastiao","skills":[["Juramento de Proteção","S","Escolha um aliado e conceda uma barreira robusta."],["Provocação Absoluta","Xtaunt","Desafia um inimigo e prende sua atenção."],["Fortaleza Viva","Bself","Eleva defesa e resistência por 2 turnos."],["Retaliação de Ferro","D","Responde à pressão com um golpe físico pesado."],["Bastião dos Companheiros","BA3","Fortalece até 3 aliados com disciplina defensiva."]]},{"key":"cavaleiro-negro","skills":[["Lâmina Sombria","D","Reveste a arma de energia sombria e causa dano físico."],["Armadura Maldita","Bself","Aumenta força e resistência através de um pacto sombrio."],["Golpe do Carrasco","DX","Fere brutalmente e reduz a defesa inimiga."],["Sacrifício Negro","DH","Causa dano e converte violência em recuperação."],["Marcha da Ruína","A3","Avança em uma sequência sombria contra até 3 inimigos."]]}]},
  {"name":"Clérigo","attrs":["ARC","INT"],"dtype":"magic","description":"Canalizador divino dedicado a cura, purificação, fortalecimento e punição sagrada com escolha real de alvos.","mechanic":{"name":"Fé","description":"Curar, proteger e purificar gera Fé para milagres e julgamentos."},"passive":{"name":"Graça Renovada","description":"Alternar cura e ofensiva mantém o Clérigo relevante em qualquer fase do combate."},"base":[["Luz Punitiva","D","Concentra energia sagrada e causa dano mágico."],["Julgamento","DX","Fere com poder divino e reduz as resistências do alvo."],["Cura Menor","H","Escolha um aliado e restaure sua vida."],["Bênção do Peregrino","B","Escolha um aliado e fortaleça resistência e poder arcano."],["Purificar","P","Escolha um aliado, remova um efeito negativo e cure parte de sua vida."],["Onda Sagrada","A3","Libera luz ofensiva contra até 3 inimigos."],["Milagre","HA4","Invoca uma onda restauradora que cura até 4 aliados."]],"paths":[{"key":"dominio-da-guerra","skills":[["Arma Consagrada","B","Escolha um aliado e fortaleça sua capacidade ofensiva."],["Martelo da Fé","DX","Causa dano sagrado e quebra as resistências do inimigo."],["Comando Divino","BA3","Fortalece até 3 aliados para a ofensiva."],["Cruzada Radiante","A3","Atravessa até 3 inimigos com luz sagrada."],["Julgamento Final","T","Concentra um veredito divino em dano verdadeiro."]]},{"key":"dominio-da-vida","skills":[["Cura Maior","H","Escolha um aliado e restaure uma grande quantidade de vida."],["Escudo da Vida","S","Escolha um aliado e proteja-o com energia vital."],["Purificação Profunda","P","Remove um efeito negativo do aliado escolhido e recupera sua vida."],["Círculo Restaurador","HA3","Cura até 3 aliados em uma onda de energia vital."],["Ressurgência","HA4","Libera o maior milagre do domínio e cura até 4 aliados."]]}]},
  {"name":"Druida","attrs":["ARC","INT"],"dtype":"magic","description":"Guardião natural que alterna ferocidade, cura e controle, usando o ciclo da natureza para responder ao combate.","mechanic":{"name":"Essência Natural","description":"Dano, cura e estados alimentam Essência Natural para técnicas de transformação e restauração."},"passive":{"name":"Ciclo Selvagem","description":"Alternar entre ataque e suporte representa o ciclo natural e amplia a versatilidade."},"base":[["Espinho Selvagem","D","Projeta espinhos endurecidos e causa dano mágico."],["Raízes Vorazes","DX","Causa dano e enfraquece as defesas do alvo."],["Florescer","H","Escolha um aliado e restaure sua vida."],["Pele de Carvalho","B","Escolha um aliado e aumente defesa e resistência."],["Enxame Feral","A3","Convoca forças naturais contra até 3 inimigos."],["Uivo da Floresta","C","Invoca a presença da mata para aterrorizar um inimigo."],["Tempestade Primordial","A4","Desencadeia forças naturais contra até 4 inimigos."]],"paths":[{"key":"circulo-da-lua","skills":[["Garras Lunares","D","Manifesta garras bestiais e causa dano físico concentrado."],["Forma do Predador","Bself","Assume aspecto de caça e aumenta força e iniciativa."],["Salto Bestial","DX","Ataca com ferocidade e quebra a defesa do alvo."],["Frenesi Lunar","A3","Dilacera até 3 inimigos em sequência."],["Avatar da Lua","A4","Assume a forma máxima e atinge até 4 inimigos."]]},{"key":"circulo-da-terra","skills":[["Bênção do Bosque","H","Escolha um aliado e cure seus ferimentos."],["Casca Ancestral","S","Escolha um aliado e cubra-o com uma barreira vegetal."],["Pólen Purificador","P","Escolha um aliado, remova uma condição negativa e recupere sua vida."],["Campo de Espinhos","A3","Ergue espinhos sob até 3 inimigos."],["Primavera Eterna","HA4","Faz a vida florescer e cura até 4 aliados."]]}]},
  {"name":"Feiticeiro","attrs":["INT","ARC"],"dtype":"magic","description":"Conjurador nato de alta potência que manipula energia bruta, explosões, controle e autoaprimoramento mágico.","mechanic":{"name":"Sobrecarga","description":"Dano e estados acumulam Sobrecarga para romper limites de potência."},"passive":{"name":"Magia Instintiva","description":"Ritmo ofensivo consistente favorece explosões cada vez mais perigosas."},"base":[["Faísca Arcana","D","Dispara energia mágica pura contra o alvo."],["Distorção Instável","DX","Causa dano e rompe as resistências do inimigo."],["Explosão Prismática","A3","Detona energia colorida contra até 3 inimigos."],["Pulso Acelerado","Bself","Amplifica inteligência e iniciativa por 2 turnos."],["Colapso Mental","DC","Causa dano e rompe a concentração do alvo."],["Nova Arcana","A4","Libera uma explosão que alcança até 4 inimigos."],["Ruptura de Mana","T","Condensa energia a ponto de causar dano verdadeiro."]],"paths":[{"key":"caos-arcano","skills":[["Dado do Caos","D","Canaliza magia imprevisível em um ataque de alta potência."],["Vertigem Cromática","DC","Causa dano e desorienta o alvo."],["Chuva Improvável","A3","Projeta efeitos caóticos contra até 3 inimigos."],["Paradoxo","T","Rompe a lógica mágica e causa dano verdadeiro."],["Catástrofe Arcana","A4","Libera caos bruto sobre até 4 inimigos."]]},{"key":"linhagem-draconica","skills":[["Sopro Ancestral","A2","Expele energia dracônica contra até 2 inimigos."],["Escamas Arcanas","Bself","Fortalece resistência e inteligência."],["Garra Elemental","DX","Causa dano e reduz a resistência do alvo."],["Rugido Dracônico","C","Aterroriza um inimigo com presença ancestral."],["Coração do Dragão","A4","Libera a herança dracônica contra até 4 inimigos."]]}]},
  {"name":"Guerreiro","attrs":["FOR","DEF"],"dtype":"physical","description":"Combatente técnico e versátil. Pressiona, quebra guardas e comanda aliados sem depender de uma coleção de escudos repetidos.","mechanic":{"name":"Bravura","description":"Ataques, controle e proteção geram Bravura para comandos e sequências marciais."},"passive":{"name":"Disciplina Marcial","description":"Variar entre golpes, controle e comando mantém sua presença constante."},"base":[["Corte Tático","D","Executa um golpe técnico e confiável contra o alvo escolhido."],["Quebra-Guarda","DX","Causa dano físico e reduz as proteções do inimigo."],["Contraofensiva","Bself","Assume postura agressiva e aumenta força e defesa."],["Varredura de Aço","A2","Descreve um arco amplo e atinge até 2 inimigos."],["Grito de Comando","B","Escolha um aliado e aumente força e iniciativa por 2 turnos."],["Pressão de Vanguarda","DC","Causa dano e interrompe a concentração do alvo."],["Tempestade de Lâminas","A3","Encadeia cortes precisos e atinge até 3 inimigos."]],"paths":[{"key":"comandante","skills":[["Ordem de Avanço","B","Escolha um aliado e fortaleça força e iniciativa."],["Formação de Guerra","BA3","Coordena e fortalece até 3 aliados."],["Intervenção do Comandante","S","Escolha um aliado e conceda uma única proteção tática."],["Romper a Linha","A2","Ataca até 2 inimigos e abre a formação adversária."],["Comando Supremo","BA4","Emite a ordem máxima e fortalece até 4 aliados."]]},{"key":"mestre-de-armas","skills":[["Estocada de Precisão","D","Ataca uma abertura específica com grande dano físico."],["Corte Reverso","DX","Fere e reduz a defesa com uma mudança súbita de direção."],["Sequência Marcial","A2","Encadeia técnicas distintas contra até 2 inimigos."],["Golpe de Ruptura","T","Concentra domínio técnico em dano verdadeiro."],["Arsenal Vivo","A3","Alterna estilos em uma sequência contra até 3 inimigos."]]}]},
  {"name":"Ladino","attrs":["INI","FOR"],"dtype":"physical","description":"Especialista em truques, velocidade e abertura de defesas. Transforma pequenas brechas em pressão contínua.","mechanic":{"name":"Vantagem","description":"Dano e debuffs geram Vantagem para técnicas oportunistas."},"passive":{"name":"Jogo Sujo","description":"Estados negativos e mudanças de ritmo criam oportunidades para golpes decisivos."},"base":[["Punhalada Rápida","D","Ataca antes que o alvo ajuste a guarda."],["Golpe Sujo","DX","Causa dano e reduz as defesas do inimigo."],["Leque de Adagas","A3","Arremessa adagas contra até 3 inimigos."],["Areia nos Olhos","X","Desorienta o alvo e reduz suas defesas."],["Pés Ligeiros","Bself","Aumenta iniciativa e força por 2 turnos."],["Ataque Oportunista","T","Explora uma abertura e causa dano verdadeiro."],["Chuva de Punhais","A4","Satura a formação inimiga e atinge até 4 alvos."]],"paths":[{"key":"duelista","skills":[["Desafio Formal","X","Marca um inimigo e reduz sua capacidade defensiva."],["Floreio","Bself","Aumenta força e iniciativa com técnica refinada."],["Riposta","D","Responde com um golpe físico preciso."],["Finta Mortal","DX","Engana a guarda e reduz a defesa do alvo."],["Ponto Final","T","Encerra o duelo com dano verdadeiro concentrado."]]},{"key":"trapaceiro","skills":[["Bolsa de Truques","X","Escolha um inimigo e aplique um enfraquecimento."],["Bomba de Fumaça","A2","Explode fumaça e estilhaços contra até 2 inimigos."],["Mão Leve","B","Escolha um aliado e aumente sua iniciativa e força."],["Armadilha Improvisada","DC","Causa dano e interrompe técnicas do alvo."],["Grande Trapaça","A3","Executa uma cadeia de artimanhas contra até 3 inimigos."]]}]},
  {"name":"Mago","attrs":["INT","ARC"],"dtype":"magic","description":"Conjurador acadêmico de grande repertório, especializado em dano mágico, controle e manipulação de múltiplos alvos.","mechanic":{"name":"Foco Arcano","description":"Sequências de magia mantêm Foco Arcano para fórmulas complexas."},"passive":{"name":"Erudição Arcana","description":"Escolher corretamente entre alvo único, controle e área maximiza o potencial do Mago."},"base":[["Míssil Arcano","D","Dispara energia condensada e causa dano mágico."],["Raio Dissipador","DX","Causa dano e reduz as resistências do alvo."],["Explosão Elemental","A3","Detona energia arcana contra até 3 inimigos."],["Barreira Arcana","S","Escolha um aliado e conceda uma barreira mágica."],["Aceleração Mística","B","Escolha um aliado e aumente inteligência e iniciativa."],["Selo de Silêncio","C","Interrompe a concentração e silencia o inimigo."],["Meteoros Arcanos","A4","Invoca uma chuva de energia sobre até 4 inimigos."]],"paths":[{"key":"arcanista","skills":[["Égide Rúnica","S","Escolha um aliado e proteja-o com runas arcanas."],["Quebra-Encanto","P","Escolha um aliado, remova um efeito negativo e restaure vida."],["Prisão de Mana","DC","Causa dano e silencia o alvo."],["Lança Astral","T","Concentra energia pura em dano verdadeiro."],["Teorema Supremo","A3","Executa uma fórmula arcana contra até 3 inimigos."]]},{"key":"elementalista","skills":[["Lança de Gelo","DX","Causa dano mágico e enfraquece a resistência do alvo."],["Arco Elétrico","A2","Salta entre até 2 inimigos."],["Torrente de Fogo","A3","Incendeia até 3 inimigos."],["Olho da Tempestade","Bself","Eleva inteligência e iniciativa."],["Convergência Elemental","A4","Combina múltiplos elementos contra até 4 inimigos."]]}]},
  {"name":"Monge","attrs":["FOR","INI"],"dtype":"physical","description":"Lutador disciplinado que usa Chi para executar combos, purificar aliados e alterar o ritmo do combate.","mechanic":{"name":"Chi","description":"Ataques e disciplina geram Chi para combos e manifestação espiritual."},"passive":{"name":"Fluxo Interior","description":"Alternar ofensiva e suporte mantém o Chi circulando e o kit flexível."},"base":[["Punho Direto","D","Golpeia com técnica precisa e causa dano físico."],["Palma Quebradora","DX","Causa dano e quebra a postura defensiva."],["Sequência de Três Golpes","A3","Desfere golpes contra até 3 inimigos."],["Respiração Centrada","Bself","Aumenta força e iniciativa por 2 turnos."],["Toque Revigorante","H","Escolha um aliado e restaure sua vida canalizando Chi."],["Palma Silenciosa","DC","Causa dano e interrompe a concentração do alvo."],["Cem Punhos","A4","Libera uma enxurrada contra até 4 inimigos."]],"paths":[{"key":"caminho-espiritual","skills":[["Sopro Vital","H","Escolha um aliado e restaure sua vida com Chi."],["Manto de Chi","S","Escolha um aliado e conceda proteção espiritual."],["Purificação Interior","P","Escolha um aliado, remova um efeito negativo e cure sua vida."],["Onda Serena","HA3","Canaliza serenidade e cura até 3 aliados."],["Iluminação","BA4","Fortalece até 4 aliados com equilíbrio espiritual."]]},{"key":"punho-de-ferro","skills":[["Punho Demolidor","DX","Causa dano físico e reduz as defesas do alvo."],["Joelho Ascendente","D","Executa um golpe físico pesado."],["Combo Relâmpago","A2","Encadeia golpes contra até 2 inimigos."],["Quebra de Espírito","T","Concentra Chi em dano verdadeiro."],["Mil Golpes","A4","Libera o ápice ofensivo contra até 4 inimigos."]]}]},
  {"name":"Necromante","attrs":["INT","ARC"],"dtype":"magic","description":"Manipulador de Almas que alterna dano sombrio, maldições, drenagem e invocações para dominar combates prolongados.","mechanic":{"name":"Almas","description":"Dano, estados e mortes alimentam Almas, recurso limitado para técnicas poderosas."},"passive":{"name":"Entre Dois Mundos","description":"Maldições e drenagem convertem pressão ofensiva em sustentação e controle."},"base":[["Toque Necrótico","D","Canaliza energia da morte e causa dano mágico."],["Maldição Óssea","DX","Causa dano e reduz as defesas do inimigo."],["Explosão de Cadáveres","A3","Detona energia necromântica contra até 3 inimigos."],["Dreno de Vida","DH","Rouba força vital e recupera vida."],["Mão do Túmulo","C","Invoca presenças mortas para aterrorizar o inimigo."],["Servo Espectral","U","Invoca um servo que fortalece temporariamente o Necromante."],["Maré dos Mortos","A4","Libera energia funerária contra até 4 inimigos."]],"paths":[{"key":"pastor-do-veu","skills":[["Costura de Alma","H","Escolha um aliado e restaure sua vida com energia espiritual."],["Véu Protetor","S","Escolha um aliado e conceda um escudo espectral."],["Exorcismo Inverso","P","Escolha um aliado, remova um efeito negativo e recupere sua vida."],["Lamento Coletivo","A3","Libera espíritos contra até 3 inimigos."],["Travessia do Véu","HA3","Conduz energia do além e cura até 3 aliados."]]},{"key":"senhor-dos-mortos","skills":[["Guerreiro Esqueleto","U","Invoca um lacaio ósseo e fortalece a presença ofensiva."],["Muralha de Ossos","Bself","Aumenta defesa e resistência com ossos conjurados."],["Comando dos Mortos","DX","Ataca por meio dos servos e reduz as defesas do alvo."],["Legião Profana","A3","Ordena uma investida espectral contra até 3 inimigos."],["Reino dos Mortos","A4","Transforma o campo em território necromântico contra até 4 inimigos."]]}]},
  {"name":"Ninja","attrs":["INI","FOR"],"dtype":"physical","description":"Especialista em Selos, velocidade e interrupção. Cria sequências rápidas e escolhe o momento exato de controlar ou finalizar.","mechanic":{"name":"Selos","description":"Golpes e estados geram Selos consumidos por controle e execuções."},"passive":{"name":"Ritmo Shinobi","description":"Alternar marcação, velocidade e execução mantém a pressão do Ninja."},"base":[["Kunai Precisa","D","Arremessa uma kunai em ponto vital e causa dano físico."],["Selo de Ruptura","DX","Marca o alvo, causa dano e reduz suas defesas."],["Shuriken em Leque","A3","Arremessa projéteis contra até 3 inimigos."],["Kawarimi","Bself","Aumenta iniciativa e resistência."],["Selo do Silêncio","C","Bloqueia temporariamente a concentração do inimigo."],["Corte Relâmpago","T","Cruza o alvo em alta velocidade e causa dano verdadeiro."],["Tempestade Shinobi","A4","Ataca de múltiplos ângulos e atinge até 4 inimigos."]],"paths":[{"key":"mestre-dos-selos","skills":[["Selo da Fraqueza","X","Reduz as defesas do inimigo marcado."],["Selo de Mudez","C","Silencia o alvo por um breve período."],["Corrente de Selos","A2","Explode marcas em até 2 inimigos."],["Prisão dos Cinco Selos","DC","Causa dano e interrompe a concentração."],["Mandala Proibida","A4","Ativa uma formação de selos contra até 4 inimigos."]]},{"key":"shinobi","skills":[["Passo Sem Som","Bself","Aumenta força e iniciativa para preparar a execução."],["Corte da Lua","D","Ataca com uma lâmina rápida e precisa."],["Duas Sombras","A2","Ataca até 2 inimigos usando duplicatas de movimento."],["Execução Shinobi","T","Converte velocidade em dano verdadeiro."],["Noite Sem Testemunhas","A3","Cruza o campo e atinge até 3 inimigos."]]}]},
  {"name":"Paladino","attrs":["FOR","ARC"],"dtype":"magic","description":"Híbrido sagrado de linha de frente que combina punição, cura seletiva e proteção sem transformar todo o kit em escudos.","mechanic":{"name":"Zelo","description":"Dano sagrado, cura e proteção geram Zelo para juramentos e técnicas decisivas."},"passive":{"name":"Juramento Vivo","description":"Alternar ofensiva e suporte mantém o Paladino relevante durante todo o confronto."},"base":[["Golpe Radiante","D","Reveste a arma de luz e causa dano mágico."],["Julgamento Marcial","DX","Causa dano sagrado e reduz as resistências do alvo."],["Imposição das Mãos","H","Escolha um aliado e restaure sua vida."],["Aura de Coragem","B","Escolha um aliado e aumente força e resistência."],["Luz Purificadora","P","Escolha um aliado, remova um efeito negativo e cure sua vida."],["Cruz Radiante","A3","Libera luz ofensiva contra até 3 inimigos."],["Veredito Celestial","A4","Invoca uma condenação luminosa contra até 4 inimigos."]],"paths":[{"key":"juramento-da-luz","skills":[["Proteção Luminosa","S","Escolha um aliado e conceda uma barreira sagrada."],["Cura do Juramento","H","Escolha um aliado e restaure uma grande quantidade de vida."],["Aurora Purificadora","P","Remove um efeito negativo do aliado e recupera sua vida."],["Farol de Esperança","HA3","Cura até 3 aliados com uma onda luminosa."],["Alvorada Sagrada","HA4","Libera a maior bênção e cura até 4 aliados."]]},{"key":"juramento-da-vinganca","skills":[["Marca da Vingança","X","Marca um inimigo e reduz suas defesas."],["Golpe Perseguidor","DX","Causa dano e quebra a proteção do alvo."],["Caçada Sagrada","A2","Avança contra até 2 inimigos com golpes de luz."],["Punição Inevitável","T","Concentra o juramento em dano verdadeiro."],["Anjo Vingador","A3","Libera uma sequência sagrada contra até 3 inimigos."]]}]}
]
$catalog$::jsonb;
  v_entry jsonb;
  v_row record;
  v_path jsonb;
  v_path_def jsonb;
  v_paths jsonb;
  v_skills jsonb;
  v_resource_max integer;
  v_attr_one text;
  v_attr_two text;
  v_dtype text;
begin
  for v_entry in select value from jsonb_array_elements(v_catalog)
  loop
    select id, payload into v_row from public.v2_classes where name = v_entry->>'name' limit 1;
    if not found then
      raise exception 'Classe não encontrada: %', v_entry->>'name';
    end if;

    v_resource_max := greatest(1, coalesce((v_row.payload #>> '{resource,maximum}')::integer, 100));
    v_attr_one := v_entry #>> '{attrs,0}';
    v_attr_two := v_entry #>> '{attrs,1}';
    v_dtype := v_entry->>'dtype';
    v_skills := public._v2_rework_skill_list(v_entry->'base', array[1,8,16,24,32,40,48], v_attr_one, v_attr_two, v_dtype, v_resource_max);
    v_paths := '[]'::jsonb;

    for v_path in select value from jsonb_array_elements(coalesce(v_row.payload->'paths','[]'::jsonb))
    loop
      select value into v_path_def
      from jsonb_array_elements(v_entry->'paths')
      where value->>'key' = v_path->>'key'
      limit 1;

      if v_path_def is not null then
        v_path := jsonb_set(
          v_path,
          '{skills}',
          public._v2_rework_skill_list(v_path_def->'skills', array[50,60,70,85,100], v_attr_one, v_attr_two, v_dtype, v_resource_max),
          true
        );
      end if;
      v_paths := v_paths || jsonb_build_array(v_path);
      v_path_def := null;
    end loop;

    update public.v2_classes
    set payload = v_row.payload || jsonb_build_object(
      'description', v_entry->>'description',
      'mechanic', v_entry->'mechanic',
      'passive', v_entry->'passive',
      'progression', v_skills,
      'paths', v_paths
    ), updated_at = now()
    where id = v_row.id;
  end loop;
end;
$$;

drop function public._v2_rework_skill_list(jsonb,integer[],text,text,text,integer);
drop function public._v2_rework_skill(text,integer,text,text,text,text,text,integer);
drop function public._v2_rework_op(text,text,text,jsonb,text,integer,jsonb);
