begin;

create table if not exists public.v2_player_progress (
  user_id uuid primary key references auth.users(id) on delete cascade,
  level integer not null default 1 check (level between 1 and 100),
  experience bigint not null default 0 check (experience >= 0),
  coins bigint not null default 250 check (coins >= 0),
  last_seen_at timestamptz not null default now(),
  last_daily_claim date,
  daily_streak integer not null default 0 check (daily_streak >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.v2_shop_items (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null,
  description text not null default '',
  category text not null default 'cosmetic',
  price bigint not null check (price >= 0),
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.v2_inventory (
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id uuid not null references public.v2_shop_items(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  acquired_at timestamptz not null default now(),
  primary key (user_id, item_id)
);

create table if not exists public.v2_player_achievements (
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_slug text not null,
  unlocked_at timestamptz not null default now(),
  primary key (user_id, achievement_slug)
);

create table if not exists public.v2_admin_history (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.v2_handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.v2_profiles (user_id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', ''))
  on conflict (user_id) do nothing;
  insert into public.v2_user_roles (user_id, role) values (new.id, 'player')
  on conflict (user_id) do nothing;
  insert into public.v2_player_progress (user_id) values (new.id)
  on conflict (user_id) do nothing;
  insert into public.v2_player_achievements (user_id, achievement_slug)
  values (new.id, 'primeiros-passos') on conflict do nothing;
  return new;
end; $$;

insert into public.v2_player_progress (user_id)
select id from auth.users on conflict (user_id) do nothing;
insert into public.v2_player_achievements (user_id, achievement_slug)
select id, 'primeiros-passos' from auth.users on conflict do nothing;

create or replace function public.v2_set_player_role(p_user_id uuid, p_role text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.v2_is_admin() then raise exception 'Acesso negado' using errcode = '42501'; end if;
  if p_role not in ('player','moderator','admin','founder') then raise exception 'Cargo inválido'; end if;
  if p_role = 'founder' and not exists (
    select 1 from public.v2_user_roles where user_id = auth.uid() and role = 'founder'
  ) then raise exception 'Somente fundadores podem promover fundadores' using errcode = '42501'; end if;
  update public.v2_user_roles set role = p_role where user_id = p_user_id;
  insert into public.v2_admin_history(actor_id, action, target_type, target_id, details)
  values (auth.uid(), 'role.updated', 'player', p_user_id::text, jsonb_build_object('role', p_role));
end; $$;

create or replace function public.v2_claim_daily_reward()
returns jsonb language plpgsql security definer set search_path = public as $$
declare p public.v2_player_progress; reward integer;
begin
  select * into p from public.v2_player_progress where user_id = auth.uid() for update;
  if p.last_daily_claim = current_date then raise exception 'Recompensa já coletada hoje'; end if;
  p.daily_streak := case when p.last_daily_claim = current_date - 1 then p.daily_streak + 1 else 1 end;
  reward := 50 + least(p.daily_streak, 7) * 10;
  update public.v2_player_progress set coins = coins + reward, daily_streak = p.daily_streak,
    last_daily_claim = current_date, last_seen_at = now() where user_id = auth.uid();
  return jsonb_build_object('reward', reward, 'streak', p.daily_streak);
end; $$;

create or replace function public.v2_buy_shop_item(p_item_id uuid)
returns void language plpgsql security definer set search_path = public as $$
declare item public.v2_shop_items; balance bigint;
begin
  select * into item from public.v2_shop_items where id = p_item_id and active for update;
  if item.id is null then raise exception 'Item indisponível'; end if;
  select coins into balance from public.v2_player_progress where user_id = auth.uid() for update;
  if balance < item.price then raise exception 'Moedas insuficientes'; end if;
  update public.v2_player_progress set coins = coins - item.price where user_id = auth.uid();
  insert into public.v2_inventory(user_id,item_id) values(auth.uid(),item.id)
  on conflict(user_id,item_id) do update set quantity = public.v2_inventory.quantity + 1;
end; $$;

alter table public.v2_player_progress enable row level security;
alter table public.v2_shop_items enable row level security;
alter table public.v2_inventory enable row level security;
alter table public.v2_player_achievements enable row level security;
alter table public.v2_admin_history enable row level security;

drop policy if exists "v2 profiles readable by owner or admin" on public.v2_profiles;
create policy "v2 public profiles readable" on public.v2_profiles for select using (true);

create policy "progress public ranking read" on public.v2_player_progress for select using (true);
create policy "progress admin update" on public.v2_player_progress for update using (public.v2_is_admin()) with check (public.v2_is_admin());
create policy "shop public read" on public.v2_shop_items for select using (active or public.v2_is_admin());
create policy "shop admin manage" on public.v2_shop_items for all using (public.v2_is_admin()) with check (public.v2_is_admin());
create policy "inventory owner read" on public.v2_inventory for select using (user_id = auth.uid() or public.v2_is_admin());
create policy "achievements public read" on public.v2_player_achievements for select using (true);
create policy "history admin read" on public.v2_admin_history for select using (public.v2_is_admin());

grant select, update on public.v2_player_progress to authenticated;
grant select on public.v2_player_progress to anon;
grant select on public.v2_profiles to anon;
grant select on public.v2_shop_items to anon, authenticated;
grant insert, update, delete on public.v2_shop_items to authenticated;
grant select on public.v2_inventory to authenticated;
grant select on public.v2_player_achievements to anon, authenticated;
grant select on public.v2_admin_history to authenticated;
grant execute on function public.v2_set_player_role(uuid,text) to authenticated;
grant execute on function public.v2_claim_daily_reward() to authenticated;
grant execute on function public.v2_buy_shop_item(uuid) to authenticated;

insert into public.v2_shop_items(slug,name,description,category,price) values
('moldura-esmeralda','Moldura Esmeralda','Uma moldura exclusiva para o seu perfil.','profile',180),
('titulo-desbravador','Título: Desbravador','Exiba sua coragem diante de Wonderland.','title',250),
('pocao-de-xp','Poção de Experiência','Concede um bônus de experiência em aventuras.','consumable',120)
on conflict(slug) do nothing;

insert into public.v2_game_settings(key,category,label,description,value,status,published_at) values
('progression.base_xp','progression','Experiência base','XP necessário do nível 1 para o 2.','100'::jsonb,'published',now()),
('progression.growth_rate','progression','Crescimento por nível','Multiplicador da curva de experiência.','1.18'::jsonb,'published',now()),
('economy.daily_base_reward','economy','Recompensa diária','Moedas base do login diário.','50'::jsonb,'published',now())
on conflict(key) do nothing;

commit;
