begin;

create extension if not exists pgcrypto;

create table if not exists public.v2_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.v2_user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'player'
    check (role in ('player', 'moderator', 'admin', 'founder')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.v2_content (
  id uuid primary key default gen_random_uuid(),
  content_type text not null check (
    content_type in (
      'race',
      'class',
      'class_path',
      'skill',
      'item',
      'monster',
      'boss',
      'progression',
      'achievement',
      'event',
      'quest',
      'dungeon'
    )
  ),
  slug text not null check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (char_length(trim(name)) > 0),
  status text not null default 'draft'
    check (status in ('draft', 'published', 'archived')),
  payload jsonb not null default '{}'::jsonb,
  revision integer not null default 1 check (revision >= 1),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (content_type, slug)
);

create index if not exists v2_content_catalog_idx
  on public.v2_content (content_type, status, name);

create table if not exists public.v2_content_revisions (
  id bigint generated by default as identity primary key,
  content_id uuid not null references public.v2_content(id) on delete cascade,
  revision integer not null,
  snapshot jsonb not null,
  edited_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (content_id, revision)
);

create table if not exists public.v2_game_settings (
  key text primary key check (key ~ '^[a-z0-9]+(?:[._-][a-z0-9]+)*$'),
  category text not null,
  label text not null,
  description text not null default '',
  value jsonb not null default '{}'::jsonb,
  status text not null default 'draft'
    check (status in ('draft', 'published', 'archived')),
  revision integer not null default 1 check (revision >= 1),
  updated_by uuid references auth.users(id) on delete set null,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.v2_setting_revisions (
  id bigint generated by default as identity primary key,
  setting_key text not null references public.v2_game_settings(key) on delete cascade,
  revision integer not null,
  snapshot jsonb not null,
  edited_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (setting_key, revision)
);

create or replace function public.v2_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.v2_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.v2_user_roles
    where user_id = auth.uid()
      and role in ('admin', 'founder')
  );
$$;

create or replace function public.v2_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.v2_profiles (user_id, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'display_name', '')
  )
  on conflict (user_id) do nothing;

  insert into public.v2_user_roles (user_id, role)
  values (new.id, 'player')
  on conflict (user_id) do nothing;

  return new;
end;
$$;

create or replace function public.v2_archive_content_revision()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if to_jsonb(old) is distinct from to_jsonb(new) then
    insert into public.v2_content_revisions (
      content_id,
      revision,
      snapshot,
      edited_by
    ) values (
      old.id,
      old.revision,
      to_jsonb(old),
      auth.uid()
    )
    on conflict (content_id, revision) do nothing;

    new.revision := old.revision + 1;
    new.updated_at := now();
    new.updated_by := auth.uid();
  end if;

  return new;
end;
$$;

create or replace function public.v2_archive_setting_revision()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if to_jsonb(old) is distinct from to_jsonb(new) then
    insert into public.v2_setting_revisions (
      setting_key,
      revision,
      snapshot,
      edited_by
    ) values (
      old.key,
      old.revision,
      to_jsonb(old),
      auth.uid()
    )
    on conflict (setting_key, revision) do nothing;

    new.revision := old.revision + 1;
    new.updated_at := now();
    new.updated_by := auth.uid();
  end if;

  return new;
end;
$$;

create or replace function public.v2_publish_content(p_content_id uuid)
returns public.v2_content
language plpgsql
security definer
set search_path = public
as $$
declare
  published_content public.v2_content;
begin
  if not public.v2_is_admin() then
    raise exception 'Acesso administrativo necessário.' using errcode = '42501';
  end if;

  update public.v2_content
  set
    status = 'published',
    published_at = now(),
    updated_by = auth.uid()
  where id = p_content_id
  returning * into published_content;

  if published_content.id is null then
    raise exception 'Conteúdo não encontrado.' using errcode = 'P0002';
  end if;

  return published_content;
end;
$$;

create or replace function public.v2_publish_setting(p_setting_key text)
returns public.v2_game_settings
language plpgsql
security definer
set search_path = public
as $$
declare
  published_setting public.v2_game_settings;
begin
  if not public.v2_is_admin() then
    raise exception 'Acesso administrativo necessário.' using errcode = '42501';
  end if;

  update public.v2_game_settings
  set
    status = 'published',
    published_at = now(),
    updated_by = auth.uid()
  where key = p_setting_key
  returning * into published_setting;

  if published_setting.key is null then
    raise exception 'Configuração não encontrada.' using errcode = 'P0002';
  end if;

  return published_setting;
end;
$$;

drop trigger if exists v2_profiles_touch_updated_at on public.v2_profiles;
create trigger v2_profiles_touch_updated_at
before update on public.v2_profiles
for each row execute function public.v2_touch_updated_at();

drop trigger if exists v2_roles_touch_updated_at on public.v2_user_roles;
create trigger v2_roles_touch_updated_at
before update on public.v2_user_roles
for each row execute function public.v2_touch_updated_at();

drop trigger if exists v2_content_archive_revision on public.v2_content;
create trigger v2_content_archive_revision
before update on public.v2_content
for each row execute function public.v2_archive_content_revision();

drop trigger if exists v2_settings_archive_revision on public.v2_game_settings;
create trigger v2_settings_archive_revision
before update on public.v2_game_settings
for each row execute function public.v2_archive_setting_revision();

drop trigger if exists on_auth_user_created_v2 on auth.users;
create trigger on_auth_user_created_v2
after insert on auth.users
for each row execute function public.v2_handle_new_user();

alter table public.v2_profiles enable row level security;
alter table public.v2_user_roles enable row level security;
alter table public.v2_content enable row level security;
alter table public.v2_content_revisions enable row level security;
alter table public.v2_game_settings enable row level security;
alter table public.v2_setting_revisions enable row level security;

drop policy if exists "v2 profiles readable by owner or admin" on public.v2_profiles;
create policy "v2 profiles readable by owner or admin"
on public.v2_profiles for select
using (user_id = auth.uid() or public.v2_is_admin());

drop policy if exists "v2 profiles editable by owner or admin" on public.v2_profiles;
create policy "v2 profiles editable by owner or admin"
on public.v2_profiles for update
using (user_id = auth.uid() or public.v2_is_admin())
with check (user_id = auth.uid() or public.v2_is_admin());

drop policy if exists "v2 roles readable by owner or admin" on public.v2_user_roles;
create policy "v2 roles readable by owner or admin"
on public.v2_user_roles for select
using (user_id = auth.uid() or public.v2_is_admin());

drop policy if exists "v2 roles managed by admins" on public.v2_user_roles;
create policy "v2 roles managed by admins"
on public.v2_user_roles for all
using (public.v2_is_admin())
with check (public.v2_is_admin());

drop policy if exists "v2 published content is public" on public.v2_content;
create policy "v2 published content is public"
on public.v2_content for select
using (status = 'published' or public.v2_is_admin());

drop policy if exists "v2 content managed by admins" on public.v2_content;
create policy "v2 content managed by admins"
on public.v2_content for all
using (public.v2_is_admin())
with check (public.v2_is_admin());

drop policy if exists "v2 content revisions readable by admins" on public.v2_content_revisions;
create policy "v2 content revisions readable by admins"
on public.v2_content_revisions for select
using (public.v2_is_admin());

drop policy if exists "v2 published settings are public" on public.v2_game_settings;
create policy "v2 published settings are public"
on public.v2_game_settings for select
using (status = 'published' or public.v2_is_admin());

drop policy if exists "v2 settings managed by admins" on public.v2_game_settings;
create policy "v2 settings managed by admins"
on public.v2_game_settings for all
using (public.v2_is_admin())
with check (public.v2_is_admin());

drop policy if exists "v2 setting revisions readable by admins" on public.v2_setting_revisions;
create policy "v2 setting revisions readable by admins"
on public.v2_setting_revisions for select
using (public.v2_is_admin());

grant select, insert, update, delete on public.v2_profiles to authenticated;
grant select, insert, update, delete on public.v2_user_roles to authenticated;
grant select on public.v2_content to anon, authenticated;
grant insert, update, delete on public.v2_content to authenticated;
grant select on public.v2_content_revisions to authenticated;
grant select on public.v2_game_settings to anon, authenticated;
grant insert, update, delete on public.v2_game_settings to authenticated;
grant select on public.v2_setting_revisions to authenticated;

revoke all on function public.v2_is_admin() from public;
grant execute on function public.v2_is_admin() to anon, authenticated;

revoke all on function public.v2_publish_content(uuid) from public;
grant execute on function public.v2_publish_content(uuid) to authenticated;

revoke all on function public.v2_publish_setting(text) from public;
grant execute on function public.v2_publish_setting(text) to authenticated;

insert into public.v2_game_settings (
  key,
  category,
  label,
  description,
  value,
  status,
  published_at
)
values
  (
    'character.base_attributes',
    'character',
    'Atributos iniciais',
    'Valor base recebido por todo novo personagem.',
    '{"FOR":20,"DEF":20,"RES":20,"INI":20,"INT":20,"ARC":20}'::jsonb,
    'published',
    now()
  ),
  (
    'character.distributable_points',
    'character',
    'Pontos distribuíveis',
    'Pontos livres disponíveis durante a criação do personagem.',
    '100'::jsonb,
    'published',
    now()
  ),
  (
    'character.maximum_slots',
    'account',
    'Limite de personagens',
    'Quantidade máxima de personagens por conta.',
    '3'::jsonb,
    'published',
    now()
  ),
  (
    'progression.maximum_level',
    'progression',
    'Nível máximo',
    'Maior nível alcançável por um personagem.',
    '100'::jsonb,
    'published',
    now()
  ),
  (
    'race.maximum_bonus_points',
    'race',
    'Limite de bônus raciais',
    'Quantidade máxima de pontos de atributo concedida por uma raça.',
    '25'::jsonb,
    'published',
    now()
  )
on conflict (key) do nothing;

commit;
